// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/audit/event.mesh.mx; change that file and rebuild.

import { z } from "zod";

import type { RecordEventInput, ReadEventInput, EventFilter } from "./event.types";

type Keys<T> = T extends Record<string, never> ? never : keyof T;

type SameShape<A, B> = [Keys<A>] extends [Keys<B>]
  ? [Keys<B>] extends [Keys<A>]
    ? [A] extends [B]
      ? [B] extends [A]
        ? true
        : false
      : false
    : false
  : false;

type Assert<T extends true> = T;

const comparison = <T extends z.ZodType>(value: T) =>
  z
    .strictObject({
      eq: value.nullable().exactOptional(),
      ne: value.nullable().exactOptional(),
      lt: value.exactOptional(),
      lte: value.exactOptional(),
      gt: value.exactOptional(),
      gte: value.exactOptional(),
      in: z.array(value).readonly().exactOptional(),
      nil: z.boolean().exactOptional(),
    })
    .refine((operators) => Object.keys(operators).length > 0, {
      message: "a comparison needs an operator",
    });

export const eventFilter: z.ZodType<EventFilter> = z.lazy(
  () =>
    z.union([
      z.strictObject({ and: z.array(eventFilter).readonly() }),
      z.strictObject({ or: z.array(eventFilter).readonly() }),
      z.strictObject({
        seq: comparison(z.int()).exactOptional(),
        type: comparison(z.string()).exactOptional(),
        schemaVersion: comparison(z.int()).exactOptional(),
        workspaceId: comparison(z.uuid()).exactOptional(),
        recordType: comparison(
          z.enum(["workspace", "collaborator", "membership", "task", "evidence-reference"]),
        ).exactOptional(),
        recordId: comparison(z.uuid()).exactOptional(),
        recordVersion: comparison(z.int()).exactOptional(),
        actor: comparison(z.string()).exactOptional(),
        caller: comparison(z.string()).exactOptional(),
        occurredAt: comparison(z.date()).exactOptional(),
        recordedAt: comparison(z.date()).exactOptional(),
        taskId: comparison(z.uuid()).exactOptional(),
      }),
    ]) as unknown as z.ZodType<EventFilter>,
);

export const eventSort = z
  .array(
    z.enum([
      "seq",
      "-seq",
      "type",
      "-type",
      "schemaVersion",
      "-schemaVersion",
      "workspaceId",
      "-workspaceId",
      "recordType",
      "-recordType",
      "recordId",
      "-recordId",
      "recordVersion",
      "-recordVersion",
      "actor",
      "-actor",
      "caller",
      "-caller",
      "occurredAt",
      "-occurredAt",
      "recordedAt",
      "-recordedAt",
      "taskId",
      "-taskId",
    ]),
  )
  .readonly();

export const recordEventInput = z.strictObject({
  type: z.string(),
  schemaVersion: z.int().min(1).optional(),
  workspaceId: z.uuid(),
  recordType: z.enum(["workspace", "collaborator", "membership", "task", "evidence-reference"]),
  recordId: z.uuid(),
  recordVersion: z.int().min(1),
  actor: z.string(),
  caller: z.string(),
  occurredAt: z.date(),
  cause: z
    .json()
    .refine((value) => value !== null, {
      message: "null is only allowed on a nullable attribute",
    }) as z.ZodType<unknown>,
  checks: (
    z
      .json()
      .refine((value) => value !== null, {
        message: "null is only allowed on a nullable attribute",
      }) as z.ZodType<unknown>
  )
    .nullable()
    .optional(),
  payload: z
    .json()
    .refine((value) => value !== null, {
      message: "null is only allowed on a nullable attribute",
    }) as z.ZodType<unknown>,
  task: z.uuid().nullable().optional(),
}) satisfies z.ZodType<RecordEventInput>;

export type RecordEventInputShape = Assert<
  SameShape<z.output<typeof recordEventInput>, RecordEventInput>
>;

export const readEventInput = z.strictObject({
  filter: eventFilter.optional(),
  sort: eventSort.optional(),
  limit: z.int().min(0).optional(),
  offset: z.int().min(0).optional(),
}) satisfies z.ZodType<ReadEventInput>;

export type ReadEventInputShape = Assert<
  SameShape<z.output<typeof readEventInput>, ReadEventInput>
>;
