// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/audit/event.mesh.mx; change that file and rebuild.

import type { Comparison as $Comparison } from "@meshfw/runtime";

import type { Task } from "../work/task.types";

export type Event = {
  seq: number;
  type: string;
  schemaVersion: number;
  workspaceId: string;
  recordType: "workspace" | "collaborator" | "membership" | "task" | "evidence-reference";
  recordId: string;
  recordVersion: number;
  actor: string;
  caller: string;
  occurredAt: Date;
  recordedAt: Date;
  cause: unknown;
  checks: unknown;
  payload: unknown;
  taskId: string | null;
};

export type RecordEventInput = {
  type: string;
  schemaVersion?: number | undefined;
  workspaceId: string;
  recordType: "workspace" | "collaborator" | "membership" | "task" | "evidence-reference";
  recordId: string;
  recordVersion: number;
  actor: string;
  caller: string;
  occurredAt: Date;
  cause: unknown;
  checks?: unknown | undefined;
  payload: unknown;
  task?: Task["id"] | null | undefined;
};

export type ReadEventInput = {
  filter?: EventFilter | undefined;
  sort?: EventSort | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

export type EventFilter =
  | { and: readonly EventFilter[] }
  | { or: readonly EventFilter[] }
  | {
      seq?: $Comparison<number>;
      type?: $Comparison<string>;
      schemaVersion?: $Comparison<number>;
      workspaceId?: $Comparison<string>;
      recordType?: $Comparison<
        "workspace" | "collaborator" | "membership" | "task" | "evidence-reference"
      >;
      recordId?: $Comparison<string>;
      recordVersion?: $Comparison<number>;
      actor?: $Comparison<string>;
      caller?: $Comparison<string>;
      occurredAt?: $Comparison<Date>;
      recordedAt?: $Comparison<Date>;
      taskId?: $Comparison<string>;
    };

export type EventSort = readonly (
  | "seq"
  | "-seq"
  | "type"
  | "-type"
  | "schemaVersion"
  | "-schemaVersion"
  | "workspaceId"
  | "-workspaceId"
  | "recordType"
  | "-recordType"
  | "recordId"
  | "-recordId"
  | "recordVersion"
  | "-recordVersion"
  | "actor"
  | "-actor"
  | "caller"
  | "-caller"
  | "occurredAt"
  | "-occurredAt"
  | "recordedAt"
  | "-recordedAt"
  | "taskId"
  | "-taskId"
)[];
