// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/audit/event.mesh.mx; change that file and rebuild.
// Mesh's own imports carry a `$` so that no entity name can shadow them.

import {
  parseInput,
  type ContextArgument as $ContextArgument,
  type DataLayer as $DataLayer,
} from "@meshfw/runtime";
import type { Event, RecordEventInput, ReadEventInput } from "./event.types";
import { recordEventInput, readEventInput } from "./event.validators";
import { tables } from "../schema";

export function bindEvent(layer: $DataLayer) {
  return Object.freeze({
    async record(input: RecordEventInput, ...[_context]: $ContextArgument): Promise<Event> {
      const parsed = await parseInput(recordEventInput, input);
      return layer.transaction(async (tx) => {
        const now = new Date();
        const row = await tx.insert(tables.event, {
          resource: parsed.resource,
          action: parsed.action,
          recordId: parsed.recordId,
          recordVersion: parsed.recordVersion === undefined ? null : parsed.recordVersion,
          actorId: parsed.actorId === undefined ? null : parsed.actorId,
          caller: parsed.caller === undefined ? null : parsed.caller,
          commandId: parsed.commandId === undefined ? null : parsed.commandId,
          changes: parsed.changes === undefined ? {} : parsed.changes,
          occurredAt: now,
          taskId: parsed.task === undefined ? null : parsed.task,
        });
        return row as Event;
      });
    },

    async read(input: ReadEventInput, ...[_context]: $ContextArgument): Promise<Event[]> {
      const parsed = await parseInput(readEventInput, input);
      return layer.transaction(async (tx) => {
        return (await tx.select(tables.event, {
          filter: parsed.filter,
          sort: parsed.sort,
          limit: parsed.limit,
          offset: parsed.offset,
        })) as Event[];
      });
    },
  });
}
