// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/audit/event.mesh.mx; change that file and rebuild.

import type { Comparison as $Comparison } from "@meshfw/runtime";

import type { Task } from "../work/task.types";

export type Event = {
  seq: number;
  resource: string;
  action: string;
  recordId: string;
  recordVersion: number | null;
  actorId: string | null;
  caller: string | null;
  commandId: string | null;
  changes: unknown;
  occurredAt: Date;
  taskId: string | null;
};

export type RecordEventInput = {
  resource: string;
  action: string;
  recordId: string;
  recordVersion?: number | null | undefined;
  actorId?: string | null | undefined;
  caller?: string | null | undefined;
  commandId?: string | null | undefined;
  changes?: unknown | undefined;
  task?: Task["id"] | null | undefined;
};

export type ReadEventInput = {
  filter?: EventFilter | undefined;
  sort?: EventSort | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

export type EventFilter =
  | { and: readonly EventFilter[] }
  | { or: readonly EventFilter[] }
  | {
      seq?: $Comparison<number>;
      resource?: $Comparison<string>;
      action?: $Comparison<string>;
      recordId?: $Comparison<string>;
      recordVersion?: $Comparison<number>;
      actorId?: $Comparison<string>;
      caller?: $Comparison<string>;
      commandId?: $Comparison<string>;
      occurredAt?: $Comparison<Date>;
      taskId?: $Comparison<string>;
    };

export type EventSort = readonly (
  | "seq"
  | "-seq"
  | "resource"
  | "-resource"
  | "action"
  | "-action"
  | "recordId"
  | "-recordId"
  | "recordVersion"
  | "-recordVersion"
  | "actorId"
  | "-actorId"
  | "caller"
  | "-caller"
  | "commandId"
  | "-commandId"
  | "occurredAt"
  | "-occurredAt"
  | "taskId"
  | "-taskId"
)[];
