// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/audit/event.mesh.mx; change that file and rebuild.

import { z } from "zod";

import type { RecordEventInput, ReadEventInput, EventFilter } from "./event.types";

type Keys<T> = T extends Record<string, never> ? never : keyof T;

type SameShape<A, B> = [Keys<A>] extends [Keys<B>]
  ? [Keys<B>] extends [Keys<A>]
    ? [A] extends [B]
      ? [B] extends [A]
        ? true
        : false
      : false
    : false
  : false;

type Assert<T extends true> = T;

const comparison = <T extends z.ZodType>(value: T) =>
  z.strictObject({
    eq: value.nullable().optional(),
    ne: value.nullable().optional(),
    lt: value.optional(),
    lte: value.optional(),
    gt: value.optional(),
    gte: value.optional(),
    in: z.array(value).readonly().optional(),
    nil: z.boolean().optional(),
  });

// The cast is the schema's only gap: zod writes an absent key as `?: T | undefined`, which the
// strictest `exactOptionalPropertyTypes` setting does not let the filter type accept.
export const eventFilter: z.ZodType<EventFilter> = z.lazy(
  () =>
    z.union([
      z.strictObject({ and: z.array(eventFilter).readonly() }),
      z.strictObject({ or: z.array(eventFilter).readonly() }),
      z.strictObject({
        seq: comparison(z.int()).optional(),
        resource: comparison(z.string()).optional(),
        action: comparison(z.string()).optional(),
        recordId: comparison(z.uuid()).optional(),
        recordVersion: comparison(z.int()).optional(),
        actorId: comparison(z.uuid()).optional(),
        caller: comparison(z.string()).optional(),
        commandId: comparison(z.string()).optional(),
        occurredAt: comparison(z.date()).optional(),
        taskId: comparison(z.string()).optional(),
      }),
    ]) as unknown as z.ZodType<EventFilter>,
);

export const eventSort = z
  .array(
    z.enum([
      "seq",
      "-seq",
      "resource",
      "-resource",
      "action",
      "-action",
      "recordId",
      "-recordId",
      "recordVersion",
      "-recordVersion",
      "actorId",
      "-actorId",
      "caller",
      "-caller",
      "commandId",
      "-commandId",
      "occurredAt",
      "-occurredAt",
      "taskId",
      "-taskId",
    ]),
  )
  .readonly();

export const recordEventInput = z.strictObject({
  resource: z.string(),
  action: z.string(),
  recordId: z.uuid(),
  recordVersion: z.int().nullable().optional(),
  actorId: z.uuid().nullable().optional(),
  caller: z.string().nullable().optional(),
  commandId: z.string().nullable().optional(),
  changes: (
    z
      .json()
      .refine((value) => value !== null, {
        message: "null is only allowed on a nullable attribute",
      }) as z.ZodType<unknown>
  ).optional(),
  task: z.uuid().nullable().optional(),
}) satisfies z.ZodType<RecordEventInput>;

export type RecordEventInputShape = Assert<
  SameShape<z.output<typeof recordEventInput>, RecordEventInput>
>;

export const readEventInput = z.strictObject({
  filter: eventFilter.optional(),
  sort: eventSort.optional(),
  limit: z.int().min(0).optional(),
  offset: z.int().min(0).optional(),
}) satisfies z.ZodType<ReadEventInput>;

export type ReadEventInputShape = Assert<
  SameShape<z.output<typeof readEventInput>, ReadEventInput>
>;
