// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/blog/comment.mesh.mx; change that file and rebuild.
// Mesh's own imports carry a `$` so that no entity name can shadow them.

import {
  parseInput,
  type ContextArgument as $ContextArgument,
  type DataLayer as $DataLayer,
} from "@meshfw/runtime";
import type { Comment, ReadCommentInput } from "./comment.types";
import { readCommentInput } from "./comment.validators";
import { tables } from "../schema";

export function bindComment(layer: $DataLayer) {
  return Object.freeze({
    async read(input: ReadCommentInput, ...[_context]: $ContextArgument): Promise<Comment[]> {
      const parsed = await parseInput(readCommentInput, input);
      return layer.transaction(async (tx) => {
        return (await tx.select(tables.comment, {
          filter: parsed.filter,
          sort: parsed.sort,
          limit: parsed.limit,
          offset: parsed.offset,
        })) as Comment[];
      });
    },
  });
}
