// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/blog/comment.mesh.mx; change that file and rebuild.

import { parseInput, type ContextArgument, type DataLayer } from "@meshfw/runtime";
import type { Comment, ReadCommentInput } from "./comment.types";
import { readCommentInput } from "./comment.validators";
import { tables } from "../schema";

export function bindComment(layer: DataLayer) {
  return Object.freeze({
    async read(input: ReadCommentInput, ...[_context]: ContextArgument): Promise<Comment[]> {
      await parseInput(readCommentInput, input);
      return layer.transaction(async (tx) => {
        return (await tx.selectAll(tables.comment)) as Comment[];
      });
    },
  });
}
