// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/blog/comment.mesh.mx; change that file and rebuild.

import { z } from "zod";

import type { ReadCommentInput, CommentFilter } from "./comment.types";

type Keys<T> = T extends Record<string, never> ? never : keyof T;

type SameShape<A, B> = [Keys<A>] extends [Keys<B>]
  ? [Keys<B>] extends [Keys<A>]
    ? [A] extends [B]
      ? [B] extends [A]
        ? true
        : false
      : false
    : false
  : false;

type Assert<T extends true> = T;

const comparison = <T extends z.ZodType>(value: T) =>
  z
    .strictObject({
      eq: value.nullable().exactOptional(),
      ne: value.nullable().exactOptional(),
      lt: value.exactOptional(),
      lte: value.exactOptional(),
      gt: value.exactOptional(),
      gte: value.exactOptional(),
      in: z.array(value).readonly().exactOptional(),
      nil: z.boolean().exactOptional(),
    })
    .refine((operators) => Object.keys(operators).length > 0, {
      message: "a comparison needs an operator",
    });

export const commentFilter: z.ZodType<CommentFilter> = z.lazy(
  () =>
    z.union([
      z.strictObject({ and: z.array(commentFilter).readonly() }),
      z.strictObject({ or: z.array(commentFilter).readonly() }),
      z.strictObject({
        id: comparison(z.uuid()).exactOptional(),
        body: comparison(z.string()).exactOptional(),
        postId: comparison(z.uuid()).exactOptional(),
      }),
    ]) as unknown as z.ZodType<CommentFilter>,
);

export const commentSort = z
  .array(z.enum(["id", "-id", "body", "-body", "postId", "-postId"]))
  .readonly();

export const readCommentInput = z.strictObject({
  filter: commentFilter.optional(),
  sort: commentSort.optional(),
  limit: z.int().min(0).optional(),
  offset: z.int().min(0).optional(),
}) satisfies z.ZodType<ReadCommentInput>;

export type ReadCommentInputShape = Assert<
  SameShape<z.output<typeof readCommentInput>, ReadCommentInput>
>;
