// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/blog/comment.mesh.mx; change that file and rebuild.

import { z } from "zod";

import type { ReadCommentInput } from "./comment.types";

type Keys<T> = T extends Record<string, never> ? never : keyof T;

type SameShape<A, B> = [Keys<A>] extends [Keys<B>]
  ? [Keys<B>] extends [Keys<A>]
    ? [A] extends [B]
      ? [B] extends [A]
        ? true
        : false
      : false
    : false
  : false;

type Assert<T extends true> = T;

export const readCommentInput = z.strictObject({}) satisfies z.ZodType<ReadCommentInput>;

export type ReadCommentInputShape = Assert<
  SameShape<z.output<typeof readCommentInput>, ReadCommentInput>
>;
