// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/blog/comment.mesh.mx; change that file and rebuild.
// Mesh's own imports carry a `$` so that no entity name can shadow them.

import {
  parseInput,
  type BindOptions as $BindOptions,
  type Composer as $Composer,
  type ContextArgument as $ContextArgument,
  type DataLayer as $DataLayer,
} from "@meshfw/runtime";
import type { Comment, ReadCommentInput } from "./comment.types";
import { readCommentInput } from "./comment.validators";
import { tables } from "../schema";

/**
 * The reads of this entity without the authorizer slot: what `tx` holds in a function of an entity file (ADR-0068).
 * The read actions below run the slot, then these.
 */
export function bindCommentReads(layer: $DataLayer) {
  return Object.freeze({
    async read(input: ReadCommentInput): Promise<Comment[]> {
      // enter, cast: only the declared input passes
      const parsed = await parseInput(readCommentInput, input);
      return layer.transaction(async (tx) => {
        return (await tx.select(tables.comment, {
          filter: parsed.filter,
          sort: parsed.sort,
          limit: parsed.limit,
          offset: parsed.offset,
        })) as Comment[];
      });
    },
  });
}

/**
 * Every action of this entity, bound to `layer`. `compose` is the binding's composer, which hands a function its
 * `actions` and `tx`; the project's `bind` in the index passes it.
 */
export function bindComment(layer: $DataLayer, _options: $BindOptions = {}, _compose?: $Composer) {
  const $reads = bindCommentReads(layer);
  return Object.freeze({
    async read(input: ReadCommentInput, ...[_context]: $ContextArgument): Promise<Comment[]> {
      // pre-check: the read authorizer slot stays empty until policies (M8); a read through `tx` skips it
      return $reads.read(input);
    },
  });
}
