// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/blog/post.mesh.mx; change that file and rebuild.

import type { Comparison as $Comparison } from "@meshfw/runtime";

import type { User } from "./user.types";

import type { Comment, CommentLoaded } from "./comment.types";

export type Post = {
  id: string;
  title: string;
  body: string | null;
  views: number;
  rating: number | null;
  price: number;
  featured: boolean;
  publicationDate: Date | null;
  publishedAt: Date | null;
  state: "draft" | "published";
  metadata: unknown;
  insertedAt: Date;
  updatedAt: Date;
  authorId: string;
};

export type CreatePostInput = {
  title: string;
  body?: string | null | undefined;
  metadata?: unknown | undefined;
  author: User["id"];
};

export type PublishPostInput = {
  id: string;
};

export type ArchivePostInput = {
  id: string;
};

export type PublishedPostInput = {
  filter?: PostFilter | undefined;
  sort?: PostSort | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

export type ReadPostInput = {
  filter?: PostFilter | undefined;
  sort?: PostSort | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

export type DestroyPostInput = {
  id: string;
};

/** What `load` attaches to a Post. The record has none of it, so reading one that was not loaded is a type error. */
export type PostLoadable = {
  author: User;
  comments: Comment[];
  excerpt: string;
  commentCount: number;
};

/** A Post with the relationships and computed fields named in N loaded. */
export type PostWith<N extends keyof PostLoadable> = Post & Pick<PostLoadable, N>;

/** A Post as the functions of its entity file see it: every relationship and computed field present, and each related record the same. */
export type PostLoaded = Post & {
  author: User;
  comments: CommentLoaded[];
  excerpt: string;
  commentCount: number;
};

export type PostFilter =
  | { and: readonly PostFilter[] }
  | { or: readonly PostFilter[] }
  | {
      id?: $Comparison<string>;
      title?: $Comparison<string>;
      body?: $Comparison<string>;
      views?: $Comparison<number>;
      rating?: $Comparison<number>;
      price?: $Comparison<number>;
      featured?: $Comparison<boolean>;
      publicationDate?: $Comparison<Date>;
      publishedAt?: $Comparison<Date>;
      state?: $Comparison<"draft" | "published">;
      insertedAt?: $Comparison<Date>;
      updatedAt?: $Comparison<Date>;
      authorId?: $Comparison<string>;
      excerpt?: $Comparison<string>;
      commentCount?: $Comparison<number>;
    };

export type PostSort = readonly (
  | "id"
  | "-id"
  | "title"
  | "-title"
  | "body"
  | "-body"
  | "views"
  | "-views"
  | "rating"
  | "-rating"
  | "price"
  | "-price"
  | "featured"
  | "-featured"
  | "publicationDate"
  | "-publicationDate"
  | "publishedAt"
  | "-publishedAt"
  | "state"
  | "-state"
  | "insertedAt"
  | "-insertedAt"
  | "updatedAt"
  | "-updatedAt"
  | "authorId"
  | "-authorId"
  | "excerpt"
  | "-excerpt"
  | "commentCount"
  | "-commentCount"
)[];
