// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/blog/post.mesh.mx; change that file and rebuild.

import {
  FrameworkError,
  NotFoundError,
  parseInput,
  type ContextArgument,
  type DataLayer,
} from "@meshfw/runtime";
import type {
  Post,
  CreatePostInput,
  PublishPostInput,
  ArchivePostInput,
  PublishedPostInput,
  ReadPostInput,
  DestroyPostInput,
} from "./post.types";
import {
  createPostInput,
  publishPostInput,
  archivePostInput,
  publishedPostInput,
  readPostInput,
  destroyPostInput,
} from "./post.validators";
import { tables } from "../schema";

export function bindPost(layer: DataLayer) {
  return Object.freeze({
    async create(input: CreatePostInput, ...[_context]: ContextArgument): Promise<Post> {
      // Not run in this version: on:load published
      const parsed = await parseInput(createPostInput, input);
      return layer.transaction(async (tx) => {
        const now = new Date();
        const row = await tx.insert(tables.post, {
          id: crypto.randomUUID(),
          title: parsed.title,
          body: parsed.body === undefined ? null : parsed.body,
          views: 0,
          rating: null,
          price: 0,
          featured: false,
          publicationDate: null,
          publishedAt: null,
          state: "draft",
          insertedAt: now,
          updatedAt: now,
          authorId: parsed.author,
        });
        return row as Post;
      });
    },

    async publish(input: PublishPostInput, ...[_context]: ContextArgument): Promise<Post> {
      // Not run in this version: validate titlePresent; load comments, excerpt; on:load published; policies owner
      const parsed = await parseInput(publishPostInput, input);
      return layer.transaction(async (tx) => {
        const key = { id: parsed.id };
        const changes: Partial<Post> = {};
        changes.state = "published";
        const now = new Date();
        changes.updatedAt = now;
        const row = await tx.updateByKey(tables.post, key, changes);
        if (row === undefined) throw new NotFoundError("Post", key);
        return row as Post;
      });
    },

    async archive(input: ArchivePostInput, ...[_context]: ContextArgument): Promise<void> {
      // Not run in this version: policies owner
      const parsed = await parseInput(archivePostInput, input);
      return layer.transaction(async (tx) => {
        const key = { id: parsed.id };
        if (!(await tx.deleteByKey(tables.post, key))) throw new NotFoundError("Post", key);
      });
    },

    async published(input: PublishedPostInput, ...[_context]: ContextArgument): Promise<Post[]> {
      // Not run in this version: on:load published; policies public
      await parseInput(publishedPostInput, input);
      throw new FrameworkError(
        "publishedPost cannot run in this version: its filter and sort are evaluated from M4",
      );
    },

    async read(input: ReadPostInput, ...[_context]: ContextArgument): Promise<Post[]> {
      // Not run in this version: on:load published; policies public
      await parseInput(readPostInput, input);
      return layer.transaction(async (tx) => {
        return (await tx.selectAll(tables.post)) as Post[];
      });
    },

    async destroy(input: DestroyPostInput, ...[_context]: ContextArgument): Promise<void> {
      const parsed = await parseInput(destroyPostInput, input);
      return layer.transaction(async (tx) => {
        const key = { id: parsed.id };
        if (!(await tx.deleteByKey(tables.post, key))) throw new NotFoundError("Post", key);
      });
    },
  });
}
