// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/blog/post.mesh.mx; change that file and rebuild.

import { z } from "zod";

import type {
  CreatePostInput,
  PublishPostInput,
  ArchivePostInput,
  PublishedPostInput,
  ReadPostInput,
  DestroyPostInput,
} from "./post.types";

type Keys<T> = T extends Record<string, never> ? never : keyof T;

type SameShape<A, B> = [Keys<A>] extends [Keys<B>]
  ? [Keys<B>] extends [Keys<A>]
    ? [A] extends [B]
      ? [B] extends [A]
        ? true
        : false
      : false
    : false
  : false;

type Assert<T extends true> = T;

export const createPostInput = z.strictObject({
  title: z.string().min(1).max(200),
  body: z.string().nullable().optional(),
  author: z.uuid(),
}) satisfies z.ZodType<CreatePostInput>;

export type CreatePostInputShape = Assert<
  SameShape<z.output<typeof createPostInput>, CreatePostInput>
>;

export const publishPostInput = z.strictObject({
  id: z.uuid(),
}) satisfies z.ZodType<PublishPostInput>;

export type PublishPostInputShape = Assert<
  SameShape<z.output<typeof publishPostInput>, PublishPostInput>
>;

export const archivePostInput = z.strictObject({
  id: z.uuid(),
}) satisfies z.ZodType<ArchivePostInput>;

export type ArchivePostInputShape = Assert<
  SameShape<z.output<typeof archivePostInput>, ArchivePostInput>
>;

export const publishedPostInput = z.strictObject({}) satisfies z.ZodType<PublishedPostInput>;

export type PublishedPostInputShape = Assert<
  SameShape<z.output<typeof publishedPostInput>, PublishedPostInput>
>;

export const readPostInput = z.strictObject({}) satisfies z.ZodType<ReadPostInput>;

export type ReadPostInputShape = Assert<SameShape<z.output<typeof readPostInput>, ReadPostInput>>;

export const destroyPostInput = z.strictObject({
  id: z.uuid(),
}) satisfies z.ZodType<DestroyPostInput>;

export type DestroyPostInputShape = Assert<
  SameShape<z.output<typeof destroyPostInput>, DestroyPostInput>
>;
