// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/blog/user.mesh.mx; change that file and rebuild.
// Mesh's own imports carry a `$` so that no entity name can shadow them.

import {
  castInput as $castInput,
  noteWrite as $noteWrite,
  type BindOptions as $BindOptions,
  type Composer as $Composer,
  type ContextArgument as $ContextArgument,
  type DataLayer as $DataLayer,
  type Row as $Row,
} from "@meshfw/runtime";
import type { User, CreateUserInput, ReadUserInput } from "./user.types";
import { createUserInput, readUserInput } from "./user.validators";
import { tables } from "../schema";

/**
 * The reads of this entity without the authorizer slot: what `tx` holds in a function of an entity file (ADR-0068).
 * The read actions below run the slot, then these.
 */
export function bindUserReads(layer: $DataLayer) {
  return Object.freeze({
    async read(input: ReadUserInput): Promise<User[]> {
      // enter, cast: only the declared input passes; a failed cast inside a transaction fails it
      const parsed = await $castInput(layer, readUserInput, input);
      return layer.transaction(async (tx) => {
        return (await tx.select(tables.user, {
          filter: parsed.filter,
          sort: parsed.sort,
          limit: parsed.limit,
          offset: parsed.offset,
        })) as User[];
      });
    },
  });
}

/**
 * Every action of this entity, bound to `layer`. `compose` is the binding's composer, which hands a function its
 * `actions` and `tx`; the project's `bind` in the index passes it.
 */
export function bindUser(layer: $DataLayer, _options: $BindOptions = {}, _compose?: $Composer) {
  const $reads = bindUserReads(layer);
  return Object.freeze({
    async create(input: CreateUserInput, ...[_context]: $ContextArgument): Promise<User> {
      // enter, cast: the call arrives with its context, and only the declared input passes; a failed cast inside a transaction fails it
      const parsed = await $castInput(layer, createUserInput, input);
      return layer.transaction(async (tx) => {
        // transaction: opens here; what follows commits together or not at all (pre-check: the authorizer slot before it stays empty until policies, M8)
        // plan: a create is one insert; nothing is read first
        const $changes: $Row = {
          name: parsed.name,
        };
        // data layer
        const $stored = await tx.insert(tables.user, $changes);
        $noteWrite(tx);
        return $stored as User;
      });
    },

    async read(input: ReadUserInput, ...[_context]: $ContextArgument): Promise<User[]> {
      // pre-check: the read authorizer slot stays empty until policies (M8); a read through `tx` skips it
      return $reads.read(input);
    },
  });
}
