// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/blog/user.mesh.mx; change that file and rebuild.

import { z } from "zod";

import type { CreateUserInput, ReadUserInput, UserFilter } from "./user.types";

type Keys<T> = T extends Record<string, never> ? never : keyof T;

type SameShape<A, B> = [Keys<A>] extends [Keys<B>]
  ? [Keys<B>] extends [Keys<A>]
    ? [A] extends [B]
      ? [B] extends [A]
        ? true
        : false
      : false
    : false
  : false;

type Assert<T extends true> = T;

const comparison = <T extends z.ZodType>(value: T) =>
  z
    .strictObject({
      eq: value.nullable().exactOptional(),
      ne: value.nullable().exactOptional(),
      lt: value.exactOptional(),
      lte: value.exactOptional(),
      gt: value.exactOptional(),
      gte: value.exactOptional(),
      in: z.array(value).readonly().exactOptional(),
      nil: z.boolean().exactOptional(),
    })
    .refine((operators) => Object.keys(operators).length > 0, {
      message: "a comparison needs an operator",
    });

export const userFilter: z.ZodType<UserFilter> = z.lazy(
  () =>
    z.union([
      z.strictObject({ and: z.array(userFilter).readonly() }),
      z.strictObject({ or: z.array(userFilter).readonly() }),
      z.strictObject({
        id: comparison(z.uuid()).exactOptional(),
        name: comparison(z.string()).exactOptional(),
      }),
    ]) as unknown as z.ZodType<UserFilter>,
);

export const userSort = z.array(z.enum(["id", "-id", "name", "-name"])).readonly();

export const createUserInput = z.strictObject({
  name: z.string(),
}) satisfies z.ZodType<CreateUserInput>;

export type CreateUserInputShape = Assert<
  SameShape<z.output<typeof createUserInput>, CreateUserInput>
>;

export const readUserInput = z.strictObject({
  filter: userFilter.optional(),
  sort: userSort.optional(),
  limit: z.int().min(0).optional(),
  offset: z.int().min(0).optional(),
}) satisfies z.ZodType<ReadUserInput>;

export type ReadUserInputShape = Assert<SameShape<z.output<typeof readUserInput>, ReadUserInput>>;
