// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/blog/user.mesh.mx; change that file and rebuild.

import { z } from "zod";

import type { ReadUserInput } from "./user.types";

type Keys<T> = T extends Record<string, never> ? never : keyof T;

type SameShape<A, B> = [Keys<A>] extends [Keys<B>]
  ? [Keys<B>] extends [Keys<A>]
    ? [A] extends [B]
      ? [B] extends [A]
        ? true
        : false
      : false
    : false
  : false;

type Assert<T extends true> = T;

export const readUserInput = z.strictObject({}) satisfies z.ZodType<ReadUserInput>;

export type ReadUserInputShape = Assert<SameShape<z.output<typeof readUserInput>, ReadUserInput>>;
