// Do not edit this file by hand.
// It is generated by `mesh build` from the entity files; change them and rebuild.
// Import it as "#mesh"; the other files in this folder are an implementation detail.
// Mesh's own imports and internal names carry a `$` so that no entity or action name can collide with them.

import {
  FrameworkError as $FrameworkError,
  type ContextArgument as $ContextArgument,
  type DataLayer as $DataLayer,
} from "@meshfw/runtime";
import { bindComment } from "./blog/comment.actions";
import type { Comment, ReadCommentInput, CommentFilter, CommentSort } from "./blog/comment.types";
import { bindPost } from "./blog/post.actions";
import type {
  Post,
  CreatePostInput,
  PublishPostInput,
  ArchivePostInput,
  PublishedPostInput,
  ReadPostInput,
  DestroyPostInput,
  PostFilter,
  PostSort,
} from "./blog/post.types";
import { bindUser } from "./blog/user.actions";
import type { User, CreateUserInput, ReadUserInput, UserFilter, UserSort } from "./blog/user.types";

export type {
  Comment,
  ReadCommentInput,
  CommentFilter,
  CommentSort,
  Post,
  CreatePostInput,
  PublishPostInput,
  ArchivePostInput,
  PublishedPostInput,
  ReadPostInput,
  DestroyPostInput,
  PostFilter,
  PostSort,
  User,
  CreateUserInput,
  ReadUserInput,
  UserFilter,
  UserSort,
};
export { tables, commentTable, postTable, userTable } from "./schema";

/**
 * Every action function, bound to `layer`. Opens nothing and creates no table:
 * the caller owns the layer and closes it.
 */
export function bind(layer: $DataLayer) {
  const commentActions = bindComment(layer);
  const postActions = bindPost(layer);
  const userActions = bindUser(layer);
  return Object.freeze({
    readComment: commentActions.read,
    createPost: postActions.create,
    publishPost: postActions.publish,
    archivePost: postActions.archive,
    publishedPost: postActions.published,
    readPost: postActions.read,
    destroyPost: postActions.destroy,
    createUser: userActions.create,
    readUser: userActions.read,
  });
}

let $defaultBinding: ReturnType<typeof bind> | undefined;
let $defaultLayer: $DataLayer | undefined;
let $disconnecting: Promise<void> | undefined;
/** Calls through the top-level functions that have not settled; `disconnect()` waits for them. */
let $inFlight = 0;
const $idle: (() => void)[] = [];

function $isDataLayer(value: unknown): value is $DataLayer {
  return (
    typeof value === "object" &&
    value !== null &&
    typeof (value as Partial<$DataLayer>).transaction === "function" &&
    typeof (value as Partial<$DataLayer>).close === "function"
  );
}

/**
 * Bind every action function to the data layer `mesh.config.ts` configures. The
 * layer opens on the first transaction. Waits for a `disconnect()` in progress;
 * throws `FrameworkError` while connected.
 */
export async function connect(): Promise<void> {
  if ($disconnecting) await $disconnecting;
  if ($defaultLayer)
    throw new $FrameworkError("connect() was called while connected; call disconnect() first");
  const { default: config } = await import("../mesh.config");
  const data: unknown = config.data;
  if (!$isDataLayer(data))
    throw new $FrameworkError(
      `The data adapter "${config.data.name}" configured in mesh.config.ts has no run-time half: connect() needs a data layer with transaction() and close()`,
    );
  if ($defaultLayer)
    throw new $FrameworkError("connect() was called while connected; call disconnect() first");
  $defaultBinding = bind(data);
  $defaultLayer = data;
}

/**
 * Stop new calls, wait for the calls already made through the top-level functions to
 * settle, however long they take, then close the layer `connect()` bound. Does nothing
 * when not connected. If `close()` rejects, the binding is restored and the program
 * stays connected, so `disconnect()` can be called again. Never closes a layer passed
 * to `bind`.
 */
export async function disconnect(): Promise<void> {
  if ($disconnecting) return $disconnecting;
  const layer = $defaultLayer;
  const binding = $defaultBinding;
  if (!layer || !binding) return;
  $defaultBinding = undefined;
  $defaultLayer = undefined;
  $disconnecting = (async () => {
    while ($inFlight > 0) await new Promise<void>((resolve) => $idle.push(resolve));
    try {
      await layer.close();
    } catch (error) {
      $defaultBinding = binding;
      $defaultLayer = layer;
      throw error;
    }
  })();
  try {
    await $disconnecting;
  } finally {
    $disconnecting = undefined;
  }
}

/** Run one call on the default binding, counted so that `disconnect()` waits for it. */
async function $delegate<T>(
  name: string,
  call: (binding: ReturnType<typeof bind>) => Promise<T>,
): Promise<T> {
  if (!$defaultBinding)
    throw new $FrameworkError(
      `${name} was called while not connected: call connect() first, or use bind(db) with a data layer of your own`,
    );
  $inFlight++;
  try {
    return await call($defaultBinding);
  } finally {
    $inFlight--;
    if ($inFlight === 0) for (const resolve of $idle.splice(0)) resolve();
  }
}

export async function readComment(
  input: ReadCommentInput,
  ...context: $ContextArgument
): Promise<Comment[]> {
  return $delegate("readComment", (binding) => binding.readComment(input, ...context));
}

export async function createPost(
  input: CreatePostInput,
  ...context: $ContextArgument
): Promise<Post> {
  return $delegate("createPost", (binding) => binding.createPost(input, ...context));
}

export async function publishPost(
  input: PublishPostInput,
  ...context: $ContextArgument
): Promise<Post> {
  return $delegate("publishPost", (binding) => binding.publishPost(input, ...context));
}

export async function archivePost(
  input: ArchivePostInput,
  ...context: $ContextArgument
): Promise<void> {
  return $delegate("archivePost", (binding) => binding.archivePost(input, ...context));
}

export async function publishedPost(
  input: PublishedPostInput,
  ...context: $ContextArgument
): Promise<Post[]> {
  return $delegate("publishedPost", (binding) => binding.publishedPost(input, ...context));
}

export async function readPost(
  input: ReadPostInput,
  ...context: $ContextArgument
): Promise<Post[]> {
  return $delegate("readPost", (binding) => binding.readPost(input, ...context));
}

export async function destroyPost(
  input: DestroyPostInput,
  ...context: $ContextArgument
): Promise<void> {
  return $delegate("destroyPost", (binding) => binding.destroyPost(input, ...context));
}

export async function createUser(
  input: CreateUserInput,
  ...context: $ContextArgument
): Promise<User> {
  return $delegate("createUser", (binding) => binding.createUser(input, ...context));
}

export async function readUser(
  input: ReadUserInput,
  ...context: $ContextArgument
): Promise<User[]> {
  return $delegate("readUser", (binding) => binding.readUser(input, ...context));
}
