// Do not edit this file by hand.
// It is generated by `mesh build` from the entity files; change them and rebuild.
// Import it as "#mesh"; the other files in this folder are an implementation detail.

import { FrameworkError, type ContextArgument, type DataLayer } from "@meshfw/runtime";
import { bindComment } from "./blog/comment.actions";
import type { Comment, ReadCommentInput } from "./blog/comment.types";
import { bindPost } from "./blog/post.actions";
import type {
  Post,
  CreatePostInput,
  PublishPostInput,
  ArchivePostInput,
  PublishedPostInput,
  ReadPostInput,
  DestroyPostInput,
} from "./blog/post.types";
import { bindUser } from "./blog/user.actions";
import type { User, CreateUserInput, ReadUserInput } from "./blog/user.types";

export type {
  Comment,
  ReadCommentInput,
  Post,
  CreatePostInput,
  PublishPostInput,
  ArchivePostInput,
  PublishedPostInput,
  ReadPostInput,
  DestroyPostInput,
  User,
  CreateUserInput,
  ReadUserInput,
};
export { tables, commentTable, postTable, userTable } from "./schema";

/**
 * Every action function, bound to `layer`. Opens nothing and creates no table:
 * the caller owns the layer and closes it.
 */
export function bind(layer: DataLayer) {
  const comment = bindComment(layer);
  const post = bindPost(layer);
  const user = bindUser(layer);
  return Object.freeze({
    readComment: comment.read,
    createPost: post.create,
    publishPost: post.publish,
    archivePost: post.archive,
    publishedPost: post.published,
    readPost: post.read,
    destroyPost: post.destroy,
    createUser: user.create,
    readUser: user.read,
  });
}

let defaultBinding: ReturnType<typeof bind> | undefined;
let defaultLayer: DataLayer | undefined;

function isDataLayer(value: unknown): value is DataLayer {
  return (
    typeof value === "object" &&
    value !== null &&
    typeof (value as Partial<DataLayer>).transaction === "function" &&
    typeof (value as Partial<DataLayer>).close === "function"
  );
}

/**
 * Bind every action function to the data layer `mesh.config.ts` configures. The
 * layer opens on the first transaction. Throws `FrameworkError` while connected.
 */
export async function connect(): Promise<void> {
  if (defaultLayer)
    throw new FrameworkError("connect() was called while connected; call disconnect() first");
  const { default: config } = await import("../mesh.config");
  const data: unknown = config.data;
  if (!isDataLayer(data))
    throw new FrameworkError(
      `The data adapter "${config.data.name}" configured in mesh.config.ts has no run-time half: connect() needs a data layer with transaction() and close()`,
    );
  if (defaultLayer)
    throw new FrameworkError("connect() was called while connected; call disconnect() first");
  defaultBinding = bind(data);
  defaultLayer = data;
}

/** Close the layer `connect()` bound and forget it; does nothing when not connected. Never closes a layer passed to `bind`. */
export async function disconnect(): Promise<void> {
  const layer = defaultLayer;
  if (!layer) return;
  await layer.close();
  defaultBinding = undefined;
  defaultLayer = undefined;
}

function connected(name: string): ReturnType<typeof bind> {
  if (!defaultBinding)
    throw new FrameworkError(
      `${name} was called while not connected: call connect() first, or use bind(db) with a data layer of your own`,
    );
  return defaultBinding;
}

export async function readComment(
  input: ReadCommentInput,
  ...context: ContextArgument
): Promise<Comment[]> {
  return connected("readComment").readComment(input, ...context);
}

export async function createPost(
  input: CreatePostInput,
  ...context: ContextArgument
): Promise<Post> {
  return connected("createPost").createPost(input, ...context);
}

export async function publishPost(
  input: PublishPostInput,
  ...context: ContextArgument
): Promise<Post> {
  return connected("publishPost").publishPost(input, ...context);
}

export async function archivePost(
  input: ArchivePostInput,
  ...context: ContextArgument
): Promise<void> {
  return connected("archivePost").archivePost(input, ...context);
}

export async function publishedPost(
  input: PublishedPostInput,
  ...context: ContextArgument
): Promise<Post[]> {
  return connected("publishedPost").publishedPost(input, ...context);
}

export async function readPost(input: ReadPostInput, ...context: ContextArgument): Promise<Post[]> {
  return connected("readPost").readPost(input, ...context);
}

export async function destroyPost(
  input: DestroyPostInput,
  ...context: ContextArgument
): Promise<void> {
  return connected("destroyPost").destroyPost(input, ...context);
}

export async function createUser(
  input: CreateUserInput,
  ...context: ContextArgument
): Promise<User> {
  return connected("createUser").createUser(input, ...context);
}

export async function readUser(input: ReadUserInput, ...context: ContextArgument): Promise<User[]> {
  return connected("readUser").readUser(input, ...context);
}
