// Do not edit this file by hand.
// It is generated by `mesh build` from the entity files; change them and rebuild.
// Mesh's own imports and internal names carry a `$` so that no entity or action name can collide with them.

import {
  loadRows as $loadRows,
  type DataOperations as $DataOperations,
  type LoadOptions as $LoadOptions,
  type LoadPlan as $LoadPlan,
} from "@meshfw/runtime";
import { tables } from "./schema";
import { expressions as postExpressions } from "./blog/post.expressions";
import type { Comment, CommentLoadable, CommentWith } from "./blog/comment.types";
import type { Post, PostLoadable, PostWith } from "./blog/post.types";

/** What `loadRows` follows: each entity's table and key, its relationships and its computed fields. */
export const loadPlan = {
  Comment: {
    table: tables.comment,
    key: "id",
    relations: {
      post: { kind: "belongs-to", target: "Post", column: "postId", nullable: false },
    },
    computed: {},
  },
  Post: {
    table: tables.post,
    key: "id",
    relations: {
      author: { kind: "belongs-to", target: "User", column: "authorId", nullable: false },
      comments: { kind: "has-many", target: "Comment", column: "postId" },
    },
    computed: {
      excerpt: {
        kind: "body",
        needs: [],
        plain: true,
        evaluate: postExpressions["computed.excerpt"],
      },
      commentCount: { kind: "rollup", fn: "count", of: ["comments"] },
    },
  },
  User: {
    table: tables.user,
    key: "id",
    relations: {},
    computed: {},
  },
} as const satisfies $LoadPlan;

/**
 * Load relationships and computed fields onto Comment rows by name. A relationship is loaded by one more
 * query for all the rows; a computed field loads what its body reads first. The rows you pass are not changed:
 * the result is new rows of type CommentWith<"name" | ...>.
 */
export async function loadCommentFields<const N extends keyof CommentLoadable>(
  tx: $DataOperations,
  rows: readonly Comment[],
  names: readonly N[],
  options?: $LoadOptions,
): Promise<CommentWith<N>[]> {
  return (await $loadRows(loadPlan, "Comment", tx, rows, names, options)) as CommentWith<N>[];
}

/**
 * Load relationships and computed fields onto Post rows by name. A relationship is loaded by one more
 * query for all the rows; a computed field loads what its body reads first. The rows you pass are not changed:
 * the result is new rows of type PostWith<"name" | ...>.
 */
export async function loadPostFields<const N extends keyof PostLoadable>(
  tx: $DataOperations,
  rows: readonly Post[],
  names: readonly N[],
  options?: $LoadOptions,
): Promise<PostWith<N>[]> {
  return (await $loadRows(loadPlan, "Post", tx, rows, names, options)) as PostWith<N>[];
}
