// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/work/assignment.mesh.mx; change that file and rebuild.

import type { Comparison as $Comparison } from "@meshfw/runtime";

import type { Task, TaskLoaded } from "./task.types";

import type { Collaborator, CollaboratorLoaded } from "../identity/collaborator.types";

export type Assignment = {
  id: string;
  reviewWaived: boolean;
  startedAt: Date;
  endedAt: Date | null;
  endReason: "reassigned" | "unassigned" | null;
  taskId: string;
  assigneeId: string;
  delegatorId: string;
};

export type StartAssignmentInput = {
  reviewWaived?: boolean | undefined;
  startedAt: Date;
  task: Task["id"];
  assignee: Collaborator["id"];
  delegator: Collaborator["id"];
};

export type ReadAssignmentInput = {
  filter?: AssignmentFilter | undefined;
  sort?: AssignmentSort | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

/** What `load` attaches to a Assignment. The record has none of it, so reading one that was not loaded is a type error. */
export type AssignmentLoadable = {
  task: Task;
  assignee: Collaborator;
  delegator: Collaborator;
};

/** A Assignment with the relationships and computed fields named in N loaded. */
export type AssignmentWith<N extends keyof AssignmentLoadable> = Assignment &
  Pick<AssignmentLoadable, N>;

/** A Assignment as the functions of its entity file see it: every relationship and computed field present, and each related record the same. */
export type AssignmentLoaded = Assignment & {
  task: TaskLoaded;
  assignee: CollaboratorLoaded;
  delegator: CollaboratorLoaded;
};

export type AssignmentFilter =
  | { and: readonly AssignmentFilter[] }
  | { or: readonly AssignmentFilter[] }
  | {
      id?: $Comparison<string>;
      reviewWaived?: $Comparison<boolean>;
      startedAt?: $Comparison<Date>;
      endedAt?: $Comparison<Date>;
      endReason?: $Comparison<"reassigned" | "unassigned">;
      taskId?: $Comparison<string>;
      assigneeId?: $Comparison<string>;
      delegatorId?: $Comparison<string>;
    };

export type AssignmentSort = readonly (
  | "id"
  | "-id"
  | "reviewWaived"
  | "-reviewWaived"
  | "startedAt"
  | "-startedAt"
  | "endedAt"
  | "-endedAt"
  | "endReason"
  | "-endReason"
  | "taskId"
  | "-taskId"
  | "assigneeId"
  | "-assigneeId"
  | "delegatorId"
  | "-delegatorId"
)[];
