// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/work/assignment.mesh.mx; change that file and rebuild.
// Mesh's own imports carry a `$` so that no entity name can shadow them.

import {
  parseInput,
  type ContextArgument as $ContextArgument,
  type DataLayer as $DataLayer,
} from "@meshfw/runtime";
import type { Assignment, StartAssignmentInput, ReadAssignmentInput } from "./assignment.types";
import { startAssignmentInput, readAssignmentInput } from "./assignment.validators";
import { tables } from "../schema";

export function bindAssignment(layer: $DataLayer) {
  return Object.freeze({
    async start(input: StartAssignmentInput, ...[_context]: $ContextArgument): Promise<Assignment> {
      const parsed = await parseInput(startAssignmentInput, input);
      return layer.transaction(async (tx) => {
        const row = await tx.insert(tables.assignment, {
          reviewWaived: parsed.reviewWaived === undefined ? false : parsed.reviewWaived,
          startedAt: parsed.startedAt,
          endedAt: null,
          endReason: null,
          taskId: parsed.task,
          assigneeId: parsed.assignee,
          delegatorId: parsed.delegator,
        });
        return row as Assignment;
      });
    },

    async read(input: ReadAssignmentInput, ...[_context]: $ContextArgument): Promise<Assignment[]> {
      const parsed = await parseInput(readAssignmentInput, input);
      return layer.transaction(async (tx) => {
        return (await tx.select(tables.assignment, {
          filter: parsed.filter,
          sort: parsed.sort,
          limit: parsed.limit,
          offset: parsed.offset,
        })) as Assignment[];
      });
    },
  });
}
