// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/work/assignment.mesh.mx; change that file and rebuild.

import { z } from "zod";

import type {
  StartAssignmentInput,
  ReadAssignmentInput,
  AssignmentFilter,
} from "./assignment.types";

type Keys<T> = T extends Record<string, never> ? never : keyof T;

type SameShape<A, B> = [Keys<A>] extends [Keys<B>]
  ? [Keys<B>] extends [Keys<A>]
    ? [A] extends [B]
      ? [B] extends [A]
        ? true
        : false
      : false
    : false
  : false;

type Assert<T extends true> = T;

const comparison = <T extends z.ZodType>(value: T) =>
  z.strictObject({
    eq: value.nullable().optional(),
    ne: value.nullable().optional(),
    lt: value.optional(),
    lte: value.optional(),
    gt: value.optional(),
    gte: value.optional(),
    in: z.array(value).readonly().optional(),
    nil: z.boolean().optional(),
  });

// The cast is the schema's only gap: zod writes an absent key as `?: T | undefined`, which the
// strictest `exactOptionalPropertyTypes` setting does not let the filter type accept.
export const assignmentFilter: z.ZodType<AssignmentFilter> = z.lazy(
  () =>
    z.union([
      z.strictObject({ and: z.array(assignmentFilter).readonly() }),
      z.strictObject({ or: z.array(assignmentFilter).readonly() }),
      z.strictObject({
        id: comparison(z.uuid()).optional(),
        reviewWaived: comparison(z.boolean()).optional(),
        startedAt: comparison(z.date()).optional(),
        endedAt: comparison(z.date()).optional(),
        endReason: comparison(z.enum(["reassigned", "unassigned"])).optional(),
        taskId: comparison(z.string()).optional(),
        assigneeId: comparison(z.string()).optional(),
        delegatorId: comparison(z.string()).optional(),
      }),
    ]) as unknown as z.ZodType<AssignmentFilter>,
);

export const assignmentSort = z
  .array(
    z.enum([
      "id",
      "-id",
      "reviewWaived",
      "-reviewWaived",
      "startedAt",
      "-startedAt",
      "endedAt",
      "-endedAt",
      "endReason",
      "-endReason",
      "taskId",
      "-taskId",
      "assigneeId",
      "-assigneeId",
      "delegatorId",
      "-delegatorId",
    ]),
  )
  .readonly();

export const startAssignmentInput = z.strictObject({
  reviewWaived: z.boolean().optional(),
  startedAt: z.date(),
  task: z.uuid(),
  assignee: z.uuid(),
  delegator: z.uuid(),
}) satisfies z.ZodType<StartAssignmentInput>;

export type StartAssignmentInputShape = Assert<
  SameShape<z.output<typeof startAssignmentInput>, StartAssignmentInput>
>;

export const readAssignmentInput = z.strictObject({
  filter: assignmentFilter.optional(),
  sort: assignmentSort.optional(),
  limit: z.int().min(0).optional(),
  offset: z.int().min(0).optional(),
}) satisfies z.ZodType<ReadAssignmentInput>;

export type ReadAssignmentInputShape = Assert<
  SameShape<z.output<typeof readAssignmentInput>, ReadAssignmentInput>
>;
