// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/work/assignment.mesh.mx; change that file and rebuild.
// Mesh's own imports carry a `$` so that no entity name can shadow them.

import {
  castInput as $castInput,
  noteWrite as $noteWrite,
  type BindOptions as $BindOptions,
  type Composer as $Composer,
  type ContextArgument as $ContextArgument,
  type DataLayer as $DataLayer,
  type Row as $Row,
} from "@meshfw/runtime";
import type { Assignment, StartAssignmentInput, ReadAssignmentInput } from "./assignment.types";
import { startAssignmentInput, readAssignmentInput } from "./assignment.validators";
import { tables } from "../schema";

/**
 * The reads of this entity without the authorizer slot: what `tx` holds in a function of an entity file (ADR-0068).
 * The read actions below run the slot, then these.
 */
export function bindAssignmentReads(layer: $DataLayer) {
  return Object.freeze({
    async read(input: ReadAssignmentInput): Promise<Assignment[]> {
      // enter, cast: only the declared input passes; a failed cast inside a transaction fails it
      const parsed = await $castInput(layer, readAssignmentInput, input);
      return layer.transaction(async (tx) => {
        return (await tx.select(tables.assignment, {
          filter: parsed.filter,
          sort: parsed.sort,
          limit: parsed.limit,
          offset: parsed.offset,
        })) as Assignment[];
      });
    },
  });
}

/**
 * Every action of this entity, bound to `layer`. `compose` is the binding's composer, which hands a function its
 * `actions` and `tx`; the project's `bind` in the index passes it.
 */
export function bindAssignment(
  layer: $DataLayer,
  _options: $BindOptions = {},
  _compose?: $Composer,
) {
  const $reads = bindAssignmentReads(layer);
  return Object.freeze({
    async start(input: StartAssignmentInput, ...[_context]: $ContextArgument): Promise<Assignment> {
      // enter, cast: the call arrives with its context, and only the declared input passes; a failed cast inside a transaction fails it
      const parsed = await $castInput(layer, startAssignmentInput, input);
      return layer.transaction(async (tx) => {
        // transaction: opens here; what follows commits together or not at all (pre-check: the authorizer slot before it stays empty until policies, M8)
        // plan: a create is one insert; nothing is read first
        const $changes: $Row = {
          reviewWaived: parsed.reviewWaived === undefined ? false : parsed.reviewWaived,
          startedAt: parsed.startedAt,
          endedAt: null,
          endReason: null,
          taskId: parsed.task,
          assigneeId: parsed.assignee,
          delegatorId: parsed.delegator,
        };
        // data layer
        const $stored = await tx.insert(tables.assignment, $changes);
        $noteWrite(tx);
        return $stored as Assignment;
      });
    },

    async read(input: ReadAssignmentInput, ...[_context]: $ContextArgument): Promise<Assignment[]> {
      // pre-check: the read authorizer slot stays empty until policies (M8); a read through `tx` skips it
      return $reads.read(input);
    },
  });
}
