// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/work/claim.mesh.mx; change that file and rebuild.

import type { Comparison as $Comparison } from "@meshfw/runtime";

import type { Task } from "./task.types";

import type { Collaborator } from "../identity/collaborator.types";

export type Claim = {
  id: string;
  fence: number;
  acquiredAt: Date;
  expiresAt: Date;
  endedAt: Date | null;
  endReason: string | null;
  state: "active" | "released" | "revoked" | "expired";
  taskId: string;
  holderId: string;
};

export type AcquireClaimInput = {
  fence: number;
  acquiredAt: Date;
  expiresAt: Date;
  task: Task["id"];
  holder: Collaborator["id"];
};

export type ReadClaimInput = {
  filter?: ClaimFilter | undefined;
  sort?: ClaimSort | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

export type ClaimFilter =
  | { and: readonly ClaimFilter[] }
  | { or: readonly ClaimFilter[] }
  | {
      id?: $Comparison<string>;
      fence?: $Comparison<number>;
      acquiredAt?: $Comparison<Date>;
      expiresAt?: $Comparison<Date>;
      endedAt?: $Comparison<Date>;
      endReason?: $Comparison<string>;
      state?: $Comparison<"active" | "released" | "revoked" | "expired">;
      taskId?: $Comparison<string>;
      holderId?: $Comparison<string>;
    };

export type ClaimSort = readonly (
  | "id"
  | "-id"
  | "fence"
  | "-fence"
  | "acquiredAt"
  | "-acquiredAt"
  | "expiresAt"
  | "-expiresAt"
  | "endedAt"
  | "-endedAt"
  | "endReason"
  | "-endReason"
  | "state"
  | "-state"
  | "taskId"
  | "-taskId"
  | "holderId"
  | "-holderId"
)[];
