// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/work/claim.mesh.mx; change that file and rebuild.

import { z } from "zod";

import type { AcquireClaimInput, ReadClaimInput, ClaimFilter } from "./claim.types";

type Keys<T> = T extends Record<string, never> ? never : keyof T;

type SameShape<A, B> = [Keys<A>] extends [Keys<B>]
  ? [Keys<B>] extends [Keys<A>]
    ? [A] extends [B]
      ? [B] extends [A]
        ? true
        : false
      : false
    : false
  : false;

type Assert<T extends true> = T;

const comparison = <T extends z.ZodType>(value: T) =>
  z
    .strictObject({
      eq: value.nullable().exactOptional(),
      ne: value.nullable().exactOptional(),
      lt: value.exactOptional(),
      lte: value.exactOptional(),
      gt: value.exactOptional(),
      gte: value.exactOptional(),
      in: z.array(value).readonly().exactOptional(),
      nil: z.boolean().exactOptional(),
    })
    .refine((operators) => Object.keys(operators).length > 0, {
      message: "a comparison needs an operator",
    });

export const claimFilter: z.ZodType<ClaimFilter> = z.lazy(
  () =>
    z.union([
      z.strictObject({ and: z.array(claimFilter).readonly() }),
      z.strictObject({ or: z.array(claimFilter).readonly() }),
      z.strictObject({
        id: comparison(z.uuid()).exactOptional(),
        fence: comparison(z.int()).exactOptional(),
        acquiredAt: comparison(z.date()).exactOptional(),
        expiresAt: comparison(z.date()).exactOptional(),
        endedAt: comparison(z.date()).exactOptional(),
        endReason: comparison(z.string()).exactOptional(),
        state: comparison(z.enum(["active", "released", "revoked", "expired"])).exactOptional(),
        taskId: comparison(z.string()).exactOptional(),
        holderId: comparison(z.string()).exactOptional(),
      }),
    ]) as unknown as z.ZodType<ClaimFilter>,
);

export const claimSort = z
  .array(
    z.enum([
      "id",
      "-id",
      "fence",
      "-fence",
      "acquiredAt",
      "-acquiredAt",
      "expiresAt",
      "-expiresAt",
      "endedAt",
      "-endedAt",
      "endReason",
      "-endReason",
      "state",
      "-state",
      "taskId",
      "-taskId",
      "holderId",
      "-holderId",
    ]),
  )
  .readonly();

export const acquireClaimInput = z.strictObject({
  fence: z.int(),
  acquiredAt: z.date(),
  expiresAt: z.date(),
  task: z.uuid(),
  holder: z.uuid(),
}) satisfies z.ZodType<AcquireClaimInput>;

export type AcquireClaimInputShape = Assert<
  SameShape<z.output<typeof acquireClaimInput>, AcquireClaimInput>
>;

export const readClaimInput = z.strictObject({
  filter: claimFilter.optional(),
  sort: claimSort.optional(),
  limit: z.int().min(0).optional(),
  offset: z.int().min(0).optional(),
}) satisfies z.ZodType<ReadClaimInput>;

export type ReadClaimInputShape = Assert<
  SameShape<z.output<typeof readClaimInput>, ReadClaimInput>
>;
