// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/work/claim.mesh.mx; change that file and rebuild.

import { expr as $, type Scope as $Scope } from "@meshfw/runtime";
import type { Claim } from "./claim.types";

/** What every expression of Claim reads. */
export type ClaimScope = $Scope<{
  self: Claim & Record<string, any>;
  input: any;
  actor: any;
  context: any;
  before: Claim | null;
  tx: any;
}>;

export const expressions = {
  // computed lapsed, translated (src/domain/work/claim.mesh.mx:17:20)
  "computed.lapsed": (s: ClaimScope) =>
    $.and($.eq(s.self.state, "active"), $.lte(s.self.expiresAt, $.now(s))),
} as const;
