// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/work/completion.mesh.mx; change that file and rebuild.
// Mesh's own imports carry a `$` so that no entity name can shadow them.

import {
  parseInput,
  type ContextArgument as $ContextArgument,
  type DataLayer as $DataLayer,
} from "@meshfw/runtime";
import type { Completion, RecordCompletionInput, ReadCompletionInput } from "./completion.types";
import { recordCompletionInput, readCompletionInput } from "./completion.validators";
import { tables } from "../schema";

export function bindCompletion(layer: $DataLayer) {
  return Object.freeze({
    async record(
      input: RecordCompletionInput,
      ...[_context]: $ContextArgument
    ): Promise<Completion> {
      const parsed = await parseInput(recordCompletionInput, input);
      return layer.transaction(async (tx) => {
        const now = new Date();
        const row = await tx.insert(tables.completion, {
          rule: parsed.rule,
          completedAt: now,
          taskId: parsed.task,
          submissionId: parsed.submission === undefined ? null : parsed.submission,
          completedById: parsed.completedBy,
        });
        return row as Completion;
      });
    },

    async read(input: ReadCompletionInput, ...[_context]: $ContextArgument): Promise<Completion[]> {
      const parsed = await parseInput(readCompletionInput, input);
      return layer.transaction(async (tx) => {
        return (await tx.select(tables.completion, {
          filter: parsed.filter,
          sort: parsed.sort,
          limit: parsed.limit,
          offset: parsed.offset,
        })) as Completion[];
      });
    },
  });
}
