// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/work/completion.mesh.mx; change that file and rebuild.
// Mesh's own imports carry a `$` so that no entity name can shadow them.

import {
  parseInput,
  type BindOptions as $BindOptions,
  type Composer as $Composer,
  type ContextArgument as $ContextArgument,
  type DataLayer as $DataLayer,
  type Row as $Row,
} from "@meshfw/runtime";
import type { Completion, RecordCompletionInput, ReadCompletionInput } from "./completion.types";
import { recordCompletionInput, readCompletionInput } from "./completion.validators";
import { tables } from "../schema";

/**
 * The reads of this entity without the authorizer slot: what `tx` holds in a function of an entity file (ADR-0068).
 * The read actions below run the slot, then these.
 */
export function bindCompletionReads(layer: $DataLayer) {
  return Object.freeze({
    async read(input: ReadCompletionInput): Promise<Completion[]> {
      // enter, cast: only the declared input passes
      const parsed = await parseInput(readCompletionInput, input);
      return layer.transaction(async (tx) => {
        return (await tx.select(tables.completion, {
          filter: parsed.filter,
          sort: parsed.sort,
          limit: parsed.limit,
          offset: parsed.offset,
        })) as Completion[];
      });
    },
  });
}

/**
 * Every action of this entity, bound to `layer`. `compose` is the binding's composer, which hands a function its
 * `actions` and `tx`; the project's `bind` in the index passes it.
 */
export function bindCompletion(
  layer: $DataLayer,
  options: $BindOptions = {},
  _compose?: $Composer,
) {
  const $reads = bindCompletionReads(layer);
  return Object.freeze({
    async record(
      input: RecordCompletionInput,
      ...[_context]: $ContextArgument
    ): Promise<Completion> {
      // enter, cast: the call arrives with its context, and only the declared input passes
      const parsed = await parseInput(recordCompletionInput, input);
      return layer.transaction(async (tx) => {
        // transaction: opens here; what follows commits together or not at all (pre-check: the authorizer slot before it stays empty until policies, M8)
        const $now = options.clock?.() ?? new Date();
        // plan: a create is one insert; nothing is read first
        const $changes: $Row = {
          rule: parsed.rule,
          completedAt: $now,
          taskId: parsed.task,
          submissionId: parsed.submission === undefined ? null : parsed.submission,
          completedById: parsed.completedBy,
        };
        // data layer
        const $stored = await tx.insert(tables.completion, $changes);
        return $stored as Completion;
      });
    },

    async read(input: ReadCompletionInput, ...[_context]: $ContextArgument): Promise<Completion[]> {
      // pre-check: the read authorizer slot stays empty until policies (M8); a read through `tx` skips it
      return $reads.read(input);
    },
  });
}
