// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/work/completion.mesh.mx; change that file and rebuild.

import { z } from "zod";

import type {
  RecordCompletionInput,
  ReadCompletionInput,
  CompletionFilter,
} from "./completion.types";

type Keys<T> = T extends Record<string, never> ? never : keyof T;

type SameShape<A, B> = [Keys<A>] extends [Keys<B>]
  ? [Keys<B>] extends [Keys<A>]
    ? [A] extends [B]
      ? [B] extends [A]
        ? true
        : false
      : false
    : false
  : false;

type Assert<T extends true> = T;

const comparison = <T extends z.ZodType>(value: T) =>
  z
    .strictObject({
      eq: value.nullable().exactOptional(),
      ne: value.nullable().exactOptional(),
      lt: value.exactOptional(),
      lte: value.exactOptional(),
      gt: value.exactOptional(),
      gte: value.exactOptional(),
      in: z.array(value).readonly().exactOptional(),
      nil: z.boolean().exactOptional(),
    })
    .refine((operators) => Object.keys(operators).length > 0, {
      message: "a comparison needs an operator",
    });

export const completionFilter: z.ZodType<CompletionFilter> = z.lazy(
  () =>
    z.union([
      z.strictObject({ and: z.array(completionFilter).readonly() }),
      z.strictObject({ or: z.array(completionFilter).readonly() }),
      z.strictObject({
        id: comparison(z.uuid()).exactOptional(),
        rule: comparison(
          z.enum(["review-accepted", "performer-is-reviewer", "review-waived"]),
        ).exactOptional(),
        completedAt: comparison(z.date()).exactOptional(),
        taskId: comparison(z.string()).exactOptional(),
        submissionId: comparison(z.string()).exactOptional(),
        completedById: comparison(z.string()).exactOptional(),
      }),
    ]) as unknown as z.ZodType<CompletionFilter>,
);

export const completionSort = z
  .array(
    z.enum([
      "id",
      "-id",
      "rule",
      "-rule",
      "completedAt",
      "-completedAt",
      "taskId",
      "-taskId",
      "submissionId",
      "-submissionId",
      "completedById",
      "-completedById",
    ]),
  )
  .readonly();

export const recordCompletionInput = z.strictObject({
  rule: z.enum(["review-accepted", "performer-is-reviewer", "review-waived"]),
  task: z.uuid(),
  submission: z.uuid().nullable().optional(),
  completedBy: z.uuid(),
}) satisfies z.ZodType<RecordCompletionInput>;

export type RecordCompletionInputShape = Assert<
  SameShape<z.output<typeof recordCompletionInput>, RecordCompletionInput>
>;

export const readCompletionInput = z.strictObject({
  filter: completionFilter.optional(),
  sort: completionSort.optional(),
  limit: z.int().min(0).optional(),
  offset: z.int().min(0).optional(),
}) satisfies z.ZodType<ReadCompletionInput>;

export type ReadCompletionInputShape = Assert<
  SameShape<z.output<typeof readCompletionInput>, ReadCompletionInput>
>;
