// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/work/completion.mesh.mx; change that file and rebuild.

import type { Comparison as $Comparison } from "@meshfw/runtime";

import type { Task, TaskLoaded } from "./task.types";

import type { Submission, SubmissionLoaded } from "./submission.types";

import type { Collaborator, CollaboratorLoaded } from "../identity/collaborator.types";

export type Completion = {
  id: string;
  rule: "review-accepted" | "performer-is-reviewer" | "review-waived";
  completedAt: Date;
  taskId: string;
  submissionId: string | null;
  completedById: string;
};

export type RecordCompletionInput = {
  rule: "review-accepted" | "performer-is-reviewer" | "review-waived";
  task: Task["id"];
  submission?: Submission["id"] | null | undefined;
  completedBy: Collaborator["id"];
};

export type ReadCompletionInput = {
  filter?: CompletionFilter | undefined;
  sort?: CompletionSort | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

/** What `load` attaches to a Completion. The record has none of it, so reading one that was not loaded is a type error. */
export type CompletionLoadable = {
  task: Task;
  submission: Submission | null;
  completedBy: Collaborator;
};

/** A Completion with the relationships and computed fields named in N loaded. */
export type CompletionWith<N extends keyof CompletionLoadable> = Completion &
  Pick<CompletionLoadable, N>;

/** A Completion as the functions of its entity file see it: every relationship and computed field present, and each related record the same. */
export type CompletionLoaded = Completion & {
  task: TaskLoaded;
  submission: SubmissionLoaded | null;
  completedBy: CollaboratorLoaded;
};

export type CompletionFilter =
  | { and: readonly CompletionFilter[] }
  | { or: readonly CompletionFilter[] }
  | {
      id?: $Comparison<string>;
      rule?: $Comparison<"review-accepted" | "performer-is-reviewer" | "review-waived">;
      completedAt?: $Comparison<Date>;
      taskId?: $Comparison<string>;
      submissionId?: $Comparison<string>;
      completedById?: $Comparison<string>;
    };

export type CompletionSort = readonly (
  | "id"
  | "-id"
  | "rule"
  | "-rule"
  | "completedAt"
  | "-completedAt"
  | "taskId"
  | "-taskId"
  | "submissionId"
  | "-submissionId"
  | "completedById"
  | "-completedById"
)[];
