// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/work/dependency.mesh.mx; change that file and rebuild.

import type { Comparison as $Comparison } from "@meshfw/runtime";

import type { Task, TaskLoaded } from "./task.types";

import type { Collaborator, CollaboratorLoaded } from "../identity/collaborator.types";

export type Dependency = {
  id: string;
  createdAt: Date;
  dependentId: string;
  prerequisiteId: string;
  createdById: string;
};

export type AddDependencyInput = {
  dependent: Task["id"];
  prerequisite: Task["id"];
  createdBy: Collaborator["id"];
};

export type RemoveDependencyInput = {
  id: string;
};

export type ReadDependencyInput = {
  filter?: DependencyFilter | undefined;
  sort?: DependencySort | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

/** What `load` attaches to a Dependency. The record has none of it, so reading one that was not loaded is a type error. */
export type DependencyLoadable = {
  dependent: Task;
  prerequisite: Task;
  createdBy: Collaborator;
};

/** A Dependency with the relationships and computed fields named in N loaded. */
export type DependencyWith<N extends keyof DependencyLoadable> = Dependency &
  Pick<DependencyLoadable, N>;

/** A Dependency as the functions of its entity file see it: every relationship and computed field present, and each related record the same. */
export type DependencyLoaded = Dependency & {
  dependent: TaskLoaded;
  prerequisite: TaskLoaded;
  createdBy: CollaboratorLoaded;
};

export type DependencyFilter =
  | { and: readonly DependencyFilter[] }
  | { or: readonly DependencyFilter[] }
  | {
      id?: $Comparison<string>;
      createdAt?: $Comparison<Date>;
      dependentId?: $Comparison<string>;
      prerequisiteId?: $Comparison<string>;
      createdById?: $Comparison<string>;
    };

export type DependencySort = readonly (
  | "id"
  | "-id"
  | "createdAt"
  | "-createdAt"
  | "dependentId"
  | "-dependentId"
  | "prerequisiteId"
  | "-prerequisiteId"
  | "createdById"
  | "-createdById"
)[];
