// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/work/dependency.mesh.mx; change that file and rebuild.
// Mesh's own imports carry a `$` so that no entity name can shadow them.

import {
  InvalidInputError as $InvalidInputError,
  NotFoundError as $NotFoundError,
  composed as $composed,
  guarded as $guarded,
  loadInto as $loadInto,
  parseInput,
  readOnlyRecord as $readOnlyRecord,
  runCheck as $runCheck,
  scope as $scope,
  type BindOptions as $BindOptions,
  type Composer as $Composer,
  type ContextArgument as $ContextArgument,
  type DataLayer as $DataLayer,
  type Issue as $Issue,
  type Row as $Row,
} from "@meshfw/runtime";
import type {
  Dependency,
  AddDependencyInput,
  RemoveDependencyInput,
  ReadDependencyInput,
} from "./dependency.types";
import {
  addDependencyInput,
  removeDependencyInput,
  readDependencyInput,
} from "./dependency.validators";
import { tables } from "../schema";
import {
  expressions as $expressions,
  type DependencyScope as $Scope,
} from "./dependency.expressions";
import { loadPlan as $loadPlan } from "../load";

/**
 * The reads of this entity without the authorizer slot: what `tx` holds in a function of an entity file (ADR-0068).
 * The read actions below run the slot, then these.
 */
export function bindDependencyReads(layer: $DataLayer) {
  return Object.freeze({
    async read(input: ReadDependencyInput): Promise<Dependency[]> {
      // enter, cast: only the declared input passes
      const parsed = await parseInput(readDependencyInput, input);
      return layer.transaction(async (tx) => {
        return (await tx.select(tables.dependency, {
          filter: parsed.filter,
          sort: parsed.sort,
          limit: parsed.limit,
          offset: parsed.offset,
        })) as Dependency[];
      });
    },
  });
}

/**
 * Every action of this entity, bound to `layer`. `compose` is the binding's composer, which hands a function its
 * `actions` and `tx`; the project's `bind` in the index passes it.
 */
export function bindDependency(layer: $DataLayer, options: $BindOptions = {}, compose?: $Composer) {
  const $reads = bindDependencyReads(layer);
  return Object.freeze({
    async add(input: AddDependencyInput, ...[context]: $ContextArgument): Promise<Dependency> {
      // enter, cast: the call arrives with its context, and only the declared input passes
      const parsed = await parseInput(addDependencyInput, input);
      return layer.transaction(async (tx) => {
        // transaction: opens here; what follows commits together or not at all (pre-check: the authorizer slot before it stays empty until policies, M8)
        const $context = (context ?? {}) as unknown as Record<string, unknown>;
        const $actor = $context.actor;
        const $now = options.clock?.() ?? new Date();
        // plan: a create is one insert; nothing is read first
        const $changes: $Row = {
          createdAt: $now,
          dependentId: parsed.dependent,
          prerequisiteId: parsed.prerequisite,
          createdById: parsed.createdBy,
        };
        const $record: $Row = { ...$changes };
        const $load = { actor: $actor, context: $context, clock: options.clock };
        const $self = $readOnlyRecord(
          $guarded($loadPlan, "Dependency", $record, "action function"),
          "Dependency.add",
        );
        const $s = $scope(
          {
            self: $self,
            input: $readOnlyRecord(parsed, "Dependency.add"),
            actor: $actor,
            context: $context,
            before: null,
            ...$composed(compose, tx, context, "Dependency.add"),
          },
          options,
        ) as unknown as $Scope<AddDependencyInput>;
        // validate: every check runs, and every failed check is reported together
        const $issues: $Issue[] = [];
        await $loadInto($loadPlan, "Dependency", tx, $record, ["dependent", "prerequisite"], $load);
        await $runCheck($issues, $s, {
          label: "distinct",
          code: "dependency.distinct",
          message: "a task cannot depend on itself",
          source: { file: "src/domain/work/dependency.mesh.mx", line: 19, column: 9 },
          that: $expressions["add.check.distinct.that"],
        });
        if ($issues.length > 0) throw new $InvalidInputError($issues);
        // data layer
        const $stored = await tx.insert(tables.dependency, $changes);
        return $stored as Dependency;
      });
    },

    async remove(input: RemoveDependencyInput, ...[_context]: $ContextArgument): Promise<void> {
      // enter, cast: the call arrives with its context, and only the declared input passes
      const parsed = await parseInput(removeDependencyInput, input);
      return layer.transaction(async (tx) => {
        // transaction: opens here; what follows commits together or not at all (pre-check: the authorizer slot before it stays empty until policies, M8)
        // plan: nothing in the body can see the record, so the row is deleted without being read
        const $key = { id: parsed.id };
        // data layer
        if (!(await tx.deleteByKey(tables.dependency, $key)))
          throw new $NotFoundError("Dependency", $key);
      });
    },

    async read(input: ReadDependencyInput, ...[_context]: $ContextArgument): Promise<Dependency[]> {
      // pre-check: the read authorizer slot stays empty until policies (M8); a read through `tx` skips it
      return $reads.read(input);
    },
  });
}
