// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/work/dependency.mesh.mx; change that file and rebuild.

import { z } from "zod";

import type {
  AddDependencyInput,
  RemoveDependencyInput,
  ReadDependencyInput,
  DependencyFilter,
} from "./dependency.types";

type Keys<T> = T extends Record<string, never> ? never : keyof T;

type SameShape<A, B> = [Keys<A>] extends [Keys<B>]
  ? [Keys<B>] extends [Keys<A>]
    ? [A] extends [B]
      ? [B] extends [A]
        ? true
        : false
      : false
    : false
  : false;

type Assert<T extends true> = T;

const comparison = <T extends z.ZodType>(value: T) =>
  z.strictObject({
    eq: value.nullable().optional(),
    ne: value.nullable().optional(),
    lt: value.optional(),
    lte: value.optional(),
    gt: value.optional(),
    gte: value.optional(),
    in: z.array(value).readonly().optional(),
    nil: z.boolean().optional(),
  });

// The cast is the schema's only gap: zod writes an absent key as `?: T | undefined`, which the
// strictest `exactOptionalPropertyTypes` setting does not let the filter type accept.
export const dependencyFilter: z.ZodType<DependencyFilter> = z.lazy(
  () =>
    z.union([
      z.strictObject({ and: z.array(dependencyFilter).readonly() }),
      z.strictObject({ or: z.array(dependencyFilter).readonly() }),
      z.strictObject({
        id: comparison(z.uuid()).optional(),
        createdAt: comparison(z.date()).optional(),
        dependentId: comparison(z.string()).optional(),
        prerequisiteId: comparison(z.string()).optional(),
        createdById: comparison(z.string()).optional(),
      }),
    ]) as unknown as z.ZodType<DependencyFilter>,
);

export const dependencySort = z
  .array(
    z.enum([
      "id",
      "-id",
      "createdAt",
      "-createdAt",
      "dependentId",
      "-dependentId",
      "prerequisiteId",
      "-prerequisiteId",
      "createdById",
      "-createdById",
    ]),
  )
  .readonly();

export const addDependencyInput = z.strictObject({
  dependent: z.uuid(),
  prerequisite: z.uuid(),
  createdBy: z.uuid(),
}) satisfies z.ZodType<AddDependencyInput>;

export type AddDependencyInputShape = Assert<
  SameShape<z.output<typeof addDependencyInput>, AddDependencyInput>
>;

export const removeDependencyInput = z.strictObject({
  id: z.uuid(),
}) satisfies z.ZodType<RemoveDependencyInput>;

export type RemoveDependencyInputShape = Assert<
  SameShape<z.output<typeof removeDependencyInput>, RemoveDependencyInput>
>;

export const readDependencyInput = z.strictObject({
  filter: dependencyFilter.optional(),
  sort: dependencySort.optional(),
  limit: z.int().min(0).optional(),
  offset: z.int().min(0).optional(),
}) satisfies z.ZodType<ReadDependencyInput>;

export type ReadDependencyInputShape = Assert<
  SameShape<z.output<typeof readDependencyInput>, ReadDependencyInput>
>;
