// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/work/evidence-reference.mesh.mx; change that file and rebuild.
// Mesh's own imports carry a `$` so that no entity name can shadow them.

import {
  parseInput,
  type ContextArgument as $ContextArgument,
  type DataLayer as $DataLayer,
} from "@meshfw/runtime";
import type {
  EvidenceReference,
  RecordEvidenceReferenceInput,
  ReadEvidenceReferenceInput,
} from "./evidenceReference.types";
import {
  recordEvidenceReferenceInput,
  readEvidenceReferenceInput,
} from "./evidenceReference.validators";
import { tables } from "../schema";

export function bindEvidenceReference(layer: $DataLayer) {
  return Object.freeze({
    async record(
      input: RecordEvidenceReferenceInput,
      ...[_context]: $ContextArgument
    ): Promise<EvidenceReference> {
      const parsed = await parseInput(recordEvidenceReferenceInput, input);
      return layer.transaction(async (tx) => {
        const now = new Date();
        const row = await tx.insert(tables.evidenceReference, {
          kind: parsed.kind,
          locator: parsed.locator,
          contentHash: parsed.contentHash === undefined ? null : parsed.contentHash,
          description: parsed.description === undefined ? null : parsed.description,
          recordedAt: now,
          recordedById: parsed.recordedBy,
        });
        return row as EvidenceReference;
      });
    },

    async read(
      input: ReadEvidenceReferenceInput,
      ...[_context]: $ContextArgument
    ): Promise<EvidenceReference[]> {
      const parsed = await parseInput(readEvidenceReferenceInput, input);
      return layer.transaction(async (tx) => {
        return (await tx.select(tables.evidenceReference, {
          filter: parsed.filter,
          sort: parsed.sort,
          limit: parsed.limit,
          offset: parsed.offset,
        })) as EvidenceReference[];
      });
    },
  });
}
