// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/work/evidence-reference.mesh.mx; change that file and rebuild.

import { z } from "zod";

import type {
  RecordEvidenceReferenceInput,
  ReadEvidenceReferenceInput,
  EvidenceReferenceFilter,
} from "./evidenceReference.types";

type Keys<T> = T extends Record<string, never> ? never : keyof T;

type SameShape<A, B> = [Keys<A>] extends [Keys<B>]
  ? [Keys<B>] extends [Keys<A>]
    ? [A] extends [B]
      ? [B] extends [A]
        ? true
        : false
      : false
    : false
  : false;

type Assert<T extends true> = T;

const comparison = <T extends z.ZodType>(value: T) =>
  z
    .strictObject({
      eq: value.nullable().exactOptional(),
      ne: value.nullable().exactOptional(),
      lt: value.exactOptional(),
      lte: value.exactOptional(),
      gt: value.exactOptional(),
      gte: value.exactOptional(),
      in: z.array(value).readonly().exactOptional(),
      nil: z.boolean().exactOptional(),
    })
    .refine((operators) => Object.keys(operators).length > 0, {
      message: "a comparison needs an operator",
    });

export const evidenceReferenceFilter: z.ZodType<EvidenceReferenceFilter> = z.lazy(
  () =>
    z.union([
      z.strictObject({ and: z.array(evidenceReferenceFilter).readonly() }),
      z.strictObject({ or: z.array(evidenceReferenceFilter).readonly() }),
      z.strictObject({
        id: comparison(z.uuid()).exactOptional(),
        kind: comparison(z.string()).exactOptional(),
        locator: comparison(z.string()).exactOptional(),
        contentHash: comparison(z.string()).exactOptional(),
        description: comparison(z.string()).exactOptional(),
        recordedAt: comparison(z.date()).exactOptional(),
        recordedById: comparison(z.uuid()).exactOptional(),
      }),
    ]) as unknown as z.ZodType<EvidenceReferenceFilter>,
);

export const evidenceReferenceSort = z
  .array(
    z.enum([
      "id",
      "-id",
      "kind",
      "-kind",
      "locator",
      "-locator",
      "contentHash",
      "-contentHash",
      "description",
      "-description",
      "recordedAt",
      "-recordedAt",
      "recordedById",
      "-recordedById",
    ]),
  )
  .readonly();

export const recordEvidenceReferenceInput = z.strictObject({
  kind: z.string(),
  locator: z.string(),
  contentHash: z.string().nullable().optional(),
  description: z.string().nullable().optional(),
  recordedBy: z.uuid(),
}) satisfies z.ZodType<RecordEvidenceReferenceInput>;

export type RecordEvidenceReferenceInputShape = Assert<
  SameShape<z.output<typeof recordEvidenceReferenceInput>, RecordEvidenceReferenceInput>
>;

export const readEvidenceReferenceInput = z.strictObject({
  filter: evidenceReferenceFilter.optional(),
  sort: evidenceReferenceSort.optional(),
  limit: z.int().min(0).optional(),
  offset: z.int().min(0).optional(),
}) satisfies z.ZodType<ReadEvidenceReferenceInput>;

export type ReadEvidenceReferenceInputShape = Assert<
  SameShape<z.output<typeof readEvidenceReferenceInput>, ReadEvidenceReferenceInput>
>;
