// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/work/evidence-reference.mesh.mx; change that file and rebuild.
// Mesh's own imports carry a `$` so that no entity name can shadow them.

import {
  castInput as $castInput,
  noteWrite as $noteWrite,
  type BindOptions as $BindOptions,
  type Composer as $Composer,
  type ContextArgument as $ContextArgument,
  type DataLayer as $DataLayer,
  type Row as $Row,
} from "@meshfw/runtime";
import type {
  EvidenceReference,
  RecordEvidenceReferenceInput,
  ReadEvidenceReferenceInput,
} from "./evidenceReference.types";
import {
  recordEvidenceReferenceInput,
  readEvidenceReferenceInput,
} from "./evidenceReference.validators";
import { tables } from "../schema";

/**
 * The reads of this entity without the authorizer slot: what `tx` holds in a function of an entity file (ADR-0068).
 * The read actions below run the slot, then these.
 */
export function bindEvidenceReferenceReads(layer: $DataLayer) {
  return Object.freeze({
    async read(input: ReadEvidenceReferenceInput): Promise<EvidenceReference[]> {
      // enter, cast: only the declared input passes; a failed cast inside a transaction fails it
      const parsed = await $castInput(layer, readEvidenceReferenceInput, input);
      return layer.transaction(async (tx) => {
        return (await tx.select(tables.evidenceReference, {
          filter: parsed.filter,
          sort: parsed.sort,
          limit: parsed.limit,
          offset: parsed.offset,
        })) as EvidenceReference[];
      });
    },
  });
}

/**
 * Every action of this entity, bound to `layer`. `compose` is the binding's composer, which hands a function its
 * `actions` and `tx`; the project's `bind` in the index passes it.
 */
export function bindEvidenceReference(
  layer: $DataLayer,
  options: $BindOptions = {},
  _compose?: $Composer,
) {
  const $reads = bindEvidenceReferenceReads(layer);
  return Object.freeze({
    async record(
      input: RecordEvidenceReferenceInput,
      ...[_context]: $ContextArgument
    ): Promise<EvidenceReference> {
      // enter, cast: the call arrives with its context, and only the declared input passes; a failed cast inside a transaction fails it
      const parsed = await $castInput(layer, recordEvidenceReferenceInput, input);
      return layer.transaction(async (tx) => {
        // transaction: opens here; what follows commits together or not at all (pre-check: the authorizer slot before it stays empty until policies, M8)
        const $now = options.clock?.() ?? new Date();
        // plan: a create is one insert; nothing is read first
        const $changes: $Row = {
          kind: parsed.kind,
          locator: parsed.locator,
          contentHash: parsed.contentHash === undefined ? null : parsed.contentHash,
          description: parsed.description === undefined ? null : parsed.description,
          recordedAt: $now,
          recordedById: parsed.recordedBy,
        };
        // data layer
        const $stored = await tx.insert(tables.evidenceReference, $changes);
        $noteWrite(tx);
        return $stored as EvidenceReference;
      });
    },

    async read(
      input: ReadEvidenceReferenceInput,
      ...[_context]: $ContextArgument
    ): Promise<EvidenceReference[]> {
      // pre-check: the read authorizer slot stays empty until policies (M8); a read through `tx` skips it
      return $reads.read(input);
    },
  });
}
