// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/work/evidence-reference.mesh.mx; change that file and rebuild.

import type { Comparison as $Comparison } from "@meshfw/runtime";

import type { Collaborator } from "../identity/collaborator.types";

export type EvidenceReference = {
  id: string;
  kind: string;
  locator: string;
  contentHash: string | null;
  description: string | null;
  recordedAt: Date;
  recordedById: string;
};

export type RecordEvidenceReferenceInput = {
  kind: string;
  locator: string;
  contentHash?: string | null | undefined;
  description?: string | null | undefined;
  recordedBy: Collaborator["id"];
};

export type ReadEvidenceReferenceInput = {
  filter?: EvidenceReferenceFilter | undefined;
  sort?: EvidenceReferenceSort | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

export type EvidenceReferenceFilter =
  | { and: readonly EvidenceReferenceFilter[] }
  | { or: readonly EvidenceReferenceFilter[] }
  | {
      id?: $Comparison<string>;
      kind?: $Comparison<string>;
      locator?: $Comparison<string>;
      contentHash?: $Comparison<string>;
      description?: $Comparison<string>;
      recordedAt?: $Comparison<Date>;
      recordedById?: $Comparison<string>;
    };

export type EvidenceReferenceSort = readonly (
  | "id"
  | "-id"
  | "kind"
  | "-kind"
  | "locator"
  | "-locator"
  | "contentHash"
  | "-contentHash"
  | "description"
  | "-description"
  | "recordedAt"
  | "-recordedAt"
  | "recordedById"
  | "-recordedById"
)[];
