// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/work/late-result.mesh.mx; change that file and rebuild.

import type { Comparison as $Comparison } from "@meshfw/runtime";

import type { Task, TaskLoaded } from "./task.types";

import type { Collaborator, CollaboratorLoaded } from "../identity/collaborator.types";

export type LateResult = {
  id: string;
  fence: number;
  summary: string | null;
  evidence: unknown;
  recordedAt: Date;
  taskId: string;
  submitterId: string;
};

export type RecordLateResultInput = {
  fence: number;
  summary?: string | null | undefined;
  evidence?: unknown | undefined;
  task: Task["id"];
  submitter: Collaborator["id"];
};

export type ReadLateResultInput = {
  filter?: LateResultFilter | undefined;
  sort?: LateResultSort | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

/** What `load` attaches to a LateResult. The record has none of it, so reading one that was not loaded is a type error. */
export type LateResultLoadable = {
  task: Task;
  submitter: Collaborator;
};

/** A LateResult with the relationships and computed fields named in N loaded. */
export type LateResultWith<N extends keyof LateResultLoadable> = LateResult &
  Pick<LateResultLoadable, N>;

/** A LateResult as the functions of its entity file see it: every relationship and computed field present, and each related record the same. */
export type LateResultLoaded = LateResult & {
  task: TaskLoaded;
  submitter: CollaboratorLoaded;
};

export type LateResultFilter =
  | { and: readonly LateResultFilter[] }
  | { or: readonly LateResultFilter[] }
  | {
      id?: $Comparison<string>;
      fence?: $Comparison<number>;
      summary?: $Comparison<string>;
      recordedAt?: $Comparison<Date>;
      taskId?: $Comparison<string>;
      submitterId?: $Comparison<string>;
    };

export type LateResultSort = readonly (
  | "id"
  | "-id"
  | "fence"
  | "-fence"
  | "summary"
  | "-summary"
  | "recordedAt"
  | "-recordedAt"
  | "taskId"
  | "-taskId"
  | "submitterId"
  | "-submitterId"
)[];
