// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/work/late-result.mesh.mx; change that file and rebuild.
// Mesh's own imports carry a `$` so that no entity name can shadow them.

import {
  parseInput,
  type BindOptions as $BindOptions,
  type Composer as $Composer,
  type ContextArgument as $ContextArgument,
  type DataLayer as $DataLayer,
  type Row as $Row,
} from "@meshfw/runtime";
import type { LateResult, RecordLateResultInput, ReadLateResultInput } from "./lateResult.types";
import { recordLateResultInput, readLateResultInput } from "./lateResult.validators";
import { tables } from "../schema";

/**
 * The reads of this entity without the authorizer slot: what `tx` holds in a function of an entity file (ADR-0068).
 * The read actions below run the slot, then these.
 */
export function bindLateResultReads(layer: $DataLayer) {
  return Object.freeze({
    async read(input: ReadLateResultInput): Promise<LateResult[]> {
      // enter, cast: only the declared input passes
      const parsed = await parseInput(readLateResultInput, input);
      return layer.transaction(async (tx) => {
        return (await tx.select(tables.lateResult, {
          filter: parsed.filter,
          sort: parsed.sort,
          limit: parsed.limit,
          offset: parsed.offset,
        })) as LateResult[];
      });
    },
  });
}

/**
 * Every action of this entity, bound to `layer`. `compose` is the binding's composer, which hands a function its
 * `actions` and `tx`; the project's `bind` in the index passes it.
 */
export function bindLateResult(
  layer: $DataLayer,
  options: $BindOptions = {},
  _compose?: $Composer,
) {
  const $reads = bindLateResultReads(layer);
  return Object.freeze({
    async record(
      input: RecordLateResultInput,
      ...[_context]: $ContextArgument
    ): Promise<LateResult> {
      // enter, cast: the call arrives with its context, and only the declared input passes
      const parsed = await parseInput(recordLateResultInput, input);
      return layer.transaction(async (tx) => {
        // transaction: opens here; what follows commits together or not at all (pre-check: the authorizer slot before it stays empty until policies, M8)
        const $now = options.clock?.() ?? new Date();
        // plan: a create is one insert; nothing is read first
        const $changes: $Row = {
          fence: parsed.fence,
          summary: parsed.summary === undefined ? null : parsed.summary,
          evidence: parsed.evidence === undefined ? [] : parsed.evidence,
          recordedAt: $now,
          taskId: parsed.task,
          submitterId: parsed.submitter,
        };
        // data layer
        const $stored = await tx.insert(tables.lateResult, $changes);
        return $stored as LateResult;
      });
    },

    async read(input: ReadLateResultInput, ...[_context]: $ContextArgument): Promise<LateResult[]> {
      // pre-check: the read authorizer slot stays empty until policies (M8); a read through `tx` skips it
      return $reads.read(input);
    },
  });
}
