// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/work/review.mesh.mx; change that file and rebuild.

import type { Comparison as $Comparison } from "@meshfw/runtime";

import type { Submission, SubmissionLoaded } from "./submission.types";

import type { Collaborator, CollaboratorLoaded } from "../identity/collaborator.types";

export type Review = {
  id: string;
  decision: "accept" | "return";
  reasons: string | null;
  ruleApplied: "parent-assignee" | "parent-creator" | "task-creator";
  decidedAt: Date;
  submissionId: string;
  reviewerId: string;
};

export type AcceptReviewInput = {
  ruleApplied: "parent-assignee" | "parent-creator" | "task-creator";
  submission: Submission["id"];
  reviewer: Collaborator["id"];
};

export type ReturnReviewInput = {
  reasons?: string | null | undefined;
  ruleApplied: "parent-assignee" | "parent-creator" | "task-creator";
  submission: Submission["id"];
  reviewer: Collaborator["id"];
};

export type ReadReviewInput = {
  filter?: ReviewFilter | undefined;
  sort?: ReviewSort | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

/** What `load` attaches to a Review. The record has none of it, so reading one that was not loaded is a type error. */
export type ReviewLoadable = {
  submission: Submission;
  reviewer: Collaborator;
};

/** A Review with the relationships and computed fields named in N loaded. */
export type ReviewWith<N extends keyof ReviewLoadable> = Review & Pick<ReviewLoadable, N>;

/** A Review as the functions of its entity file see it: every relationship and computed field present, and each related record the same. */
export type ReviewLoaded = Review & {
  submission: SubmissionLoaded;
  reviewer: CollaboratorLoaded;
};

export type ReviewFilter =
  | { and: readonly ReviewFilter[] }
  | { or: readonly ReviewFilter[] }
  | {
      id?: $Comparison<string>;
      decision?: $Comparison<"accept" | "return">;
      reasons?: $Comparison<string>;
      ruleApplied?: $Comparison<"parent-assignee" | "parent-creator" | "task-creator">;
      decidedAt?: $Comparison<Date>;
      submissionId?: $Comparison<string>;
      reviewerId?: $Comparison<string>;
    };

export type ReviewSort = readonly (
  | "id"
  | "-id"
  | "decision"
  | "-decision"
  | "reasons"
  | "-reasons"
  | "ruleApplied"
  | "-ruleApplied"
  | "decidedAt"
  | "-decidedAt"
  | "submissionId"
  | "-submissionId"
  | "reviewerId"
  | "-reviewerId"
)[];
