// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/work/review.mesh.mx; change that file and rebuild.
// Mesh's own imports carry a `$` so that no entity name can shadow them.

import {
  parseInput,
  type BindOptions as $BindOptions,
  type Composer as $Composer,
  type ContextArgument as $ContextArgument,
  type DataLayer as $DataLayer,
  type Row as $Row,
} from "@meshfw/runtime";
import type { Review, AcceptReviewInput, ReturnReviewInput, ReadReviewInput } from "./review.types";
import { acceptReviewInput, returnReviewInput, readReviewInput } from "./review.validators";
import { tables } from "../schema";

/**
 * The reads of this entity without the authorizer slot: what `tx` holds in a function of an entity file (ADR-0068).
 * The read actions below run the slot, then these.
 */
export function bindReviewReads(layer: $DataLayer) {
  return Object.freeze({
    async read(input: ReadReviewInput): Promise<Review[]> {
      // enter, cast: only the declared input passes
      const parsed = await parseInput(readReviewInput, input);
      return layer.transaction(async (tx) => {
        return (await tx.select(tables.review, {
          filter: parsed.filter,
          sort: parsed.sort,
          limit: parsed.limit,
          offset: parsed.offset,
        })) as Review[];
      });
    },
  });
}

/**
 * Every action of this entity, bound to `layer`. `compose` is the binding's composer, which hands a function its
 * `actions` and `tx`; the project's `bind` in the index passes it.
 */
export function bindReview(layer: $DataLayer, options: $BindOptions = {}, _compose?: $Composer) {
  const $reads = bindReviewReads(layer);
  return Object.freeze({
    async accept(input: AcceptReviewInput, ...[_context]: $ContextArgument): Promise<Review> {
      // enter, cast: the call arrives with its context, and only the declared input passes
      const parsed = await parseInput(acceptReviewInput, input);
      return layer.transaction(async (tx) => {
        // transaction: opens here; what follows commits together or not at all (pre-check: the authorizer slot before it stays empty until policies, M8)
        const $now = options.clock?.() ?? new Date();
        // plan: a create is one insert; nothing is read first
        const $changes: $Row = {
          reasons: null,
          ruleApplied: parsed.ruleApplied,
          decidedAt: $now,
          submissionId: parsed.submission,
          reviewerId: parsed.reviewer,
        };
        const $record: $Row = { ...$changes };
        // do: the steps run in written order, each seeing the record as the ones before it left it
        $changes.decision = $record.decision = "accept";
        // data layer
        const $stored = await tx.insert(tables.review, $changes);
        return $stored as Review;
      });
    },

    async return(input: ReturnReviewInput, ...[_context]: $ContextArgument): Promise<Review> {
      // enter, cast: the call arrives with its context, and only the declared input passes
      const parsed = await parseInput(returnReviewInput, input);
      return layer.transaction(async (tx) => {
        // transaction: opens here; what follows commits together or not at all (pre-check: the authorizer slot before it stays empty until policies, M8)
        const $now = options.clock?.() ?? new Date();
        // plan: a create is one insert; nothing is read first
        const $changes: $Row = {
          reasons: parsed.reasons === undefined ? null : parsed.reasons,
          ruleApplied: parsed.ruleApplied,
          decidedAt: $now,
          submissionId: parsed.submission,
          reviewerId: parsed.reviewer,
        };
        const $record: $Row = { ...$changes };
        // do: the steps run in written order, each seeing the record as the ones before it left it
        $changes.decision = $record.decision = "return";
        // data layer
        const $stored = await tx.insert(tables.review, $changes);
        return $stored as Review;
      });
    },

    async read(input: ReadReviewInput, ...[_context]: $ContextArgument): Promise<Review[]> {
      // pre-check: the read authorizer slot stays empty until policies (M8); a read through `tx` skips it
      return $reads.read(input);
    },
  });
}
