// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/work/review.mesh.mx; change that file and rebuild.

import type { Comparison as $Comparison } from "@meshfw/runtime";

import type { Submission } from "./submission.types";

import type { Collaborator } from "../identity/collaborator.types";

export type Review = {
  id: string;
  decision: "accept" | "return";
  reasons: string | null;
  reviewedAt: Date;
  submissionId: string;
  reviewerId: string;
};

export type AcceptReviewInput = {
  submission: Submission["id"];
  reviewer: Collaborator["id"];
};

export type ReturnReviewInput = {
  reasons?: string | null | undefined;
  submission: Submission["id"];
  reviewer: Collaborator["id"];
};

export type ReadReviewInput = {
  filter?: ReviewFilter | undefined;
  sort?: ReviewSort | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

export type ReviewFilter =
  | { and: readonly ReviewFilter[] }
  | { or: readonly ReviewFilter[] }
  | {
      id?: $Comparison<string>;
      decision?: $Comparison<"accept" | "return">;
      reasons?: $Comparison<string>;
      reviewedAt?: $Comparison<Date>;
      submissionId?: $Comparison<string>;
      reviewerId?: $Comparison<string>;
    };

export type ReviewSort = readonly (
  | "id"
  | "-id"
  | "decision"
  | "-decision"
  | "reasons"
  | "-reasons"
  | "reviewedAt"
  | "-reviewedAt"
  | "submissionId"
  | "-submissionId"
  | "reviewerId"
  | "-reviewerId"
)[];
