// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/work/submission.mesh.mx; change that file and rebuild.

import type { Comparison as $Comparison } from "@meshfw/runtime";

import type { Task } from "./task.types";

import type { Collaborator } from "../identity/collaborator.types";

export type Submission = {
  id: string;
  summary: string | null;
  evidence: unknown;
  fence: number | null;
  taskVersion: number;
  state: "pending" | "accepted" | "returned" | "withdrawn";
  submittedAt: Date;
  taskId: string;
  submitterId: string;
};

export type SubmitSubmissionInput = {
  summary?: string | null | undefined;
  evidence?: unknown | undefined;
  fence?: number | null | undefined;
  taskVersion: number;
  task: Task["id"];
  submitter: Collaborator["id"];
};

export type ReadSubmissionInput = {
  filter?: SubmissionFilter | undefined;
  sort?: SubmissionSort | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

/** What `load` attaches to a Submission. The record has none of it, so reading one that was not loaded is a type error. */
export type SubmissionLoadable = {
  task: Task;
  submitter: Collaborator;
};

/** A Submission with the relationships and computed fields named in N loaded. */
export type SubmissionWith<N extends keyof SubmissionLoadable> = Submission &
  Pick<SubmissionLoadable, N>;

export type SubmissionFilter =
  | { and: readonly SubmissionFilter[] }
  | { or: readonly SubmissionFilter[] }
  | {
      id?: $Comparison<string>;
      summary?: $Comparison<string>;
      fence?: $Comparison<number>;
      taskVersion?: $Comparison<number>;
      state?: $Comparison<"pending" | "accepted" | "returned" | "withdrawn">;
      submittedAt?: $Comparison<Date>;
      taskId?: $Comparison<string>;
      submitterId?: $Comparison<string>;
    };

export type SubmissionSort = readonly (
  | "id"
  | "-id"
  | "summary"
  | "-summary"
  | "fence"
  | "-fence"
  | "taskVersion"
  | "-taskVersion"
  | "state"
  | "-state"
  | "submittedAt"
  | "-submittedAt"
  | "taskId"
  | "-taskId"
  | "submitterId"
  | "-submitterId"
)[];
