// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/work/submission.mesh.mx; change that file and rebuild.

import { z } from "zod";

import type {
  SubmitSubmissionInput,
  ReadSubmissionInput,
  SubmissionFilter,
} from "./submission.types";

type Keys<T> = T extends Record<string, never> ? never : keyof T;

type SameShape<A, B> = [Keys<A>] extends [Keys<B>]
  ? [Keys<B>] extends [Keys<A>]
    ? [A] extends [B]
      ? [B] extends [A]
        ? true
        : false
      : false
    : false
  : false;

type Assert<T extends true> = T;

const comparison = <T extends z.ZodType>(value: T) =>
  z.strictObject({
    eq: value.nullable().optional(),
    ne: value.nullable().optional(),
    lt: value.optional(),
    lte: value.optional(),
    gt: value.optional(),
    gte: value.optional(),
    in: z.array(value).readonly().optional(),
    nil: z.boolean().optional(),
  });

// The cast is the schema's only gap: zod writes an absent key as `?: T | undefined`, which the
// strictest `exactOptionalPropertyTypes` setting does not let the filter type accept.
export const submissionFilter: z.ZodType<SubmissionFilter> = z.lazy(
  () =>
    z.union([
      z.strictObject({ and: z.array(submissionFilter).readonly() }),
      z.strictObject({ or: z.array(submissionFilter).readonly() }),
      z.strictObject({
        id: comparison(z.uuid()).optional(),
        summary: comparison(z.string()).optional(),
        fence: comparison(z.int()).optional(),
        taskVersion: comparison(z.int()).optional(),
        state: comparison(z.enum(["pending", "accepted", "returned", "withdrawn"])).optional(),
        submittedAt: comparison(z.date()).optional(),
        taskId: comparison(z.string()).optional(),
        submitterId: comparison(z.string()).optional(),
      }),
    ]) as unknown as z.ZodType<SubmissionFilter>,
);

export const submissionSort = z
  .array(
    z.enum([
      "id",
      "-id",
      "summary",
      "-summary",
      "fence",
      "-fence",
      "taskVersion",
      "-taskVersion",
      "state",
      "-state",
      "submittedAt",
      "-submittedAt",
      "taskId",
      "-taskId",
      "submitterId",
      "-submitterId",
    ]),
  )
  .readonly();

export const submitSubmissionInput = z.strictObject({
  summary: z.string().min(1),
  evidence: (
    z
      .json()
      .refine((value) => value !== null, {
        message: "null is only allowed on a nullable attribute",
      }) as z.ZodType<unknown>
  ).optional(),
  fence: z.int(),
  taskVersion: z.int(),
  task: z.uuid(),
  submitter: z.uuid(),
}) satisfies z.ZodType<SubmitSubmissionInput>;

export type SubmitSubmissionInputShape = Assert<
  SameShape<z.output<typeof submitSubmissionInput>, SubmitSubmissionInput>
>;

export const readSubmissionInput = z.strictObject({
  filter: submissionFilter.optional(),
  sort: submissionSort.optional(),
  limit: z.int().min(0).optional(),
  offset: z.int().min(0).optional(),
}) satisfies z.ZodType<ReadSubmissionInput>;

export type ReadSubmissionInputShape = Assert<
  SameShape<z.output<typeof readSubmissionInput>, ReadSubmissionInput>
>;
