// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/work/submission.mesh.mx; change that file and rebuild.

import type { Comparison as $Comparison } from "@meshfw/runtime";

import type { Task } from "./task.types";

import type { Collaborator } from "../identity/collaborator.types";

export type Submission = {
  id: string;
  summary: string;
  evidence: unknown;
  fence: number;
  taskVersion: number;
  state: "pending" | "accepted" | "returned" | "withdrawn";
  submittedAt: Date;
  taskId: string;
  submitterId: string;
};

export type SubmitSubmissionInput = {
  summary: string;
  evidence?: unknown | undefined;
  fence: number;
  taskVersion: number;
  task: Task["id"];
  submitter: Collaborator["id"];
};

export type ReadSubmissionInput = {
  filter?: SubmissionFilter | undefined;
  sort?: SubmissionSort | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

export type SubmissionFilter =
  | { and: readonly SubmissionFilter[] }
  | { or: readonly SubmissionFilter[] }
  | {
      id?: $Comparison<string>;
      summary?: $Comparison<string>;
      fence?: $Comparison<number>;
      taskVersion?: $Comparison<number>;
      state?: $Comparison<"pending" | "accepted" | "returned" | "withdrawn">;
      submittedAt?: $Comparison<Date>;
      taskId?: $Comparison<string>;
      submitterId?: $Comparison<string>;
    };

export type SubmissionSort = readonly (
  | "id"
  | "-id"
  | "summary"
  | "-summary"
  | "fence"
  | "-fence"
  | "taskVersion"
  | "-taskVersion"
  | "state"
  | "-state"
  | "submittedAt"
  | "-submittedAt"
  | "taskId"
  | "-taskId"
  | "submitterId"
  | "-submitterId"
)[];
