// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/work/submission.mesh.mx; change that file and rebuild.
// Mesh's own imports carry a `$` so that no entity name can shadow them.

import {
  castInput as $castInput,
  noteWrite as $noteWrite,
  type BindOptions as $BindOptions,
  type Composer as $Composer,
  type ContextArgument as $ContextArgument,
  type DataLayer as $DataLayer,
  type Row as $Row,
} from "@meshfw/runtime";
import type { Submission, SubmitSubmissionInput, ReadSubmissionInput } from "./submission.types";
import { submitSubmissionInput, readSubmissionInput } from "./submission.validators";
import { tables } from "../schema";

/**
 * The reads of this entity without the authorizer slot: what `tx` holds in a function of an entity file (ADR-0068).
 * The read actions below run the slot, then these.
 */
export function bindSubmissionReads(layer: $DataLayer) {
  return Object.freeze({
    async read(input: ReadSubmissionInput): Promise<Submission[]> {
      // enter, cast: only the declared input passes; a failed cast inside a transaction fails it
      const parsed = await $castInput(layer, readSubmissionInput, input);
      return layer.transaction(async (tx) => {
        return (await tx.select(tables.submission, {
          filter: parsed.filter,
          sort: parsed.sort,
          limit: parsed.limit,
          offset: parsed.offset,
        })) as Submission[];
      });
    },
  });
}

/**
 * Every action of this entity, bound to `layer`. `compose` is the binding's composer, which hands a function its
 * `actions` and `tx`; the project's `bind` in the index passes it.
 */
export function bindSubmission(
  layer: $DataLayer,
  options: $BindOptions = {},
  _compose?: $Composer,
) {
  const $reads = bindSubmissionReads(layer);
  return Object.freeze({
    async submit(
      input: SubmitSubmissionInput,
      ...[_context]: $ContextArgument
    ): Promise<Submission> {
      // enter, cast: the call arrives with its context, and only the declared input passes; a failed cast inside a transaction fails it
      const parsed = await $castInput(layer, submitSubmissionInput, input);
      return layer.transaction(async (tx) => {
        // transaction: opens here; what follows commits together or not at all (pre-check: the authorizer slot before it stays empty until policies, M8)
        const $now = options.clock?.() ?? new Date();
        // plan: a create is one insert; nothing is read first
        const $changes: $Row = {
          summary: parsed.summary === undefined ? null : parsed.summary,
          evidence: parsed.evidence === undefined ? [] : parsed.evidence,
          fence: parsed.fence === undefined ? null : parsed.fence,
          taskVersion: parsed.taskVersion,
          state: "pending",
          submittedAt: $now,
          taskId: parsed.task,
          submitterId: parsed.submitter,
        };
        // data layer
        const $stored = await tx.insert(tables.submission, $changes);
        $noteWrite(tx);
        return $stored as Submission;
      });
    },

    async read(input: ReadSubmissionInput, ...[_context]: $ContextArgument): Promise<Submission[]> {
      // pre-check: the read authorizer slot stays empty until policies (M8); a read through `tx` skips it
      return $reads.read(input);
    },
  });
}
