// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/work/task.mesh.mx; change that file and rebuild.

import { expr as $, type Scope as $Scope } from "@meshfw/runtime";
import type { Task } from "./task.types";

/** What every expression of Task reads. */
export type TaskScope = $Scope<{
  self: Task & Record<string, any>;
  input: any;
  actor: any;
  context: any;
  before: Task | null;
  tx: any;
}>;

export const expressions = {
  // computed childrenSettled, translated (src/domain/work/task.mesh.mx:28:29)
  "computed.childrenSettled": (s: TaskScope) =>
    $.every(s.self.children, (c: any) => $.ne(c.state, "open")),
  // computed hasActiveClaim, translated (src/domain/work/task.mesh.mx:29:28)
  "computed.hasActiveClaim": (s: TaskScope) =>
    $.some(s.self.claims, (c: any) => $.eq(c.state, "active")),
} as const;
