// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/work/task.mesh.mx; change that file and rebuild.
// Mesh's own imports carry a `$` so that no entity name can shadow them.

import {
  NotFoundError as $NotFoundError,
  parseInput,
  type ContextArgument as $ContextArgument,
  type DataLayer as $DataLayer,
} from "@meshfw/runtime";
import type {
  Task,
  CreateTaskInput,
  SetPriorityTaskInput,
  MoveTaskInput,
  ReadTaskInput,
} from "./task.types";
import {
  createTaskInput,
  setPriorityTaskInput,
  moveTaskInput,
  readTaskInput,
} from "./task.validators";
import { tables } from "../schema";

export function bindTask(layer: $DataLayer) {
  return Object.freeze({
    async create(input: CreateTaskInput, ...[_context]: $ContextArgument): Promise<Task> {
      const parsed = await parseInput(createTaskInput, input);
      return layer.transaction(async (tx) => {
        const now = new Date();
        const row = await tx.insert(tables.task, {
          title: parsed.title,
          intent: parsed.intent === undefined ? null : parsed.intent,
          priority: parsed.priority === undefined ? null : parsed.priority,
          state: "open",
          version: 1,
          createdAt: now,
          parentId: parsed.parent === undefined ? null : parsed.parent,
          creatorId: parsed.creator,
        });
        return row as Task;
      });
    },

    async setPriority(input: SetPriorityTaskInput, ...[_context]: $ContextArgument): Promise<Task> {
      const parsed = await parseInput(setPriorityTaskInput, input);
      return layer.transaction(async (tx) => {
        const key = { id: parsed.id };
        const changes: Partial<Task> = {};
        if (parsed.priority !== undefined) changes.priority = parsed.priority;
        const row = await tx.updateByKey(tables.task, key, changes);
        if (row === undefined) throw new $NotFoundError("Task", key);
        return row as Task;
      });
    },

    async move(input: MoveTaskInput, ...[_context]: $ContextArgument): Promise<Task> {
      const parsed = await parseInput(moveTaskInput, input);
      return layer.transaction(async (tx) => {
        const key = { id: parsed.id };
        const changes: Partial<Task> = {};
        if (parsed.parent !== undefined) changes.parentId = parsed.parent;
        const row = await tx.updateByKey(tables.task, key, changes);
        if (row === undefined) throw new $NotFoundError("Task", key);
        return row as Task;
      });
    },

    async read(input: ReadTaskInput, ...[_context]: $ContextArgument): Promise<Task[]> {
      const parsed = await parseInput(readTaskInput, input);
      return layer.transaction(async (tx) => {
        return (await tx.select(tables.task, {
          filter: parsed.filter,
          sort: parsed.sort,
          limit: parsed.limit,
          offset: parsed.offset,
        })) as Task[];
      });
    },
  });
}
