// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/work/task.mesh.mx; change that file and rebuild.

import type { Comparison as $Comparison } from "@meshfw/runtime";

import type { Collaborator } from "../identity/collaborator.types";

import type { Dependency } from "./dependency.types";

import type { Assignment } from "./assignment.types";

import type { Claim } from "./claim.types";

import type { Submission } from "./submission.types";

import type { Completion } from "./completion.types";

import type { Event } from "../audit/event.types";

export type Task = {
  id: string;
  title: string;
  intent: string | null;
  priority: number | null;
  state: "open" | "done" | "canceled";
  version: number;
  createdAt: Date;
  parentId: string | null;
  creatorId: string;
};

export type CreateTaskInput = {
  title: string;
  intent?: string | null | undefined;
  parent?: Task["id"] | null | undefined;
  priority?: number | null | undefined;
  creator: Collaborator["id"];
};

export type SetPriorityTaskInput = {
  id: string;
  priority?: number | null | undefined;
};

export type MoveTaskInput = {
  id: string;
  parent?: Task["id"] | null | undefined;
};

export type ReadTaskInput = {
  filter?: TaskFilter | undefined;
  sort?: TaskSort | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

/** What `load` attaches to a Task. The record has none of it, so reading one that was not loaded is a type error. */
export type TaskLoadable = {
  parent: Task | null;
  creator: Collaborator;
  children: Task[];
  dependencies: Dependency[];
  dependents: Dependency[];
  assignments: Assignment[];
  claims: Claim[];
  submissions: Submission[];
  completions: Completion[];
  events: Event[];
  childrenSettled: boolean;
  claimed: boolean;
  lapsedClaim: boolean;
  inReview: boolean;
  assigned: boolean;
  blocked: boolean;
  maxFence: number | null;
  derivedState: "ready" | "blocked" | "claimed" | "in-review" | "done" | "canceled";
};

/** A Task with the relationships and computed fields named in N loaded. */
export type TaskWith<N extends keyof TaskLoadable> = Task & Pick<TaskLoadable, N>;

export type TaskFilter =
  | { and: readonly TaskFilter[] }
  | { or: readonly TaskFilter[] }
  | {
      id?: $Comparison<string>;
      title?: $Comparison<string>;
      intent?: $Comparison<string>;
      priority?: $Comparison<number>;
      state?: $Comparison<"open" | "done" | "canceled">;
      version?: $Comparison<number>;
      createdAt?: $Comparison<Date>;
      parentId?: $Comparison<string>;
      creatorId?: $Comparison<string>;
      childrenSettled?: $Comparison<boolean>;
      claimed?: $Comparison<boolean>;
      lapsedClaim?: $Comparison<boolean>;
      inReview?: $Comparison<boolean>;
      assigned?: $Comparison<boolean>;
      blocked?: $Comparison<boolean>;
      maxFence?: $Comparison<number>;
      derivedState?: $Comparison<
        "ready" | "blocked" | "claimed" | "in-review" | "done" | "canceled"
      >;
    };

export type TaskSort = readonly (
  | "id"
  | "-id"
  | "title"
  | "-title"
  | "intent"
  | "-intent"
  | "priority"
  | "-priority"
  | "state"
  | "-state"
  | "version"
  | "-version"
  | "createdAt"
  | "-createdAt"
  | "parentId"
  | "-parentId"
  | "creatorId"
  | "-creatorId"
  | "childrenSettled"
  | "-childrenSettled"
  | "claimed"
  | "-claimed"
  | "lapsedClaim"
  | "-lapsedClaim"
  | "inReview"
  | "-inReview"
  | "assigned"
  | "-assigned"
  | "blocked"
  | "-blocked"
  | "maxFence"
  | "-maxFence"
  | "derivedState"
  | "-derivedState"
)[];
