// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/work/task.mesh.mx; change that file and rebuild.

import { z } from "zod";

import type {
  CreateTaskInput,
  SetPriorityTaskInput,
  MoveTaskInput,
  ReadTaskInput,
  TaskFilter,
} from "./task.types";

type Keys<T> = T extends Record<string, never> ? never : keyof T;

type SameShape<A, B> = [Keys<A>] extends [Keys<B>]
  ? [Keys<B>] extends [Keys<A>]
    ? [A] extends [B]
      ? [B] extends [A]
        ? true
        : false
      : false
    : false
  : false;

type Assert<T extends true> = T;

const comparison = <T extends z.ZodType>(value: T) =>
  z
    .strictObject({
      eq: value.nullable().exactOptional(),
      ne: value.nullable().exactOptional(),
      lt: value.exactOptional(),
      lte: value.exactOptional(),
      gt: value.exactOptional(),
      gte: value.exactOptional(),
      in: z.array(value).readonly().exactOptional(),
      nil: z.boolean().exactOptional(),
    })
    .refine((operators) => Object.keys(operators).length > 0, {
      message: "a comparison needs an operator",
    });

export const taskFilter: z.ZodType<TaskFilter> = z.lazy(
  () =>
    z.union([
      z.strictObject({ and: z.array(taskFilter).readonly() }),
      z.strictObject({ or: z.array(taskFilter).readonly() }),
      z.strictObject({
        id: comparison(z.uuid()).exactOptional(),
        title: comparison(z.string()).exactOptional(),
        intent: comparison(z.string()).exactOptional(),
        priority: comparison(z.int()).exactOptional(),
        state: comparison(z.enum(["open", "done", "canceled"])).exactOptional(),
        version: comparison(z.int()).exactOptional(),
        createdAt: comparison(z.date()).exactOptional(),
        parentId: comparison(z.uuid()).exactOptional(),
        creatorId: comparison(z.uuid()).exactOptional(),
        childrenSettled: comparison(z.boolean()).exactOptional(),
        claimed: comparison(z.boolean()).exactOptional(),
        lapsedClaim: comparison(z.boolean()).exactOptional(),
        inReview: comparison(z.boolean()).exactOptional(),
        assigned: comparison(z.boolean()).exactOptional(),
        blocked: comparison(z.boolean()).exactOptional(),
        maxFence: comparison(z.int()).exactOptional(),
        derivedState: comparison(
          z.enum(["ready", "blocked", "claimed", "in-review", "done", "canceled"]),
        ).exactOptional(),
      }),
    ]) as unknown as z.ZodType<TaskFilter>,
);

export const taskSort = z
  .array(
    z.enum([
      "id",
      "-id",
      "title",
      "-title",
      "intent",
      "-intent",
      "priority",
      "-priority",
      "state",
      "-state",
      "version",
      "-version",
      "createdAt",
      "-createdAt",
      "parentId",
      "-parentId",
      "creatorId",
      "-creatorId",
      "childrenSettled",
      "-childrenSettled",
      "claimed",
      "-claimed",
      "lapsedClaim",
      "-lapsedClaim",
      "inReview",
      "-inReview",
      "assigned",
      "-assigned",
      "blocked",
      "-blocked",
      "maxFence",
      "-maxFence",
      "derivedState",
      "-derivedState",
    ]),
  )
  .readonly();

export const createTaskInput = z.strictObject({
  title: z.string(),
  intent: z.string().nullable().optional(),
  parent: z.uuid().nullable().optional(),
  priority: z.int().nullable().optional(),
  creator: z.uuid(),
}) satisfies z.ZodType<CreateTaskInput>;

export type CreateTaskInputShape = Assert<
  SameShape<z.output<typeof createTaskInput>, CreateTaskInput>
>;

export const setPriorityTaskInput = z.strictObject({
  id: z.uuid(),
  priority: z.int().nullable().optional(),
}) satisfies z.ZodType<SetPriorityTaskInput>;

export type SetPriorityTaskInputShape = Assert<
  SameShape<z.output<typeof setPriorityTaskInput>, SetPriorityTaskInput>
>;

export const moveTaskInput = z.strictObject({
  id: z.uuid(),
  parent: z.uuid().nullable().optional(),
}) satisfies z.ZodType<MoveTaskInput>;

export type MoveTaskInputShape = Assert<SameShape<z.output<typeof moveTaskInput>, MoveTaskInput>>;

export const readTaskInput = z.strictObject({
  filter: taskFilter.optional(),
  sort: taskSort.optional(),
  limit: z.int().min(0).optional(),
  offset: z.int().min(0).optional(),
}) satisfies z.ZodType<ReadTaskInput>;

export type ReadTaskInputShape = Assert<SameShape<z.output<typeof readTaskInput>, ReadTaskInput>>;
