export { default, default as contracts } from "./front-end/contracts.ts";
export { buildModel } from "./front-end/build.ts";
export type { BuildResult, ProjectDescription, EntityFile } from "./model/index.ts";
export { MESH_DIALECT } from "./front-end/dialect.ts";
export { MESH_EXTENSIONS, hasMeshExtension } from "./front-end/extensions.ts";
export { defineConfig, loadConfig, loadProject, type MeshConfig, type ExtensionDescriptor, type ResolvedConfig, type ConfigResult } from "./config.ts";
export { EmitError } from "./typescript/emit-error.ts";
export { EMITTERS, GENERATORS, buildEmitters, generatedImportDiagnostics, generateFiles, renderGenerator, writeGeneratedFiles, type Emitter, type EmitInput, type GeneratedFile, type GeneratedView, type Generator } from "./typescript/emit.ts";
export { MESH_TEMPLATES_DIR, PROJECT_TEMPLATES_DIR, loadTemplates, type Templates } from "./typescript/templates.ts";
export type { Template } from "./typescript/render.ts";
export { FORMATTER_OPTIONS, formatTypescript } from "./typescript/format.ts";
export { stableJsonStringify } from "./typescript/stable-json.ts";
export { typesView, type TypesView, type TypeImport, type RecordDeclaration, type TypeDeclaration, type TypeMember } from "./typescript/views/types.ts";
export { validatorsView, type ValidatorsView, type InputSchema, type SchemaField } from "./typescript/views/validators.ts";
export { RESERVED_COMMAND_WORDS, loadAdapterBuild, type AdapterBuild, type AdapterBuildResult, type AdapterCommand, type AdapterCommandContext } from "./typescript/adapter.ts";
