import { afterAll, afterEach, beforeAll, describe, expect, test } from "bun:test";
import { chmod, link, mkdtemp, mkdir, readFile, readdir, readlink, rm, symlink, writeFile, rename, lstat } from "node:fs/promises";
import { existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { RESERVED_COMMAND_WORDS, stableJsonStringify } from "@meshfw/compiler";
import { defineConfig } from "../src/index.ts";

const repo = resolve(import.meta.dir, "../../..");
const projects: string[] = [];
let command: string;
let buildDir: string;
const sourcePath = "domain/todos/todo.mesh.mx";
const source = `entity :Todo
  attributes
    uuid :id primary-key
    string :title
  actions
    create :create
      input
        &title
`;

beforeAll(async () => {
  buildDir = await mkdtemp(join(tmpdir(), "mesh-cli-command-"));
  command = join(buildDir, "bin.js");
  await linkPackages(buildDir);
  const result = await Bun.build({ entrypoints: [join(import.meta.dir, "../src/bin.ts")],
    outdir: buildDir, target: "bun", packages: "external" });
  expect(result.success).toBe(true);
});
afterAll(async () => { await rm(buildDir, { recursive: true, force: true }); });
afterEach(async () => {
  for (const root of projects.splice(0)) await rm(root, { recursive: true, force: true });
});

// Bun's isolated linker keeps workspace dependencies at each package, not at
// the root. Link the packages explicitly for a real external project fixture.
async function linkPackages(root: string): Promise<void> {
  await mkdir(join(root, "node_modules/@meshfw"), { recursive: true });
  await symlink(join(repo, "packages/cli"), join(root, "node_modules/meshfw"));
  for (const name of ["compiler", "model", "runtime"]) {
    await symlink(join(repo, "packages", name), join(root, "node_modules/@meshfw", name));
  }
}

async function project(config = true): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), "mesh-cli-project-"));
  projects.push(root);
  await mkdir(join(root, "domain/todos"), { recursive: true });
  await linkPackages(root);
  await symlink(join(repo, "packages/compiler/node_modules/zod"), join(root, "node_modules/zod"));
  await writeFile(join(root, sourcePath), source);
  if (config) await writeFile(join(root, "mesh.config.ts"), `import { defineConfig } from "meshfw";
export default defineConfig({ domain: "domain", output: "generated", data: { kind: "data-adapter", name: "sqlite", build: "./adapter.ts", options: { file: ":memory:" } } });\n`);
  // The data adapter's build half: no generators, so the core tree is what these tests see.
  await writeFile(join(root, "adapter.ts"), adapterSource);
  return root;
}
const adapterSource = "export default { generators: [] };\n";
const fakeAdapter = join(repo, "packages/compiler/test/fixtures/fake-adapter");
/** A build half re-exporting the compiler's fake adapter: one generator (`fake.ts`) and a `db push` command. */
const fakeAdapterSource = `export { default } from ${JSON.stringify(join(fakeAdapter, "build.ts"))};\n`;
function run(root: string, ...args: string[]) {
  const child = Bun.spawnSync([process.execPath, command, ...args], { cwd: root });
  return { code: child.exitCode, stdout: child.stdout.toString(), stderr: child.stderr.toString() };
}
const file = "generated/todos/todo.types.ts";
async function builtProject(): Promise<string> {
  const root = await project();
  expect(run(root, "build")).toEqual({ code: 0, stdout: "", stderr: "0 errors, 0 warnings\n" });
  return root;
}

test("defineConfig is re-exported from meshfw", () => {
  const config = { domain: "domain", output: "generated", data: { kind: "data-adapter" as const, name: "sqlite", build: "@meshfw/data-sqlite/build", options: { file: ":memory:" } } };
  expect(defineConfig(config)).toBe(config);
});

test("built command builds files then passes the guard", async () => {
  const root = await builtProject();
  expect(await readFile(join(root, file), "utf8")).toContain("export type Todo");
  expect(JSON.parse(await readFile(join(root, "generated/model.json"), "utf8")).entities[0].name).toBe("Todo");
  expect(run(root, "build", "--check")).toEqual({ code: 0, stdout: "", stderr: "0 errors, 0 warnings\n" });
});

describe("M1 test 3: guard differences", () => {
  test("M1 test 3: a hand edit fails mesh build --check and names the file", async () => {
    const root = await builtProject();
    const contents = Buffer.from([0xff, 0x00, 0xfe]);
    await writeFile(join(root, file), contents);
    const result = run(root, "build", "--check");
    expect(result).toEqual({ code: 1, stdout: "", stderr: `${file}:1:1 error Generated bytes differ; run mesh build and commit the generated tree\n1 error, 0 warnings\n` });
    expect(await readFile(join(root, file))).toEqual(contents);
  });
  test("M1 test 3: a deleted generated file fails the guard without being recreated", async () => {
    const root = await builtProject();
    await rm(join(root, file));
    expect(run(root, "build", "--check")).toEqual({ code: 1, stdout: "", stderr: `${file}:1:1 error Generated file is missing; run mesh build and commit the generated tree\n1 error, 0 warnings\n` });
    expect(await Bun.file(join(root, file)).exists()).toBe(false);
  });
  test("M1 test 3: a stray file fails both build and guard and is never deleted", async () => {
    const root = await builtProject();
    await mkdir(join(root, "generated/.old"));
    await writeFile(join(root, "generated/.old/stale.ts"), "keep me");
    const expected = { code: 1, stdout: "", stderr: "generated/.old/stale.ts:1:1 error File is not produced by the build; delete or move it out of the output directory\n1 error, 0 warnings\n" };
    expect(run(root, "build")).toEqual(expected);
    expect(run(root, "build", "--check")).toEqual(expected);
    expect(await readFile(join(root, "generated/.old/stale.ts"), "utf8")).toBe("keep me");
  });
  test.each(["file", "directory", "output", "dangling", "stray"])("M1 test 3: a symlinked %s fails the guard without following it", async (kind) => {
    const root = await builtProject();
    const path = kind === "output" ? "generated" : kind === "directory" ? "generated/todos" : kind === "stray" ? "generated/stray" : file;
    if (kind !== "stray") await rename(join(root, path), join(root, "saved"));
    // The symlink points at the exact original bytes, not different contents.
    // A following guard would incorrectly pass (or hang on a cycle).
    const target = kind === "dangling" ? "absent" : kind === "stray" ? "generated" : "saved";
    await symlink(join(root, target), join(root, path));
    const result = run(root, "build", "--check");
    expect(result.code).toBe(1);
    expect(result.stdout).toBe("");
    expect(result.stderr).toBe(`${path}:1:1 error Symlink in the output tree; delete or move it and rebuild using real files and directories\n1 error, 0 warnings\n`);
    expect((await lstat(join(root, path))).isSymbolicLink()).toBe(true);
    expect(run(root, "build").code).toBe(1);
    expect((await lstat(join(root, path))).isSymbolicLink()).toBe(true);
  });
  test("M1 test 3: a changed entity leaves a stale tree that fails the guard", async () => {
    const root = await builtProject();
    const before = await readFile(join(root, file));
    await writeFile(join(root, sourcePath), source.replace('string :title', 'integer :title'));
    const result = run(root, "build", "--check");
    expect(result.code).toBe(1);
    expect(result.stderr).toBe(`generated/model.json:1:1 error Generated bytes differ; run mesh build and commit the generated tree\n${file}:1:1 error Generated bytes differ; run mesh build and commit the generated tree\ngenerated/todos/todo.validators.ts:1:1 error Generated bytes differ; run mesh build and commit the generated tree\n3 errors, 0 warnings\n`);
    expect(await readFile(join(root, file))).toEqual(before);
  });
});

test("missing output reports every produced file in path order and writes nothing", async () => {
  const root = await project();
  expect(run(root, "build", "--check")).toEqual({ code: 1, stdout: "", stderr: `generated/index.ts:1:1 error Generated file is missing; run mesh build and commit the generated tree\ngenerated/model.json:1:1 error Generated file is missing; run mesh build and commit the generated tree\ngenerated/todos/todo.actions.ts:1:1 error Generated file is missing; run mesh build and commit the generated tree\n${file}:1:1 error Generated file is missing; run mesh build and commit the generated tree\ngenerated/todos/todo.validators.ts:1:1 error Generated file is missing; run mesh build and commit the generated tree\n5 errors, 0 warnings\n` });
  expect(await Bun.file(join(root, "generated/model.json")).exists()).toBe(false);
});

test.each(["build", "inspect"])("%s errors have exact positions and write no files or JSON", async (cmd) => {
  const root = await project();
  await writeFile(join(root, sourcePath), "");
  expect(run(root, cmd)).toEqual({ code: 1, stdout: "", stderr: `${sourcePath}:1:1 error An entity file must contain exactly one entity\n1 error, 0 warnings\n` });
  expect(await Bun.file(join(root, "generated/model.json")).exists()).toBe(false);
});

test.each([["titel", " Did you mean &title?"], ["unknown", ""]])("unknown member %s prints the exact diagnostic", async (name, tail) => {
  const root = await project();
  await writeFile(join(root, sourcePath), source.replace('&title', `&${name}`));
  expect(run(root, "build")).toEqual({ code: 1, stdout: "", stderr: `${sourcePath}:8:9 error &${name} is not a member of :Todo.${tail}\n1 error, 0 warnings\n` });
});

test("missing config is exit 1 with a diagnostic, with no upward search", async () => {
  const root = await project();
  expect(run(join(root, "domain"), "build")).toEqual({ code: 1, stdout: "", stderr: "mesh.config.ts:1:1 error Cannot read mesh.config.ts (ENOENT)\n  fix: Create mesh.config.ts with domain, output and data\n1 error, 0 warnings\n" });
});

test("invalid config is exit 1 with exact position", async () => {
  const root = await project();
  await writeFile(join(root, "mesh.config.ts"), 'export default { domain: "domain", output: 3, data: { kind: "data-adapter", name: "sqlite", build: "./adapter.ts", options: {} } };\n');
  expect(run(root, "build")).toEqual({ code: 1, stdout: "", stderr: "mesh.config.ts:1:36 error Configuration field `output` must be a non-empty relative directory path\n  fix: Fix the output field in mesh.config.ts\n1 error, 0 warnings\n" });
});

// Six `mesh` processes, each lowering entity files. The first `lowerSource` call in a process takes
// about 430 ms on alpha.15 against about 200 ms for alpha.14's `parseData` (measured locally: core
// loads its Marko front end lazily on that first call; the dialect and the build module cost under 20 ms),
// so this test went from about 4.0 s to about 5.3 s on netcup and hit bun's 5 s default. The cost is MX's
// per-process start-up, not something Mesh rebuilds per call (a second call takes about 2 ms).
test("inspect prints precisely the built model bytes or the named entity with the same serialiser", async () => {
  const root = await builtProject();
  const bytes = await readFile(join(root, "generated/model.json"), "utf8");
  const document = JSON.parse(bytes);
  expect(run(root, "inspect")).toEqual({ code: 0, stdout: bytes, stderr: "0 errors, 0 warnings\n" });
  expect(run(root, "inspect", "Todo")).toEqual({ code: 0, stdout: `${stableJsonStringify(document.entities[0])}\n`, stderr: "0 errors, 0 warnings\n" });
  expect(run(root, "inspect", "todo").code).toBe(1);
  expect(document.data).toEqual({ name: "sqlite" });
  expect(run(root, "inspect", "absent")).toEqual({ code: 1, stdout: "", stderr: 'mesh.config.ts:1:1 error Unknown entity "absent"; known entities: Todo\n1 error, 0 warnings\n' });
  await rm(join(root, "generated"), { recursive: true });
  expect(run(root, "inspect").stdout).toBe(bytes);
  expect(await Bun.file(join(root, "generated/model.json")).exists()).toBe(false);
}, 20_000);

test.each([[], ["unknown"], ["build", "--unknown"], ["build", "extra"], ["inspect", "a", "b"], ["inspect", "--check"], ["build", "--config", "x"]].map((args) => ({ args })))("usage error exits 2: $args", async ({ args }) => {
  const result = run(await project(false), ...args);
  expect(result.code).toBe(2);
  expect(result.stdout).toBe("");
  expect(result.stderr.length).toBeGreaterThan(0);
});

test.each([
  { args: ["init"], milestone: "not scheduled" },
  { args: ["explain", "todo", "create"], milestone: "M5" },
  { args: ["migrate", "generate", "--allow", "drop:todo.title"], milestone: "M9" },
  { args: ["migrate", "apply"], milestone: "M9" },
])("unavailable command names its milestone: $args", async ({ args, milestone }) => {
  const result = run(await project(false), ...args);
  expect(result.code).toBe(2);
  expect(result.stderr).toContain(`not available yet (${milestone})`);
});

test("inspect orders multiple entities exactly like model.json and lists known names", async () => {
  const root = await project();
  await writeFile(join(root, "domain/z.mesh.mx"), source.replace('entity :Todo', 'entity :Alpha'));
  expect(run(root, "build").code).toBe(0);
  const bytes = await readFile(join(root, "generated/model.json"), "utf8");
  expect(run(root, "inspect").stdout).toBe(bytes);
  expect(JSON.parse(bytes).entities.map((entity: { name: string }) => entity.name)).toEqual(["Todo", "Alpha"]);
  expect(run(root, "inspect", "missing").stderr).toBe('mesh.config.ts:1:1 error Unknown entity "missing"; known entities: Alpha, Todo\n1 error, 0 warnings\n');
});

test("build errors are sorted across files and preserve an existing tree", async () => {
  const root = await builtProject();
  const before = await readFile(join(root, file));
  await writeFile(join(root, sourcePath), "");
  await writeFile(join(root, "domain/a.mesh.mx"), "");
  expect(run(root, "build")).toEqual({ code: 1, stdout: "", stderr:
    `domain/a.mesh.mx:1:1 error An entity file must contain exactly one entity\n${sourcePath}:1:1 error An entity file must contain exactly one entity\n2 errors, 0 warnings\n` });
  expect(await readFile(join(root, file))).toEqual(before);
});

test("emit diagnostics fail build and inspect without writing or printing JSON", async () => {
  const root = await project();
  await writeFile(join(root, sourcePath), source.replace('entity :Todo', 'entity "../Todo"'));
  for (const cmd of ["build", "inspect"]) {
    const result = run(root, cmd);
    expect(result.code).toBe(1);
    expect(result.stdout).toBe("");
    expect(result.stderr).toContain(`${sourcePath}:1:8 error`);
    expect(await Bun.file(join(root, "generated/model.json")).exists()).toBe(false);
  }
});

test("filesystem preflight errors name project-relative paths and the entry type", async () => {
  const root = await project();
  await mkdir(join(root, "generated/model.json"), { recursive: true });
  expect(run(root, "build")).toEqual({ code: 1, stdout: "", stderr:
    'generated/model.json:1:1 error Cannot write generated path "generated/model.json": expected a regular file, found a directory; delete or move it and rebuild\n1 error, 0 warnings\n' });
  expect(await Bun.file(join(root, file)).exists()).toBe(false);
});

/** A regression must fail, not hang, when the writer accidentally opens a FIFO. */
async function runBounded(root: string, ...args: string[]) {
  const child = Bun.spawn([process.execPath, command, ...args], { cwd: root, stdout: "pipe", stderr: "pipe" });
  const timer = setTimeout(() => child.kill("SIGKILL"), 3000);
  try {
    const [code, stdout, stderr] = await Promise.all([
      child.exited, new Response(child.stdout).text(), new Response(child.stderr).text(),
    ]);
    return { code, stdout, stderr };
  } finally { clearTimeout(timer); }
}

/** No symlink following or special-file reads, and no atimes (reads may change them). */
async function treeSnapshot(root: string): Promise<unknown[]> {
  const entries: unknown[] = [];
  const walk = async (path: string) => {
    const absolute = join(root, path);
    const info = await lstat(absolute);
    entries.push({ path, mode: info.mode, ino: info.ino, size: info.size, nlink: info.nlink,
      mtime: info.mtimeMs, ctime: info.ctimeMs,
      contents: info.isFile() ? (await readFile(absolute)).toString("base64") : null,
      link: info.isSymbolicLink() ? await readlink(absolute) : null });
    if (info.isDirectory()) for (const name of (await readdir(absolute)).sort()) await walk(`${path}/${name}`);
  };
  await walk("generated");
  return entries;
}

test("round 2 M1: replacing a write-only generated file restores the build/check invariant", async () => {
  const root = await builtProject();
  const path = join(root, file);
  await chmod(path, 0o200);
  let readDenied = false;
  try { await readFile(path); }
  catch (cause) {
    if (!(cause instanceof Error) || !("code" in cause) || cause.code !== "EACCES") throw cause;
    readDenied = true;
  }
  if (readDenied) expect(run(root, "build", "--check").stderr).toBe(
    `${file}:1:1 error Cannot read generated file (EACCES); fix its permissions and rebuild\n1 error, 0 warnings\n`);
  else console.warn("permissions capability: this user can read mode-0200 files; testing fresh mode/inode and invariant without EACCES assertion");
  const before = await lstat(path);
  expect(run(root, "build").code).toBe(0);
  expect(run(root, "build", "--check").code).toBe(0);
  const after = await lstat(path);
  expect(after.mode & 0o777).toBe(0o644);
  expect(after.ino).not.toBe(before.ino);
  expect(after.nlink).toBe(1);
});

test("round 2 M1: replacing hard-linked generated paths restores the build/check invariant", async () => {
  const root = await builtProject();
  const model = join(root, "generated/model.json");
  const original = await readFile(model);
  await link(model, join(root, "unrelated.json"));
  await rm(join(root, file));
  await link(model, join(root, file));
  expect(run(root, "build").code).toBe(0);
  expect(run(root, "build", "--check").code).toBe(0);
  expect(await readFile(join(root, "unrelated.json"))).toEqual(original);
  expect((await lstat(model)).nlink).toBe(1);
  expect((await lstat(join(root, file))).nlink).toBe(1);
  const before = await treeSnapshot(root);
  expect(run(root, "build", "--check").code).toBe(0);
  expect(await treeSnapshot(root)).toEqual(before);
});

test("round 2 M2: a FIFO produced target is rejected without opening it or hanging", async () => {
  const root = await project();
  await mkdir(join(root, "generated"));
  expect(Bun.spawnSync(["mkfifo", join(root, "generated/model.json")]).exitCode).toBe(0);
  const before = await treeSnapshot(root);
  const checked = await runBounded(root, "build", "--check");
  expect(checked.code).toBe(1);
  expect(checked.stderr).toContain("generated/model.json:1:1 error Unsupported filesystem entry");
  expect(await treeSnapshot(root)).toEqual(before);
  const built = await runBounded(root, "build");
  expect(built.code).toBe(1);
  expect(built.stderr).toBe('generated/model.json:1:1 error Cannot write generated path "generated/model.json": expected a regular file, found a FIFO; delete or move it and rebuild\n1 error, 0 warnings\n');
  expect(await treeSnapshot(root)).toEqual(before);
}, 10000);

test("round 2 M2: a later directory target refuses the whole write before any generated bytes change", async () => {
  const root = await builtProject();
  await rm(join(root, file));
  await mkdir(join(root, file));
  await writeFile(join(root, sourcePath), source.replace('string :title', 'integer :title'));
  const before = await treeSnapshot(root);
  const result = run(root, "build");
  expect(result.code).toBe(1);
  expect(await treeSnapshot(root)).toEqual(before);
  expect(result.stderr).toBe(`${file}:1:1 error Cannot write generated path "${file}": expected a regular file, found a directory; delete or move it and rebuild\n1 error, 0 warnings\n`);
});

test.each(["inside", "outside", "dangling", "cyclic"])("round 2 L1: a %s output-root symlink is named without resolving its target", async (kind) => {
  const root = await project();
  const outside = await project(false);
  await mkdir(join(root, "real-output"));
  const target = kind === "inside" ? join(root, "real-output") : kind === "outside" ? outside :
    kind === "dangling" ? join(root, "absent") : join(root, "generated");
  await symlink(target, join(root, "generated"));
  const before = await treeSnapshot(root);
  for (const args of [["build"], ["build", "--check"], ["inspect"]]) {
    expect(run(root, ...args)).toEqual({ code: 1, stdout: "", stderr:
      "generated:1:1 error Symlink in the output tree; delete or move it and rebuild using real files and directories\n1 error, 0 warnings\n" });
    expect(await treeSnapshot(root)).toEqual(before);
  }
});

test("M2 test 2: build preflights generated imports without writes while check and inspect skip resolution", async () => {
  const root = await builtProject();
  const before = await treeSnapshot(root);
  await rm(join(root, "node_modules/zod"));
  expect(run(root, "build")).toEqual({ code: 1, stdout: "", stderr: 'mesh.config.ts:1:1 error generated code imports "zod", which is not installed in this project. Run: bun add zod\n1 error, 0 warnings\n' });
  expect(await treeSnapshot(root)).toEqual(before);
  expect(run(root, "build", "--check")).toEqual({ code: 0, stdout: "", stderr: "0 errors, 0 warnings\n" });
  expect(run(root, "inspect").code).toBe(0);
  const fresh = await project();
  await rm(join(fresh, "node_modules/zod"));
  expect(run(fresh, "build").code).toBe(1);
  expect(await Bun.file(join(fresh, "generated/model.json")).exists()).toBe(false);
});

test("help lists only implemented commands and needs no config", async () => {
  const result = run(await project(false), "--help");
  expect(result.code).toBe(0);
  expect(result.stderr).toBe("");
  expect(result.stdout).toContain("build --check");
  expect(result.stdout).toContain("inspect [entity]");
  for (const pending of ["init", "explain", "db push", "migrate"]) expect(result.stdout).not.toContain(pending);
});

describe("data adapter commands (mesh db push)", () => {
  async function fakeProject(): Promise<string> {
    const root = await project();
    await writeFile(join(root, "adapter.ts"), fakeAdapterSource);
    expect(run(root, "build").code).toBe(0);
    return root;
  }

  test("--help lists the adapter's commands under the adapter's name", async () => {
    const result = run(await fakeProject(), "--help");
    expect(result.code).toBe(0);
    expect(result.stdout).toEndWith('\nCommands from the data adapter "sqlite":\n  db push\n');
  });

  test("--help without a valid config prints the base help only", async () => {
    const root = await project();
    await writeFile(join(root, "adapter.ts"), "export default 1;\n");
    const result = run(root, "--help");
    expect(result).toEqual({ code: 0, stdout: run(await project(false), "--help").stdout, stderr: "" });
    expect(result.stdout).not.toContain("Commands from the data adapter");
  });

  test("the adapter's command gets the arguments after its words and decides the exit code", async () => {
    const root = await fakeProject();
    expect(run(root, "db", "push", "--force")).toEqual({ code: 0, stdout: "fake push sqlite --force\n", stderr: "" });
    expect(run(root, "db", "push", "--fail")).toEqual({ code: 1, stdout: "fake push sqlite --fail\n", stderr: "" });
  });

  test("the guard runs first: a stale generated tree stops the command before the adapter runs", async () => {
    const root = await fakeProject();
    await writeFile(join(root, "generated/fake.ts"), "// edited\n");
    expect(run(root, "db", "push")).toEqual({ code: 1, stdout: "",
      stderr: "the generated tree is out of date: run mesh build first\ngenerated/fake.ts:1:1 error Generated bytes differ; run mesh build and commit the generated tree\n1 error, 0 warnings\n" });
    await rm(join(root, "generated/fake.ts"));
    expect(run(root, "db", "push").stderr).toContain("generated/fake.ts:1:1 error Generated file is missing");
  });

  test("an adapter without the command says so, exit 1", async () => {
    const root = await project();
    expect(run(root, "build").code).toBe(0);
    expect(run(root, "db", "push")).toEqual({ code: 1, stdout: "",
      stderr: 'mesh.config.ts:1:1 error the data adapter "sqlite" does not provide "db push"\n1 error, 0 warnings\n' });
    expect(run(await fakeProject(), "db", "reset").stderr).toBe('mesh.config.ts:1:1 error the data adapter "sqlite" does not provide "db reset"\n1 error, 0 warnings\n');
  });

  test("a reserved word never reaches the adapter: each is a core command or a scheduled one", async () => {
    const root = await fakeProject();
    for (const word of RESERVED_COMMAND_WORDS) {
      const result = run(root, word, "push");
      expect(result.stdout).not.toContain("fake push");
      expect(result.code).not.toBe(0);
    }
  });

  test("an unknown command is a usage error, with or without a config", async () => {
    for (const root of [await fakeProject(), await project(false)]) {
      expect(run(root, "frobnicate")).toEqual({ code: 2, stdout: "", stderr: 'Unknown command "frobnicate"; use mesh --help\n' });
    }
  });

  test("mesh db push without mesh.config.ts reports the missing config, exit 1", async () => {
    expect(run(await project(false), "db", "push")).toEqual({ code: 1, stdout: "",
      stderr: "mesh.config.ts:1:1 error Cannot read mesh.config.ts (ENOENT)\n  fix: Create mesh.config.ts with domain, output and data\n1 error, 0 warnings\n" });
  });

  test("an entity error stops the command before the adapter runs", async () => {
    const root = await fakeProject();
    await writeFile(join(root, sourcePath), "entity :Todo\n");
    const result = run(root, "db", "push");
    expect(result.code).toBe(1);
    expect(result.stdout).toBe("");
  });
});

describe("roadmap Jig port, acceptance 4: a project template overrides Mesh's", () => {
  async function tree(root: string): Promise<Record<string, string>> {
    const out: Record<string, string> = {};
    for (const name of (await readdir(join(root, "generated"), { recursive: true })).sort()) {
      const path = join(root, "generated", String(name));
      if ((await lstat(path)).isFile()) out[String(name)] = await readFile(path, "utf8");
    }
    return out;
  }
  const meshTemplate = join(repo, "packages/compiler/src/typescript/templates/validators.ts.jig");

  test("an overridden validators.ts.jig changes only the *.validators.ts files, and --check passes on the new output", async () => {
    const root = await builtProject();
    await writeFile(join(root, "domain/todos/list.mesh.mx"), "entity :List\n  attributes\n    uuid :id primary-key\n");
    expect(run(root, "build").code).toBe(0);
    const before = await tree(root);
    await mkdir(join(root, ".mesh-generators"));
    await writeFile(join(root, ".mesh-generators/validators.ts.jig"), `// House rule: validators are reviewed by the platform team.\n${await readFile(meshTemplate, "utf8")}`);
    expect(run(root, "build", "--check").code).toBe(1);
    expect(run(root, "build")).toEqual({ code: 0, stdout: "", stderr: "0 errors, 0 warnings\n" });
    const after = await tree(root);
    expect(Object.keys(after)).toEqual(Object.keys(before));
    const changed = Object.keys(after).filter((path) => after[path] !== before[path]);
    expect(changed).toEqual(["todos/list.validators.ts", "todos/todo.validators.ts"]);
    for (const path of changed) expect(after[path]).toBe(`// House rule: validators are reviewed by the platform team.\n${before[path]}`);
    expect(run(root, "build", "--check")).toEqual({ code: 0, stdout: "", stderr: "0 errors, 0 warnings\n" });
  });

  test("build, --check and inspect read the same override and name it in a render error", async () => {
    const root = await builtProject();
    await mkdir(join(root, ".mesh-generators"));
    await writeFile(join(root, ".mesh-generators/types.ts.jig"), "// ok\n@if(\n");
    const expected = { code: 1, stdout: "", stderr: '.mesh-generators/types.ts.jig:2:5 error Generator "types" cannot render .mesh-generators/types.ts.jig: Missing token ")"\n  fix: Fix the template; it receives the view documented for this generator\n1 error, 0 warnings\n' };
    expect(run(root, "build")).toEqual(expected);
    expect(run(root, "build", "--check")).toEqual(expected);
    expect(run(root, "inspect")).toEqual(expected);
  });

  test("an unreadable override is MESH_TEMPLATE_READ for every command", async () => {
    const root = await builtProject();
    await mkdir(join(root, ".mesh-generators/validators.ts.jig"), { recursive: true });
    for (const args of [["build"], ["build", "--check"], ["inspect"]]) {
      const result = run(root, ...args);
      expect(result.code).toBe(1);
      expect(result.stderr).toStartWith('.mesh-generators/validators.ts.jig:1:1 error The template ".mesh-generators/validators.ts.jig" is not a regular file');
    }
  });
});

describe("the data adapter's build half in mesh build", () => {
  test("its generators write beside the core files and the guard covers them", async () => {
    const root = await project();
    await writeFile(join(root, "adapter.ts"), fakeAdapterSource);
    expect(run(root, "build")).toEqual({ code: 0, stdout: "", stderr: "0 errors, 0 warnings\n" });
    expect(await readFile(join(root, "generated/fake.ts"), "utf8")).toBe('// Written by the fake adapter.\nexport const names = ["Todo"];\n');
    expect(run(root, "build", "--check")).toEqual({ code: 0, stdout: "", stderr: "0 errors, 0 warnings\n" });
    await writeFile(join(root, "generated/fake.ts"), "// edited\n");
    expect(run(root, "build", "--check")).toEqual({ code: 1, stdout: "",
      stderr: "generated/fake.ts:1:1 error Generated bytes differ; run mesh build and commit the generated tree\n1 error, 0 warnings\n" });
  });

  test.each(["build", "inspect"])("mesh %s reports an uninstalled build half as MESH_ADAPTER_BUILD and writes nothing", async (name) => {
    const root = await project();
    await writeFile(join(root, "mesh.config.ts"), 'export default { domain: "domain", output: "generated", data: { kind: "data-adapter", name: "sqlite", build: "@meshfw/data-sqlite/build", options: { file: ":memory:" } } };\n');
    expect(run(root, name)).toEqual({ code: 1, stdout: "",
      stderr: "mesh.config.ts:1:1 error the data adapter's build entry \"@meshfw/data-sqlite/build\" cannot be resolved from this project: either @meshfw/data-sqlite is not installed, or the installed version does not export \"@meshfw/data-sqlite/build\". Run: bun add @meshfw/data-sqlite\n  fix: Install the package of the data adapter that mesh.config.ts names, in a version that has this build entry\n1 error, 0 warnings\n" });
    expect(existsSync(join(root, "generated"))).toBe(false);
  });
});

describe("mesh export generators (roadmap Jig port, acceptance 3)", () => {
  const templates = join(repo, "packages/compiler/src/typescript/templates");
  const names = ["types.ts.jig", "validators.ts.jig", "actions.ts.jig", "index.ts.jig"];
  const summary = "0 errors, 0 warnings\n";

  test("writes every template Mesh ships, then a second run is a no-op", async () => {
    const root = await project();
    expect(run(root, "export", "generators")).toEqual({ code: 0, stderr: summary,
      stdout: names.map((name) => `wrote .mesh-generators/${name}\n`).join("") });
    expect((await readdir(join(root, ".mesh-generators"))).sort()).toEqual([...names].sort());
    for (const name of names)
      expect(await readFile(join(root, ".mesh-generators", name), "utf8")).toBe(await readFile(join(templates, name), "utf8"));
    expect(run(root, "export", "generators")).toEqual({ code: 0, stderr: summary,
      stdout: "nothing to export: .mesh-generators/ already holds Mesh's templates\n" });
    // The exported copies are Mesh's templates, so the build output is unchanged.
    expect(run(root, "build")).toEqual({ code: 0, stdout: "", stderr: summary });
  });

  test("the data adapter's templates are exported too, read from its templateDir", async () => {
    const root = await project();
    await writeFile(join(root, "adapter.ts"), fakeAdapterSource);
    expect(run(root, "export", "generators")).toEqual({ code: 0, stderr: summary,
      stdout: [...names, "fake.ts.jig"].map((name) => `wrote .mesh-generators/${name}\n`).join("") });
    expect(await readFile(join(root, ".mesh-generators/fake.ts.jig"), "utf8")).toBe(await readFile(join(fakeAdapter, "templates/fake.ts.jig"), "utf8"));
  });

  test("an invalid adapter build half stops the export before anything is written", async () => {
    const root = await project();
    await writeFile(join(root, "adapter.ts"), "export const nothing = 1;\n");
    expect(run(root, "export", "generators")).toEqual({ code: 1, stdout: "",
      stderr: 'mesh.config.ts:1:1 error the data adapter\'s build entry "./adapter.ts" has no default export of an AdapterBuild object\n  fix: Use a data adapter whose build entry default-exports { generators, commands }\n1 error, 0 warnings\n' });
    expect(existsSync(join(root, ".mesh-generators"))).toBe(false);
  });

  test("writes only the absent templates when the others are identical", async () => {
    const root = await project();
    await mkdir(join(root, ".mesh-generators"));
    await writeFile(join(root, ".mesh-generators/types.ts.jig"), await readFile(join(templates, "types.ts.jig")));
    expect(run(root, "export", "generators")).toEqual({ code: 0, stderr: summary, stdout: "wrote .mesh-generators/validators.ts.jig\nwrote .mesh-generators/actions.ts.jig\nwrote .mesh-generators/index.ts.jig\n" });
  });

  test("a differing template stops the export: nothing is written, the file is listed, exit 1", async () => {
    const root = await project();
    await mkdir(join(root, ".mesh-generators"));
    await writeFile(join(root, ".mesh-generators/validators.ts.jig"), "// mine\n");
    expect(run(root, "export", "generators")).toEqual({ code: 1, stdout: "",
      stderr: ".mesh-generators/validators.ts.jig:1:1 error Differs from Mesh's template; nothing was exported. Move your template aside to export Mesh's, or keep it and export nothing\n1 error, 0 warnings\n" });
    expect(await readdir(join(root, ".mesh-generators"))).toEqual(["validators.ts.jig"]);
    expect(await readFile(join(root, ".mesh-generators/validators.ts.jig"), "utf8")).toBe("// mine\n");
  });

  test.each(["template", "folder"])("a symlinked %s is refused and not followed", async (kind) => {
    const root = await project();
    await mkdir(join(root, "elsewhere"));
    if (kind === "folder") await symlink(join(root, "elsewhere"), join(root, ".mesh-generators"));
    else {
      await mkdir(join(root, ".mesh-generators"));
      await symlink(join(root, "elsewhere/types.ts.jig"), join(root, ".mesh-generators/types.ts.jig"));
    }
    const result = run(root, "export", "generators");
    expect(result.code).toBe(1);
    expect(result.stderr).toStartWith(kind === "folder" ? ".mesh-generators:1:1 error" : ".mesh-generators/types.ts.jig:1:1 error Is a symlink");
    expect(await readdir(join(root, "elsewhere"))).toEqual([]);
    if (kind === "template") expect(await Bun.file(join(root, ".mesh-generators/validators.ts.jig")).exists()).toBe(false);
  });

  test("a directory at a template's path is refused", async () => {
    const root = await project();
    await mkdir(join(root, ".mesh-generators/types.ts.jig"), { recursive: true });
    const result = run(root, "export", "generators");
    expect(result.code).toBe(1);
    expect(result.stderr).toContain(".mesh-generators/types.ts.jig:1:1 error Is not a regular file");
  });

  test("without mesh.config.ts nothing is written", async () => {
    const root = await project(false);
    expect(run(root, "export", "generators").code).toBe(1);
    expect(await Bun.file(join(root, ".mesh-generators/types.ts.jig")).exists()).toBe(false);
  });

  test.each([[["export"]], [["export", "templates"]], [["export", "generators", "extra"]], [["export", "generators", "--check"]]])("usage error exits 2: %j", async (args) => {
    const result = run(await project(), ...args);
    expect(result.code).toBe(2);
    expect(result.stdout).toBe("");
  });

  test("--help lists the command", async () => {
    expect(run(await project(false), "--help").stdout).toContain("export generators   Copy Mesh's generator templates into .mesh-generators/");
  });
});

test("importing meshfw loads the runtime's defineConfig and no compiler code (ADR-0033)", () => {
  // A fresh process: this test file itself has already loaded the compiler.
  const probe = `
    const { defineConfig } = await import("meshfw");
    const runtime = await import("@meshfw/runtime");
    if (defineConfig !== runtime.defineConfig) throw new Error("meshfw's defineConfig is not the runtime's");
    const loaded = Object.keys(require.cache);
    console.log(JSON.stringify(loaded.filter((path) => path.includes("/packages/compiler/") || path.includes("@meshfw/compiler"))));
    console.log(JSON.stringify(loaded.some((path) => path.includes("/packages/runtime/"))));
  `;
  const result = Bun.spawnSync([process.execPath, "--eval", probe], { cwd: join(import.meta.dir, ".."), stdout: "pipe", stderr: "pipe" });
  expect(result.stderr.toString()).toBe("");
  expect(result.stdout.toString()).toBe("[]\ntrue\n");
});
