import { afterAll, afterEach, beforeAll, describe, expect, test } from "bun:test";
import { chmod, link, mkdtemp, mkdir, readFile, readdir, readlink, rm, symlink, writeFile, rename, lstat } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { stableJsonStringify } from "@mesh/compiler";
import { defineConfig } from "../src/index.ts";

const repo = resolve(import.meta.dir, "../../..");
const projects: string[] = [];
let command: string;
let buildDir: string;
const source = `resource="todo" domain="todos"
  attributes
    uuid-primary-key="id"
    attribute="title" type="string" allow-nil=false
  actions
    create="create" accept=["title"]
`;

beforeAll(async () => {
  buildDir = await mkdtemp(join(tmpdir(), "mesh-cli-command-"));
  command = join(buildDir, "bin.js");
  await linkPackages(buildDir);
  const result = await Bun.build({ entrypoints: [join(import.meta.dir, "../src/bin.ts")],
    outdir: buildDir, target: "bun", packages: "external" });
  expect(result.success).toBe(true);
});
afterAll(async () => { await rm(buildDir, { recursive: true, force: true }); });
afterEach(async () => {
  for (const root of projects.splice(0)) await rm(root, { recursive: true, force: true });
});

// Bun's isolated linker keeps workspace dependencies at each package, not at
// the root. Link the packages explicitly for a real external project fixture.
async function linkPackages(root: string): Promise<void> {
  await mkdir(join(root, "node_modules/@mesh"), { recursive: true });
  for (const name of ["cli", "compiler", "model"]) {
    await symlink(join(repo, "packages", name), join(root, "node_modules/@mesh", name));
  }
}

async function project(config = true): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), "mesh-cli-project-"));
  projects.push(root);
  await mkdir(join(root, "resources"));
  await linkPackages(root);
  await writeFile(join(root, "resources/todo.mx"), source);
  if (config) await writeFile(join(root, "mesh.config.ts"), `import { defineConfig } from "@mesh/cli";
export default defineConfig({ resources: "resources", output: "generated" });\n`);
  return root;
}
function run(root: string, ...args: string[]) {
  const child = Bun.spawnSync([process.execPath, command, ...args], { cwd: root });
  return { code: child.exitCode, stdout: child.stdout.toString(), stderr: child.stderr.toString() };
}
const file = "generated/todos/todo.types.ts";
async function builtProject(): Promise<string> {
  const root = await project();
  expect(run(root, "build")).toEqual({ code: 0, stdout: "", stderr: "0 errors, 0 warnings\n" });
  return root;
}

test("defineConfig is re-exported from @mesh/cli", () => {
  const config = { resources: "resources", output: "generated" };
  expect(defineConfig(config)).toBe(config);
});

test("built command builds files then passes the guard", async () => {
  const root = await builtProject();
  expect(await readFile(join(root, file), "utf8")).toContain("export type Todo");
  expect(JSON.parse(await readFile(join(root, "generated/model.json"), "utf8")).resources[0].name.value).toBe("todo");
  expect(run(root, "build", "--check")).toEqual({ code: 0, stdout: "", stderr: "0 errors, 0 warnings\n" });
});

describe("M1 test 3: guard differences", () => {
  test("M1 test 3: a hand edit fails mesh build --check and names the file", async () => {
    const root = await builtProject();
    const contents = Buffer.from([0xff, 0x00, 0xfe]);
    await writeFile(join(root, file), contents);
    const result = run(root, "build", "--check");
    expect(result).toEqual({ code: 1, stdout: "", stderr: `${file}:1:1 error Generated bytes differ; run mesh build and commit the generated tree\n1 error, 0 warnings\n` });
    expect(await readFile(join(root, file))).toEqual(contents);
  });
  test("M1 test 3: a deleted generated file fails the guard without being recreated", async () => {
    const root = await builtProject();
    await rm(join(root, file));
    expect(run(root, "build", "--check")).toEqual({ code: 1, stdout: "", stderr: `${file}:1:1 error Generated file is missing; run mesh build and commit the generated tree\n1 error, 0 warnings\n` });
    expect(await Bun.file(join(root, file)).exists()).toBe(false);
  });
  test("M1 test 3: a stray file fails both build and guard and is never deleted", async () => {
    const root = await builtProject();
    await mkdir(join(root, "generated/.old"));
    await writeFile(join(root, "generated/.old/stale.ts"), "keep me");
    const expected = { code: 1, stdout: "", stderr: "generated/.old/stale.ts:1:1 error File is not produced by the build; delete or move it out of the output directory\n1 error, 0 warnings\n" };
    expect(run(root, "build")).toEqual(expected);
    expect(run(root, "build", "--check")).toEqual(expected);
    expect(await readFile(join(root, "generated/.old/stale.ts"), "utf8")).toBe("keep me");
  });
  test.each(["file", "directory", "output", "dangling", "stray"])("M1 test 3: a symlinked %s fails the guard without following it", async (kind) => {
    const root = await builtProject();
    const path = kind === "output" ? "generated" : kind === "directory" ? "generated/todos" : kind === "stray" ? "generated/stray" : file;
    if (kind !== "stray") await rename(join(root, path), join(root, "saved"));
    // The symlink points at the exact original bytes, not different contents.
    // A following guard would incorrectly pass (or hang on a cycle).
    const target = kind === "dangling" ? "absent" : kind === "stray" ? "generated" : "saved";
    await symlink(join(root, target), join(root, path));
    const result = run(root, "build", "--check");
    expect(result.code).toBe(1);
    expect(result.stdout).toBe("");
    expect(result.stderr).toBe(`${path}:1:1 error Symlink in the output tree; delete or move it and rebuild using real files and directories\n1 error, 0 warnings\n`);
    expect((await lstat(join(root, path))).isSymbolicLink()).toBe(true);
    expect(run(root, "build").code).toBe(1);
    expect((await lstat(join(root, path))).isSymbolicLink()).toBe(true);
  });
  test("M1 test 3: a changed resource leaves a stale tree that fails the guard", async () => {
    const root = await builtProject();
    const before = await readFile(join(root, file));
    await writeFile(join(root, "resources/todo.mx"), source.replace('type="string"', 'type="integer"'));
    const result = run(root, "build", "--check");
    expect(result.code).toBe(1);
    expect(result.stderr).toBe(`generated/model.json:1:1 error Generated bytes differ; run mesh build and commit the generated tree\n${file}:1:1 error Generated bytes differ; run mesh build and commit the generated tree\n2 errors, 0 warnings\n`);
    expect(await readFile(join(root, file))).toEqual(before);
  });
});

test("missing output reports every produced file in path order and writes nothing", async () => {
  const root = await project();
  expect(run(root, "build", "--check")).toEqual({ code: 1, stdout: "", stderr: `generated/model.json:1:1 error Generated file is missing; run mesh build and commit the generated tree\n${file}:1:1 error Generated file is missing; run mesh build and commit the generated tree\n2 errors, 0 warnings\n` });
  expect(await Bun.file(join(root, "generated/model.json")).exists()).toBe(false);
});

test.each(["build", "inspect"])("%s errors have exact positions and write no files or JSON", async (cmd) => {
  const root = await project();
  await writeFile(join(root, "resources/todo.mx"), "");
  expect(run(root, cmd)).toEqual({ code: 1, stdout: "", stderr: "resources/todo.mx:1:1 error A resource file must contain exactly one `resource` (fix: Declare exactly one resource in this file)\n1 error, 0 warnings\n" });
  expect(await Bun.file(join(root, "generated/model.json")).exists()).toBe(false);
});

test("missing config is exit 1 with a diagnostic, with no upward search", async () => {
  const root = await project();
  expect(run(join(root, "resources"), "build")).toEqual({ code: 1, stdout: "", stderr: "mesh.config.ts:1:1 error Cannot read mesh.config.ts (ENOENT) (fix: Create mesh.config.ts with resources and output)\n1 error, 0 warnings\n" });
});

test("invalid config is exit 1 with exact position", async () => {
  const root = await project();
  await writeFile(join(root, "mesh.config.ts"), 'export default { resources: "resources", output: 3 };\n');
  expect(run(root, "build")).toEqual({ code: 1, stdout: "", stderr: "mesh.config.ts:1:42 error Configuration field `output` must be a non-empty relative directory path (fix: Fix the output field in mesh.config.ts)\n1 error, 0 warnings\n" });
});

test("inspect prints precisely the built model bytes or the named resource with the same serialiser", async () => {
  const root = await builtProject();
  const bytes = await readFile(join(root, "generated/model.json"), "utf8");
  const document = JSON.parse(bytes);
  expect(run(root, "inspect")).toEqual({ code: 0, stdout: bytes, stderr: "0 errors, 0 warnings\n" });
  expect(run(root, "inspect", "todo")).toEqual({ code: 0, stdout: `${stableJsonStringify(document.resources[0])}\n`, stderr: "0 errors, 0 warnings\n" });
  expect(run(root, "inspect", "absent")).toEqual({ code: 1, stdout: "", stderr: 'mesh.config.ts:1:1 error Unknown resource "absent"; known resources: todo\n1 error, 0 warnings\n' });
  await rm(join(root, "generated"), { recursive: true });
  expect(run(root, "inspect").stdout).toBe(bytes);
  expect(await Bun.file(join(root, "generated/model.json")).exists()).toBe(false);
});

test.each([[], ["unknown"], ["build", "--unknown"], ["build", "extra"], ["inspect", "a", "b"], ["inspect", "--check"], ["build", "--config", "x"]].map((args) => ({ args })))("usage error exits 2: $args", async ({ args }) => {
  const result = run(await project(false), ...args);
  expect(result.code).toBe(2);
  expect(result.stdout).toBe("");
  expect(result.stderr.length).toBeGreaterThan(0);
});

test.each([
  { args: ["init"], milestone: "not scheduled" },
  { args: ["explain", "todo", "create"], milestone: "M5" },
  { args: ["db", "push"], milestone: "M2" },
  { args: ["migrate", "generate", "--allow", "drop:todo.title"], milestone: "M9" },
  { args: ["migrate", "apply"], milestone: "M9" },
])("unavailable command names its milestone: $args", async ({ args, milestone }) => {
  const result = run(await project(false), ...args);
  expect(result.code).toBe(2);
  expect(result.stderr).toContain(`not available yet (${milestone})`);
});

test("inspect orders multiple resources exactly like model.json and lists known names", async () => {
  const root = await project();
  await writeFile(join(root, "resources/z.mx"), source.replace('resource="todo"', 'resource="alpha"'));
  expect(run(root, "build").code).toBe(0);
  const bytes = await readFile(join(root, "generated/model.json"), "utf8");
  expect(run(root, "inspect").stdout).toBe(bytes);
  expect(JSON.parse(bytes).resources.map((r: { name: { value: string } }) => r.name.value)).toEqual(["alpha", "todo"]);
  expect(run(root, "inspect", "missing").stderr).toBe('mesh.config.ts:1:1 error Unknown resource "missing"; known resources: alpha, todo\n1 error, 0 warnings\n');
});

test("build errors are sorted across files and preserve an existing tree", async () => {
  const root = await builtProject();
  const before = await readFile(join(root, file));
  await writeFile(join(root, "resources/todo.mx"), "");
  await writeFile(join(root, "resources/a.mx"), "");
  expect(run(root, "build")).toEqual({ code: 1, stdout: "", stderr:
    "resources/a.mx:1:1 error A resource file must contain exactly one `resource` (fix: Declare exactly one resource in this file)\nresources/todo.mx:1:1 error A resource file must contain exactly one `resource` (fix: Declare exactly one resource in this file)\n2 errors, 0 warnings\n" });
  expect(await readFile(join(root, file))).toEqual(before);
});

test("emit diagnostics fail build and inspect without writing or printing JSON", async () => {
  const root = await project();
  await writeFile(join(root, "resources/todo.mx"), source.replace('resource="todo"', 'resource="../todo"'));
  for (const cmd of ["build", "inspect"]) {
    const result = run(root, cmd);
    expect(result.code).toBe(1);
    expect(result.stdout).toBe("");
    expect(result.stderr).toStartWith('resources/todo.mx:1:10 error Name "../todo" cannot be used in a generated file path');
    expect(await Bun.file(join(root, "generated/model.json")).exists()).toBe(false);
  }
});

test("filesystem preflight errors name project-relative paths and the entry type", async () => {
  const root = await project();
  await mkdir(join(root, "generated/model.json"), { recursive: true });
  expect(run(root, "build")).toEqual({ code: 1, stdout: "", stderr:
    'generated/model.json:1:1 error Cannot write generated path "generated/model.json": expected a regular file, found a directory; delete or move it and rebuild\n1 error, 0 warnings\n' });
  expect(await Bun.file(join(root, file)).exists()).toBe(false);
});

/** A regression must fail, not hang, when the writer accidentally opens a FIFO. */
async function runBounded(root: string, ...args: string[]) {
  const child = Bun.spawn([process.execPath, command, ...args], { cwd: root, stdout: "pipe", stderr: "pipe" });
  const timer = setTimeout(() => child.kill("SIGKILL"), 3000);
  try {
    const [code, stdout, stderr] = await Promise.all([
      child.exited, new Response(child.stdout).text(), new Response(child.stderr).text(),
    ]);
    return { code, stdout, stderr };
  } finally { clearTimeout(timer); }
}

/** No symlink following or special-file reads, and no atimes (reads may change them). */
async function treeSnapshot(root: string): Promise<unknown[]> {
  const entries: unknown[] = [];
  const walk = async (path: string) => {
    const absolute = join(root, path);
    const info = await lstat(absolute);
    entries.push({ path, mode: info.mode, ino: info.ino, size: info.size, nlink: info.nlink,
      mtime: info.mtimeMs, ctime: info.ctimeMs,
      contents: info.isFile() ? (await readFile(absolute)).toString("base64") : null,
      link: info.isSymbolicLink() ? await readlink(absolute) : null });
    if (info.isDirectory()) for (const name of (await readdir(absolute)).sort()) await walk(`${path}/${name}`);
  };
  await walk("generated");
  return entries;
}

test("round 2 M1: replacing a write-only generated file restores the build/check invariant", async () => {
  const root = await builtProject();
  const path = join(root, file);
  await chmod(path, 0o200);
  let readDenied = false;
  try { await readFile(path); }
  catch (cause) {
    if (!(cause instanceof Error) || !("code" in cause) || cause.code !== "EACCES") throw cause;
    readDenied = true;
  }
  if (readDenied) expect(run(root, "build", "--check").stderr).toBe(
    `${file}:1:1 error Cannot read generated file (EACCES); fix its permissions and rebuild\n1 error, 0 warnings\n`);
  else console.warn("permissions capability: this user can read mode-0200 files; testing fresh mode/inode and invariant without EACCES assertion");
  const before = await lstat(path);
  expect(run(root, "build").code).toBe(0);
  expect(run(root, "build", "--check").code).toBe(0);
  const after = await lstat(path);
  expect(after.mode & 0o777).toBe(0o644);
  expect(after.ino).not.toBe(before.ino);
  expect(after.nlink).toBe(1);
});

test("round 2 M1: replacing hard-linked generated paths restores the build/check invariant", async () => {
  const root = await builtProject();
  const model = join(root, "generated/model.json");
  const original = await readFile(model);
  await link(model, join(root, "unrelated.json"));
  await rm(join(root, file));
  await link(model, join(root, file));
  expect(run(root, "build").code).toBe(0);
  expect(run(root, "build", "--check").code).toBe(0);
  expect(await readFile(join(root, "unrelated.json"))).toEqual(original);
  expect((await lstat(model)).nlink).toBe(1);
  expect((await lstat(join(root, file))).nlink).toBe(1);
  const before = await treeSnapshot(root);
  expect(run(root, "build", "--check").code).toBe(0);
  expect(await treeSnapshot(root)).toEqual(before);
});

test("round 2 M2: a FIFO produced target is rejected without opening it or hanging", async () => {
  const root = await project();
  await mkdir(join(root, "generated"));
  expect(Bun.spawnSync(["mkfifo", join(root, "generated/model.json")]).exitCode).toBe(0);
  const before = await treeSnapshot(root);
  const checked = await runBounded(root, "build", "--check");
  expect(checked.code).toBe(1);
  expect(checked.stderr).toContain("generated/model.json:1:1 error Unsupported filesystem entry");
  expect(await treeSnapshot(root)).toEqual(before);
  const built = await runBounded(root, "build");
  expect(built.code).toBe(1);
  expect(built.stderr).toBe('generated/model.json:1:1 error Cannot write generated path "generated/model.json": expected a regular file, found a FIFO; delete or move it and rebuild\n1 error, 0 warnings\n');
  expect(await treeSnapshot(root)).toEqual(before);
}, 10000);

test("round 2 M2: a later directory target refuses the whole write before any generated bytes change", async () => {
  const root = await builtProject();
  await rm(join(root, file));
  await mkdir(join(root, file));
  await writeFile(join(root, "resources/todo.mx"), source.replace('type="string"', 'type="integer"'));
  const before = await treeSnapshot(root);
  const result = run(root, "build");
  expect(result.code).toBe(1);
  expect(await treeSnapshot(root)).toEqual(before);
  expect(result.stderr).toBe(`${file}:1:1 error Cannot write generated path "${file}": expected a regular file, found a directory; delete or move it and rebuild\n1 error, 0 warnings\n`);
});

test.each(["inside", "outside", "dangling", "cyclic"])("round 2 L1: a %s output-root symlink is named without resolving its target", async (kind) => {
  const root = await project();
  const outside = await project(false);
  await mkdir(join(root, "real-output"));
  const target = kind === "inside" ? join(root, "real-output") : kind === "outside" ? outside :
    kind === "dangling" ? join(root, "absent") : join(root, "generated");
  await symlink(target, join(root, "generated"));
  const before = await treeSnapshot(root);
  for (const args of [["build"], ["build", "--check"], ["inspect"]]) {
    expect(run(root, ...args)).toEqual({ code: 1, stdout: "", stderr:
      "generated:1:1 error Symlink in the output tree; delete or move it and rebuild using real files and directories\n1 error, 0 warnings\n" });
    expect(await treeSnapshot(root)).toEqual(before);
  }
});

test("help lists only implemented commands and needs no config", async () => {
  const result = run(await project(false), "--help");
  expect(result.code).toBe(0);
  expect(result.stderr).toBe("");
  expect(result.stdout).toContain("build --check");
  expect(result.stdout).toContain("inspect [resource]");
  for (const pending of ["init", "explain", "db push", "migrate"]) expect(result.stdout).not.toContain(pending);
});
