import { expect, test } from "bun:test";
import { cpSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { Database } from "bun:sqlite";

const repo = resolve(import.meta.dir, "../../..");
const example = join(repo, "examples/blog");
function validate(cwd: string) {
  const result = Bun.spawnSync([process.execPath, "run", "validate"], { cwd });
  return { code: result.exitCode, stderr: result.stderr.toString() };
}

test("M1 test 3: verify-discovered blog validate script guards the committed tree", () => {
  expect(validate(example)).toEqual({ code: 0, stderr: "$ mesh build --check\n0 errors, 0 warnings\n" });
});

test.each(["types", "validators"])("M2 test 2: blog validate script rejects a planted stale %s file without writing", (kind) => {
  const dir = mkdtempSync(join(repo, ".m1-blog-guard-"));
  try {
    for (const path of ["mesh.config.ts", "package.json", "src", ".mesh"]) {
      cpSync(join(example, path), join(dir, path), { recursive: true });
    }
    symlinkSync(join(example, "node_modules"), join(dir, "node_modules"));
    expect(validate(dir).code).toBe(0);
    const path = join(dir, `.mesh/blog/post.${kind}.ts`);
    const stale = `${readFileSync(path, "utf8")}\n// planted hand edit\n`;
    writeFileSync(path, stale);
    const result = validate(dir);
    expect(result.code).toBe(1);
    expect(result.stderr).toContain(`.mesh/blog/post.${kind}.ts:1:1 error Generated bytes differ; run mesh build and commit the generated tree`);
    expect(readFileSync(path, "utf8")).toBe(stale);
  } finally { rmSync(dir, { recursive: true, force: true }); }
});

/** A temporary copy of the example inside the workspace, sharing its installed packages. */
function exampleCopy(): string {
  const dir = mkdtempSync(join(repo, ".m2-blog-db-"));
  for (const path of ["mesh.config.ts", "package.json", "src", ".mesh"]) cpSync(join(example, path), join(dir, path), { recursive: true });
  symlinkSync(join(example, "node_modules"), join(dir, "node_modules"));
  return dir;
}
function script(cwd: string, name: string, ...args: string[]) {
  const result = Bun.spawnSync([process.execPath, "run", name, ...args], { cwd });
  return { code: result.exitCode, stdout: result.stdout.toString(), stderr: result.stderr.toString() };
}
function tableNames(file: string): string[] {
  const db = new Database(file, { readonly: true });
  try { return db.query<{ name: string }, []>("SELECT name FROM sqlite_master WHERE type = 'table' ORDER BY name").all().map((row) => row.name); }
  finally { db.close(); }
}

test("M2 test 6: blog validate script rejects a hand-edited schema.ts and names the file", () => {
  const dir = exampleCopy();
  try {
    const path = join(dir, ".mesh/schema.ts");
    writeFileSync(path, `${readFileSync(path, "utf8")}// planted hand edit\n`);
    const result = validate(dir);
    expect(result.code).toBe(1);
    expect(result.stderr).toContain(".mesh/schema.ts:1:1 error Generated bytes differ; run mesh build and commit the generated tree");
  } finally { rmSync(dir, { recursive: true, force: true }); }
});

test("M2 test 6: bun run db:push creates the example's three tables, then has nothing to do", () => {
  const dir = exampleCopy();
  try {
    const first = script(dir, "db:push");
    expect(first.stderr).toBe("$ mesh db push\n");
    expect(first.code).toBe(0);
    expect(first.stdout).toContain("CREATE TABLE `posts`");
    expect(first.stdout).toEndWith("applied 3 statements to blog.db\n");
    expect(tableNames(join(dir, "blog.db"))).toEqual(["comments", "posts", "users"]);
    expect(script(dir, "db:push")).toEqual({ code: 0, stdout: "schema is up to date: blog.db\n", stderr: "$ mesh db push\n" });
  } finally { rmSync(dir, { recursive: true, force: true }); }
}, 20_000);

test("mesh db push refuses a stale tree, refuses data loss without --force, and applies it with --force", () => {
  const dir = exampleCopy();
  try {
    expect(script(dir, "db:push").code).toBe(0);
    // Dropping a table loses data only when it holds rows.
    const db = new Database(join(dir, "blog.db"));
    try { db.run("INSERT INTO comments (id, body) VALUES ('c1', 'kept')"); } finally { db.close(); }
    rmSync(join(dir, "src/domain/blog/comment.mesh.mx"));
    writeFileSync(join(dir, "src/domain/blog/post.mesh.mx"), readFileSync(join(dir, "src/domain/blog/post.mesh.mx"), "utf8")
      .replace('import { Comment } from "./comment.mesh.mx"\n', "").replace("    has-many :comments entity=Comment\n", "")
      .replace('    count :commentCount of="comments"\n', "").replace("load=[&comments, &excerpt]", "load=[&excerpt]"));
    const stale = script(dir, "db:push");
    expect(stale.code).toBe(1);
    expect(stale.stderr).toStartWith("$ mesh db push\nthe generated tree is out of date: run mesh build first\n");
    expect(stale.stderr).toContain(".mesh/schema.ts:1:1 error Generated bytes differ");
    // A build never deletes files: the removed entity's generated files go by hand.
    for (const kind of ["types", "validators"]) rmSync(join(dir, `.mesh/blog/comment.${kind}.ts`));
    const built = Bun.spawnSync([process.execPath, "x", "mesh", "build"], { cwd: dir });
    expect(built.stderr.toString()).toBe("0 errors, 0 warnings\n");
    const refused = script(dir, "db:push");
    expect(refused.code).toBe(1);
    expect(refused.stderr).toContain("db push refuses statements that would lose data in blog.db:\nDROP TABLE `comments`;");
    expect(refused.stderr).toContain("\nNothing was applied. Run mesh db push --force to apply them anyway.\n");
    expect(tableNames(join(dir, "blog.db"))).toEqual(["comments", "posts", "users"]);
    expect(refused.stdout).toBe("");
    const forced = script(dir, "db:push", "--force");
    expect(forced.code).toBe(0);
    expect(forced.stdout).toContain("DROP TABLE `comments`;");
    expect(tableNames(join(dir, "blog.db"))).toEqual(["posts", "users"]);
  } finally { rmSync(dir, { recursive: true, force: true }); }
}, 30_000);

test("mesh db push needs a database file: :memory: is refused", () => {
  const dir = exampleCopy();
  try {
    writeFileSync(join(dir, "mesh.config.ts"), readFileSync(join(dir, "mesh.config.ts"), "utf8").replace('"blog.db"', '":memory:"'));
    const result = script(dir, "db:push");
    expect(result.code).toBe(1);
    expect(result.stdout).toBe("");
    expect(result.stderr).toStartWith("$ mesh db push\ndb push needs a database file: an in-memory database ends with the process; use createSchema in tests\n");
  } finally { rmSync(dir, { recursive: true, force: true }); }
});
