import { expect, test } from "bun:test";
import { cpSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const repo = resolve(import.meta.dir, "../../..");
const example = join(repo, "examples/blog");
function validate(cwd: string) {
  const result = Bun.spawnSync([process.execPath, "run", "validate"], { cwd });
  return { code: result.exitCode, stderr: result.stderr.toString() };
}

test("M1 test 3: verify-discovered blog validate script guards the committed tree", () => {
  expect(validate(example)).toEqual({ code: 0, stderr: "$ mesh build --check\n0 errors, 0 warnings\n" });
});

test("M1 test 3: blog validate script rejects a planted stale tree without writing", () => {
  const dir = mkdtempSync(join(repo, ".m1-blog-guard-"));
  try {
    for (const path of ["mesh.config.ts", "package.json", "resources", "generated"]) {
      cpSync(join(example, path), join(dir, path), { recursive: true });
    }
    symlinkSync(join(example, "node_modules"), join(dir, "node_modules"));
    expect(validate(dir).code).toBe(0);
    const path = join(dir, "generated/blog/post.types.ts");
    const stale = `${readFileSync(path, "utf8")}\n// planted hand edit\n`;
    writeFileSync(path, stale);
    const result = validate(dir);
    expect(result.code).toBe(1);
    expect(result.stderr).toContain("generated/blog/post.types.ts:1:1 error Generated bytes differ; run mesh build and commit the generated tree");
    expect(readFileSync(path, "utf8")).toBe(stale);
  } finally { rmSync(dir, { recursive: true, force: true }); }
});
