// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/execution/attempt.mesh.mx; change that file and rebuild.

import type { Comparison as $Comparison } from "@meshfw/runtime";

import type { Run, RunLoaded } from "./run.types";

import type { Task, TaskLoaded } from "../work/task.types";

import type { Collaborator, CollaboratorLoaded } from "../identity/collaborator.types";

import type { Machine, MachineLoaded } from "./machine.types";

import type { SessionReference, SessionReferenceLoaded } from "./sessionReference.types";

export type Attempt = {
  id: string;
  step: string;
  number: number;
  claimFence: number | null;
  runtime: string | null;
  outcome: unknown;
  state: "running" | "succeeded" | "failed" | "stopped" | "abandoned";
  endedAt: Date | null;
  version: number;
  startedAt: Date;
  runId: string;
  taskId: string;
  performerId: string;
  delegatorId: string;
  machineId: string | null;
  sessionId: string | null;
};

export type StartAttemptInput = {
  step?: string | undefined;
  number: number;
  claimFence?: number | null | undefined;
  runtime?: string | null | undefined;
  run: Run["id"];
  task: Task["id"];
  performer: Collaborator["id"];
  delegator: Collaborator["id"];
  machine?: Machine["id"] | null | undefined;
  session?: SessionReference["id"] | null | undefined;
};

export type ReadAttemptInput = {
  filter?: AttemptFilter | undefined;
  sort?: AttemptSort | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

/** What `load` attaches to a Attempt. The record has none of it, so reading one that was not loaded is a type error. */
export type AttemptLoadable = {
  run: Run;
  task: Task;
  performer: Collaborator;
  delegator: Collaborator;
  machine: Machine | null;
  session: SessionReference | null;
};

/** A Attempt with the relationships and computed fields named in N loaded. */
export type AttemptWith<N extends keyof AttemptLoadable> = Attempt & Pick<AttemptLoadable, N>;

/** A Attempt as the functions of its entity file see it: every relationship and computed field present, and each related record the same. */
export type AttemptLoaded = Attempt & {
  run: RunLoaded;
  task: TaskLoaded;
  performer: CollaboratorLoaded;
  delegator: CollaboratorLoaded;
  machine: MachineLoaded | null;
  session: SessionReferenceLoaded | null;
};

export type AttemptFilter =
  | { and: readonly AttemptFilter[] }
  | { or: readonly AttemptFilter[] }
  | {
      id?: $Comparison<string>;
      step?: $Comparison<string>;
      number?: $Comparison<number>;
      claimFence?: $Comparison<number>;
      runtime?: $Comparison<string>;
      state?: $Comparison<"running" | "succeeded" | "failed" | "stopped" | "abandoned">;
      endedAt?: $Comparison<Date>;
      version?: $Comparison<number>;
      startedAt?: $Comparison<Date>;
      runId?: $Comparison<string>;
      taskId?: $Comparison<string>;
      performerId?: $Comparison<string>;
      delegatorId?: $Comparison<string>;
      machineId?: $Comparison<string>;
      sessionId?: $Comparison<string>;
    };

export type AttemptSort = readonly (
  | "id"
  | "-id"
  | "step"
  | "-step"
  | "number"
  | "-number"
  | "claimFence"
  | "-claimFence"
  | "runtime"
  | "-runtime"
  | "state"
  | "-state"
  | "endedAt"
  | "-endedAt"
  | "version"
  | "-version"
  | "startedAt"
  | "-startedAt"
  | "runId"
  | "-runId"
  | "taskId"
  | "-taskId"
  | "performerId"
  | "-performerId"
  | "delegatorId"
  | "-delegatorId"
  | "machineId"
  | "-machineId"
  | "sessionId"
  | "-sessionId"
)[];
