// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/execution/attempt.mesh.mx; change that file and rebuild.
// Mesh's own imports carry a `$` so that no entity name can shadow them.

import {
  parseInput,
  type ContextArgument as $ContextArgument,
  type DataLayer as $DataLayer,
} from "@meshfw/runtime";
import type { Attempt, StartAttemptInput, ReadAttemptInput } from "./attempt.types";
import { startAttemptInput, readAttemptInput } from "./attempt.validators";
import { tables } from "../schema";

export function bindAttempt(layer: $DataLayer) {
  return Object.freeze({
    async start(input: StartAttemptInput, ...[_context]: $ContextArgument): Promise<Attempt> {
      const parsed = await parseInput(startAttemptInput, input);
      return layer.transaction(async (tx) => {
        const now = new Date();
        const row = await tx.insert(tables.attempt, {
          step: parsed.step === undefined ? "main" : parsed.step,
          number: parsed.number,
          claimFence: parsed.claimFence === undefined ? null : parsed.claimFence,
          runtime: parsed.runtime === undefined ? null : parsed.runtime,
          outcome: null,
          state: "running",
          endedAt: null,
          version: 1,
          startedAt: now,
          runId: parsed.run,
          taskId: parsed.task,
          performerId: parsed.performer,
          delegatorId: parsed.delegator,
          machineId: parsed.machine === undefined ? null : parsed.machine,
          sessionId: parsed.session === undefined ? null : parsed.session,
        });
        return row as Attempt;
      });
    },

    async read(input: ReadAttemptInput, ...[_context]: $ContextArgument): Promise<Attempt[]> {
      const parsed = await parseInput(readAttemptInput, input);
      return layer.transaction(async (tx) => {
        return (await tx.select(tables.attempt, {
          filter: parsed.filter,
          sort: parsed.sort,
          limit: parsed.limit,
          offset: parsed.offset,
        })) as Attempt[];
      });
    },
  });
}
