// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/execution/attempt.mesh.mx; change that file and rebuild.

import { z } from "zod";

import type { StartAttemptInput, ReadAttemptInput, AttemptFilter } from "./attempt.types";

type Keys<T> = T extends Record<string, never> ? never : keyof T;

type SameShape<A, B> = [Keys<A>] extends [Keys<B>]
  ? [Keys<B>] extends [Keys<A>]
    ? [A] extends [B]
      ? [B] extends [A]
        ? true
        : false
      : false
    : false
  : false;

type Assert<T extends true> = T;

const comparison = <T extends z.ZodType>(value: T) =>
  z
    .strictObject({
      eq: value.nullable().exactOptional(),
      ne: value.nullable().exactOptional(),
      lt: value.exactOptional(),
      lte: value.exactOptional(),
      gt: value.exactOptional(),
      gte: value.exactOptional(),
      in: z.array(value).readonly().exactOptional(),
      nil: z.boolean().exactOptional(),
    })
    .refine((operators) => Object.keys(operators).length > 0, {
      message: "a comparison needs an operator",
    });

export const attemptFilter: z.ZodType<AttemptFilter> = z.lazy(
  () =>
    z.union([
      z.strictObject({ and: z.array(attemptFilter).readonly() }),
      z.strictObject({ or: z.array(attemptFilter).readonly() }),
      z.strictObject({
        id: comparison(z.uuid()).exactOptional(),
        step: comparison(z.string()).exactOptional(),
        number: comparison(z.int()).exactOptional(),
        claimFence: comparison(z.int()).exactOptional(),
        runtime: comparison(z.string()).exactOptional(),
        state: comparison(
          z.enum(["running", "succeeded", "failed", "stopped", "abandoned"]),
        ).exactOptional(),
        endedAt: comparison(z.date()).exactOptional(),
        version: comparison(z.int()).exactOptional(),
        startedAt: comparison(z.date()).exactOptional(),
        runId: comparison(z.uuid()).exactOptional(),
        taskId: comparison(z.uuid()).exactOptional(),
        performerId: comparison(z.uuid()).exactOptional(),
        delegatorId: comparison(z.uuid()).exactOptional(),
        machineId: comparison(z.uuid()).exactOptional(),
        sessionId: comparison(z.uuid()).exactOptional(),
      }),
    ]) as unknown as z.ZodType<AttemptFilter>,
);

export const attemptSort = z
  .array(
    z.enum([
      "id",
      "-id",
      "step",
      "-step",
      "number",
      "-number",
      "claimFence",
      "-claimFence",
      "runtime",
      "-runtime",
      "state",
      "-state",
      "endedAt",
      "-endedAt",
      "version",
      "-version",
      "startedAt",
      "-startedAt",
      "runId",
      "-runId",
      "taskId",
      "-taskId",
      "performerId",
      "-performerId",
      "delegatorId",
      "-delegatorId",
      "machineId",
      "-machineId",
      "sessionId",
      "-sessionId",
    ]),
  )
  .readonly();

export const startAttemptInput = z.strictObject({
  step: z.string().optional(),
  number: z.int(),
  claimFence: z.int().nullable().optional(),
  runtime: z.string().nullable().optional(),
  run: z.uuid(),
  task: z.uuid(),
  performer: z.uuid(),
  delegator: z.uuid(),
  machine: z.uuid().nullable().optional(),
  session: z.uuid().nullable().optional(),
}) satisfies z.ZodType<StartAttemptInput>;

export type StartAttemptInputShape = Assert<
  SameShape<z.output<typeof startAttemptInput>, StartAttemptInput>
>;

export const readAttemptInput = z.strictObject({
  filter: attemptFilter.optional(),
  sort: attemptSort.optional(),
  limit: z.int().min(0).optional(),
  offset: z.int().min(0).optional(),
}) satisfies z.ZodType<ReadAttemptInput>;

export type ReadAttemptInputShape = Assert<
  SameShape<z.output<typeof readAttemptInput>, ReadAttemptInput>
>;
