// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/execution/attempt.mesh.mx; change that file and rebuild.
// Mesh's own imports carry a `$` so that no entity name can shadow them.

import {
  parseInput,
  type BindOptions as $BindOptions,
  type ContextArgument as $ContextArgument,
  type DataLayer as $DataLayer,
  type Row as $Row,
} from "@meshfw/runtime";
import type { Attempt, StartAttemptInput, ReadAttemptInput } from "./attempt.types";
import { startAttemptInput, readAttemptInput } from "./attempt.validators";
import { tables } from "../schema";

export function bindAttempt(layer: $DataLayer, _options: $BindOptions = {}) {
  return Object.freeze({
    async start(input: StartAttemptInput, ...[_context]: $ContextArgument): Promise<Attempt> {
      // enter, cast: the call arrives with its context, and only the declared input passes
      const parsed = await parseInput(startAttemptInput, input);
      return layer.transaction(async (tx) => {
        // transaction: opens here; what follows commits together or not at all (pre-check: the authorizer slot before it stays empty until policies, M8)
        const $now = new Date();
        // plan: a create is one insert; nothing is read first
        const $changes: $Row = {
          step: parsed.step === undefined ? "main" : parsed.step,
          number: parsed.number,
          claimFence: parsed.claimFence === undefined ? null : parsed.claimFence,
          runtime: parsed.runtime === undefined ? null : parsed.runtime,
          outcome: null,
          state: "running",
          endedAt: null,
          version: 1,
          startedAt: $now,
          runId: parsed.run,
          taskId: parsed.task,
          performerId: parsed.performer,
          delegatorId: parsed.delegator,
          machineId: parsed.machine === undefined ? null : parsed.machine,
          sessionId: parsed.session === undefined ? null : parsed.session,
        };
        // data layer
        const $stored = await tx.insert(tables.attempt, $changes);
        return $stored as Attempt;
      });
    },

    async read(input: ReadAttemptInput, ...[_context]: $ContextArgument): Promise<Attempt[]> {
      // enter, cast: the call arrives with its context, and only the declared input passes
      const parsed = await parseInput(readAttemptInput, input);
      return layer.transaction(async (tx) => {
        return (await tx.select(tables.attempt, {
          filter: parsed.filter,
          sort: parsed.sort,
          limit: parsed.limit,
          offset: parsed.offset,
        })) as Attempt[];
      });
    },
  });
}
