// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/execution/invocation.mesh.mx; change that file and rebuild.
// Mesh's own imports carry a `$` so that no entity name can shadow them.

import {
  parseInput,
  type BindOptions as $BindOptions,
  type ContextArgument as $ContextArgument,
  type DataLayer as $DataLayer,
  type Row as $Row,
} from "@meshfw/runtime";
import type {
  Invocation,
  RecordInvocationInput,
  CorrectInvocationInput,
  ReadInvocationInput,
} from "./invocation.types";
import {
  recordInvocationInput,
  correctInvocationInput,
  readInvocationInput,
} from "./invocation.validators";
import { tables } from "../schema";

export function bindInvocation(layer: $DataLayer, _options: $BindOptions = {}) {
  return Object.freeze({
    async record(
      input: RecordInvocationInput,
      ...[_context]: $ContextArgument
    ): Promise<Invocation> {
      // enter, cast: the call arrives with its context, and only the declared input passes
      const parsed = await parseInput(recordInvocationInput, input);
      return layer.transaction(async (tx) => {
        // transaction: opens here; what follows commits together or not at all (pre-check: the authorizer slot before it stays empty until policies, M8)
        const $now = new Date();
        // plan: a create is one insert; nothing is read first
        const $changes: $Row = {
          requestedProvider:
            parsed.requestedProvider === undefined ? null : parsed.requestedProvider,
          requestedModel: parsed.requestedModel === undefined ? null : parsed.requestedModel,
          actualProvider: parsed.actualProvider === undefined ? null : parsed.actualProvider,
          actualModel: parsed.actualModel === undefined ? null : parsed.actualModel,
          inputTokens: parsed.inputTokens === undefined ? null : parsed.inputTokens,
          outputTokens: parsed.outputTokens === undefined ? null : parsed.outputTokens,
          cacheReadTokens: parsed.cacheReadTokens === undefined ? null : parsed.cacheReadTokens,
          cacheWriteTokens: parsed.cacheWriteTokens === undefined ? null : parsed.cacheWriteTokens,
          usageSource: parsed.usageSource,
          estimatedCost: parsed.estimatedCost === undefined ? null : parsed.estimatedCost,
          pricingBasis: parsed.pricingBasis === undefined ? null : parsed.pricingBasis,
          startedAt: parsed.startedAt === undefined ? null : parsed.startedAt,
          endedAt: parsed.endedAt === undefined ? null : parsed.endedAt,
          reason: null,
          recordedAt: $now,
          attemptId: parsed.attempt,
          taskId: parsed.task,
          sessionId: parsed.session === undefined ? null : parsed.session,
          correctsId: null,
          recordedById: parsed.recordedBy,
        };
        // data layer
        const $stored = await tx.insert(tables.invocation, $changes);
        return $stored as Invocation;
      });
    },

    async correct(
      input: CorrectInvocationInput,
      ...[_context]: $ContextArgument
    ): Promise<Invocation> {
      // enter, cast: the call arrives with its context, and only the declared input passes
      const parsed = await parseInput(correctInvocationInput, input);
      return layer.transaction(async (tx) => {
        // transaction: opens here; what follows commits together or not at all (pre-check: the authorizer slot before it stays empty until policies, M8)
        const $now = new Date();
        // plan: a create is one insert; nothing is read first
        const $changes: $Row = {
          requestedProvider: null,
          requestedModel: null,
          actualProvider: null,
          actualModel: null,
          inputTokens: null,
          outputTokens: null,
          cacheReadTokens: null,
          cacheWriteTokens: null,
          usageSource: parsed.usageSource,
          estimatedCost: null,
          pricingBasis: null,
          startedAt: null,
          endedAt: null,
          reason: parsed.reason === undefined ? null : parsed.reason,
          recordedAt: $now,
          attemptId: parsed.attempt,
          taskId: parsed.task,
          sessionId: null,
          correctsId: parsed.corrects === undefined ? null : parsed.corrects,
          recordedById: parsed.recordedBy,
        };
        // data layer
        const $stored = await tx.insert(tables.invocation, $changes);
        return $stored as Invocation;
      });
    },

    async read(input: ReadInvocationInput, ...[_context]: $ContextArgument): Promise<Invocation[]> {
      // enter, cast: the call arrives with its context, and only the declared input passes
      const parsed = await parseInput(readInvocationInput, input);
      return layer.transaction(async (tx) => {
        return (await tx.select(tables.invocation, {
          filter: parsed.filter,
          sort: parsed.sort,
          limit: parsed.limit,
          offset: parsed.offset,
        })) as Invocation[];
      });
    },
  });
}
