// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/execution/invocation.mesh.mx; change that file and rebuild.

import { z } from "zod";

import type {
  RecordInvocationInput,
  CorrectInvocationInput,
  ReadInvocationInput,
  InvocationFilter,
} from "./invocation.types";

type Keys<T> = T extends Record<string, never> ? never : keyof T;

type SameShape<A, B> = [Keys<A>] extends [Keys<B>]
  ? [Keys<B>] extends [Keys<A>]
    ? [A] extends [B]
      ? [B] extends [A]
        ? true
        : false
      : false
    : false
  : false;

type Assert<T extends true> = T;

const comparison = <T extends z.ZodType>(value: T) =>
  z
    .strictObject({
      eq: value.nullable().exactOptional(),
      ne: value.nullable().exactOptional(),
      lt: value.exactOptional(),
      lte: value.exactOptional(),
      gt: value.exactOptional(),
      gte: value.exactOptional(),
      in: z.array(value).readonly().exactOptional(),
      nil: z.boolean().exactOptional(),
    })
    .refine((operators) => Object.keys(operators).length > 0, {
      message: "a comparison needs an operator",
    });

export const invocationFilter: z.ZodType<InvocationFilter> = z.lazy(
  () =>
    z.union([
      z.strictObject({ and: z.array(invocationFilter).readonly() }),
      z.strictObject({ or: z.array(invocationFilter).readonly() }),
      z.strictObject({
        id: comparison(z.uuid()).exactOptional(),
        requestedProvider: comparison(z.string()).exactOptional(),
        requestedModel: comparison(z.string()).exactOptional(),
        actualProvider: comparison(z.string()).exactOptional(),
        actualModel: comparison(z.string()).exactOptional(),
        inputTokens: comparison(z.int()).exactOptional(),
        outputTokens: comparison(z.int()).exactOptional(),
        cacheReadTokens: comparison(z.int()).exactOptional(),
        cacheWriteTokens: comparison(z.int()).exactOptional(),
        usageSource: comparison(z.enum(["runtime", "provider", "estimate"])).exactOptional(),
        estimatedCost: comparison(z.number()).exactOptional(),
        pricingBasis: comparison(z.string()).exactOptional(),
        startedAt: comparison(z.date()).exactOptional(),
        endedAt: comparison(z.date()).exactOptional(),
        reason: comparison(z.string()).exactOptional(),
        recordedAt: comparison(z.date()).exactOptional(),
        attemptId: comparison(z.uuid()).exactOptional(),
        taskId: comparison(z.uuid()).exactOptional(),
        sessionId: comparison(z.uuid()).exactOptional(),
        correctsId: comparison(z.uuid()).exactOptional(),
        recordedById: comparison(z.uuid()).exactOptional(),
      }),
    ]) as unknown as z.ZodType<InvocationFilter>,
);

export const invocationSort = z
  .array(
    z.enum([
      "id",
      "-id",
      "requestedProvider",
      "-requestedProvider",
      "requestedModel",
      "-requestedModel",
      "actualProvider",
      "-actualProvider",
      "actualModel",
      "-actualModel",
      "inputTokens",
      "-inputTokens",
      "outputTokens",
      "-outputTokens",
      "cacheReadTokens",
      "-cacheReadTokens",
      "cacheWriteTokens",
      "-cacheWriteTokens",
      "usageSource",
      "-usageSource",
      "estimatedCost",
      "-estimatedCost",
      "pricingBasis",
      "-pricingBasis",
      "startedAt",
      "-startedAt",
      "endedAt",
      "-endedAt",
      "reason",
      "-reason",
      "recordedAt",
      "-recordedAt",
      "attemptId",
      "-attemptId",
      "taskId",
      "-taskId",
      "sessionId",
      "-sessionId",
      "correctsId",
      "-correctsId",
      "recordedById",
      "-recordedById",
    ]),
  )
  .readonly();

export const recordInvocationInput = z.strictObject({
  requestedProvider: z.string().nullable().optional(),
  requestedModel: z.string().nullable().optional(),
  actualProvider: z.string().nullable().optional(),
  actualModel: z.string().nullable().optional(),
  inputTokens: z.int().min(0).nullable().optional(),
  outputTokens: z.int().min(0).nullable().optional(),
  cacheReadTokens: z.int().min(0).nullable().optional(),
  cacheWriteTokens: z.int().min(0).nullable().optional(),
  usageSource: z.enum(["runtime", "provider", "estimate"]),
  estimatedCost: z.number().nullable().optional(),
  pricingBasis: z.string().nullable().optional(),
  startedAt: z.date().nullable().optional(),
  endedAt: z.date().nullable().optional(),
  attempt: z.uuid(),
  task: z.uuid(),
  session: z.uuid().nullable().optional(),
  recordedBy: z.uuid(),
}) satisfies z.ZodType<RecordInvocationInput>;

export type RecordInvocationInputShape = Assert<
  SameShape<z.output<typeof recordInvocationInput>, RecordInvocationInput>
>;

export const correctInvocationInput = z.strictObject({
  reason: z.string().nullable().optional(),
  usageSource: z.enum(["runtime", "provider", "estimate"]),
  attempt: z.uuid(),
  task: z.uuid(),
  corrects: z.uuid().nullable().optional(),
  recordedBy: z.uuid(),
}) satisfies z.ZodType<CorrectInvocationInput>;

export type CorrectInvocationInputShape = Assert<
  SameShape<z.output<typeof correctInvocationInput>, CorrectInvocationInput>
>;

export const readInvocationInput = z.strictObject({
  filter: invocationFilter.optional(),
  sort: invocationSort.optional(),
  limit: z.int().min(0).optional(),
  offset: z.int().min(0).optional(),
}) satisfies z.ZodType<ReadInvocationInput>;

export type ReadInvocationInputShape = Assert<
  SameShape<z.output<typeof readInvocationInput>, ReadInvocationInput>
>;
