// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/execution/invocation.mesh.mx; change that file and rebuild.

import type { Comparison as $Comparison } from "@meshfw/runtime";

import type { Attempt, AttemptLoaded } from "./attempt.types";

import type { Task, TaskLoaded } from "../work/task.types";

import type { SessionReference, SessionReferenceLoaded } from "./sessionReference.types";

import type { Collaborator, CollaboratorLoaded } from "../identity/collaborator.types";

export type Invocation = {
  id: string;
  requestedProvider: string | null;
  requestedModel: string | null;
  actualProvider: string | null;
  actualModel: string | null;
  inputTokens: number | null;
  outputTokens: number | null;
  cacheReadTokens: number | null;
  cacheWriteTokens: number | null;
  usageSource: "runtime" | "provider" | "estimate";
  estimatedCost: number | null;
  pricingBasis: string | null;
  startedAt: Date | null;
  endedAt: Date | null;
  reason: string | null;
  recordedAt: Date;
  attemptId: string;
  taskId: string;
  sessionId: string | null;
  correctsId: string | null;
  recordedById: string;
};

export type RecordInvocationInput = {
  requestedProvider?: string | null | undefined;
  requestedModel?: string | null | undefined;
  actualProvider?: string | null | undefined;
  actualModel?: string | null | undefined;
  inputTokens?: number | null | undefined;
  outputTokens?: number | null | undefined;
  cacheReadTokens?: number | null | undefined;
  cacheWriteTokens?: number | null | undefined;
  usageSource: "runtime" | "provider" | "estimate";
  estimatedCost?: number | null | undefined;
  pricingBasis?: string | null | undefined;
  startedAt?: Date | null | undefined;
  endedAt?: Date | null | undefined;
  attempt: Attempt["id"];
  task: Task["id"];
  session?: SessionReference["id"] | null | undefined;
  recordedBy: Collaborator["id"];
};

export type CorrectInvocationInput = {
  reason?: string | null | undefined;
  usageSource: "runtime" | "provider" | "estimate";
  attempt: Attempt["id"];
  task: Task["id"];
  corrects?: Invocation["id"] | null | undefined;
  recordedBy: Collaborator["id"];
};

export type ReadInvocationInput = {
  filter?: InvocationFilter | undefined;
  sort?: InvocationSort | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

/** What `load` attaches to a Invocation. The record has none of it, so reading one that was not loaded is a type error. */
export type InvocationLoadable = {
  attempt: Attempt;
  task: Task;
  session: SessionReference | null;
  corrects: Invocation | null;
  recordedBy: Collaborator;
};

/** A Invocation with the relationships and computed fields named in N loaded. */
export type InvocationWith<N extends keyof InvocationLoadable> = Invocation &
  Pick<InvocationLoadable, N>;

/** A Invocation as the functions of its entity file see it: every relationship and computed field present, and each related record the same. */
export type InvocationLoaded = Invocation & {
  attempt: AttemptLoaded;
  task: TaskLoaded;
  session: SessionReferenceLoaded | null;
  corrects: InvocationLoaded | null;
  recordedBy: CollaboratorLoaded;
};

export type InvocationFilter =
  | { and: readonly InvocationFilter[] }
  | { or: readonly InvocationFilter[] }
  | {
      id?: $Comparison<string>;
      requestedProvider?: $Comparison<string>;
      requestedModel?: $Comparison<string>;
      actualProvider?: $Comparison<string>;
      actualModel?: $Comparison<string>;
      inputTokens?: $Comparison<number>;
      outputTokens?: $Comparison<number>;
      cacheReadTokens?: $Comparison<number>;
      cacheWriteTokens?: $Comparison<number>;
      usageSource?: $Comparison<"runtime" | "provider" | "estimate">;
      estimatedCost?: $Comparison<number>;
      pricingBasis?: $Comparison<string>;
      startedAt?: $Comparison<Date>;
      endedAt?: $Comparison<Date>;
      reason?: $Comparison<string>;
      recordedAt?: $Comparison<Date>;
      attemptId?: $Comparison<string>;
      taskId?: $Comparison<string>;
      sessionId?: $Comparison<string>;
      correctsId?: $Comparison<string>;
      recordedById?: $Comparison<string>;
    };

export type InvocationSort = readonly (
  | "id"
  | "-id"
  | "requestedProvider"
  | "-requestedProvider"
  | "requestedModel"
  | "-requestedModel"
  | "actualProvider"
  | "-actualProvider"
  | "actualModel"
  | "-actualModel"
  | "inputTokens"
  | "-inputTokens"
  | "outputTokens"
  | "-outputTokens"
  | "cacheReadTokens"
  | "-cacheReadTokens"
  | "cacheWriteTokens"
  | "-cacheWriteTokens"
  | "usageSource"
  | "-usageSource"
  | "estimatedCost"
  | "-estimatedCost"
  | "pricingBasis"
  | "-pricingBasis"
  | "startedAt"
  | "-startedAt"
  | "endedAt"
  | "-endedAt"
  | "reason"
  | "-reason"
  | "recordedAt"
  | "-recordedAt"
  | "attemptId"
  | "-attemptId"
  | "taskId"
  | "-taskId"
  | "sessionId"
  | "-sessionId"
  | "correctsId"
  | "-correctsId"
  | "recordedById"
  | "-recordedById"
)[];
