// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/execution/machine.mesh.mx; change that file and rebuild.

import type { Comparison as $Comparison } from "@meshfw/runtime";

import type { Collaborator } from "../identity/collaborator.types";

import type { Attempt } from "./attempt.types";

export type Machine = {
  id: string;
  name: string;
  platform: string | null;
  state: "active" | "retired";
  version: number;
  registeredAt: Date;
  firstReportedById: string | null;
};

export type RegisterMachineInput = {
  name: string;
  platform?: string | null | undefined;
  firstReportedBy?: Collaborator["id"] | null | undefined;
};

export type UpdateMachineInput = {
  id: string;
  platform?: string | null | undefined;
  expectedVersion?: number | null | undefined;
};

export type ReadMachineInput = {
  filter?: MachineFilter | undefined;
  sort?: MachineSort | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

/** What `load` attaches to a Machine. The record has none of it, so reading one that was not loaded is a type error. */
export type MachineLoadable = {
  firstReportedBy: Collaborator | null;
  attempts: Attempt[];
};

/** A Machine with the relationships and computed fields named in N loaded. */
export type MachineWith<N extends keyof MachineLoadable> = Machine & Pick<MachineLoadable, N>;

export type MachineFilter =
  | { and: readonly MachineFilter[] }
  | { or: readonly MachineFilter[] }
  | {
      id?: $Comparison<string>;
      name?: $Comparison<string>;
      platform?: $Comparison<string>;
      state?: $Comparison<"active" | "retired">;
      version?: $Comparison<number>;
      registeredAt?: $Comparison<Date>;
      firstReportedById?: $Comparison<string>;
    };

export type MachineSort = readonly (
  | "id"
  | "-id"
  | "name"
  | "-name"
  | "platform"
  | "-platform"
  | "state"
  | "-state"
  | "version"
  | "-version"
  | "registeredAt"
  | "-registeredAt"
  | "firstReportedById"
  | "-firstReportedById"
)[];
