// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/execution/machine.mesh.mx; change that file and rebuild.

import { expr as $, type Scope as $Scope } from "@meshfw/runtime";
import type { Machine } from "./machine.types";

/** What every expression of Machine reads. */
export type MachineScope = $Scope<{
  self: Machine & { firstReportedBy: any; attempts: any[] };
  input: any;
  actor: any;
  context: any;
  before: Machine | null;
  tx: any;
}>;
/** What the expressions that only run on a stored record (an update or a destroy) read: `before` is the stored record. */
export type MachineStoredScope = MachineScope & { before: Machine };

export const expressions = {
  // check :machineActive that, translated (src/domain/execution/machine.mesh.mx:27:16)
  "update.check.machineActive.that": ($s: MachineStoredScope) => $.eq($s.self.state, "active"),
  // check :versionMatches that, translated (src/domain/execution/machine.mesh.mx:32:16)
  "update.check.versionMatches.that": ($s: MachineStoredScope) =>
    $.or($.isNull($s.input?.expectedVersion), $.eq($s.input?.expectedVersion, $s.self.version)),
  // check :versionMatches details, plain (unsupported-construct) (src/domain/execution/machine.mesh.mx:35:19)
  "update.check.versionMatches.details": ($s: MachineStoredScope) => {
    return (({ input, before }) => ({
      expectedVersion: input.expectedVersion,
      actualVersion: before.version,
    }))($s);
  },
  // set &version, translated (src/domain/execution/machine.mesh.mx:39:20)
  "update.step.0.set.version": ($s: MachineStoredScope) => $.add($s.self.version, 1),
} as const;
