// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/execution/machine.mesh.mx; change that file and rebuild.

import { z } from "zod";

import type {
  RegisterMachineInput,
  UpdateMachineInput,
  ReadMachineInput,
  MachineFilter,
} from "./machine.types";

type Keys<T> = T extends Record<string, never> ? never : keyof T;

type SameShape<A, B> = [Keys<A>] extends [Keys<B>]
  ? [Keys<B>] extends [Keys<A>]
    ? [A] extends [B]
      ? [B] extends [A]
        ? true
        : false
      : false
    : false
  : false;

type Assert<T extends true> = T;

const comparison = <T extends z.ZodType>(value: T) =>
  z
    .strictObject({
      eq: value.nullable().exactOptional(),
      ne: value.nullable().exactOptional(),
      lt: value.exactOptional(),
      lte: value.exactOptional(),
      gt: value.exactOptional(),
      gte: value.exactOptional(),
      in: z.array(value).readonly().exactOptional(),
      nil: z.boolean().exactOptional(),
    })
    .refine((operators) => Object.keys(operators).length > 0, {
      message: "a comparison needs an operator",
    });

export const machineFilter: z.ZodType<MachineFilter> = z.lazy(
  () =>
    z.union([
      z.strictObject({ and: z.array(machineFilter).readonly() }),
      z.strictObject({ or: z.array(machineFilter).readonly() }),
      z.strictObject({
        id: comparison(z.uuid()).exactOptional(),
        name: comparison(z.string()).exactOptional(),
        platform: comparison(z.string()).exactOptional(),
        state: comparison(z.enum(["active", "retired"])).exactOptional(),
        version: comparison(z.int()).exactOptional(),
        registeredAt: comparison(z.date()).exactOptional(),
        firstReportedById: comparison(z.uuid()).exactOptional(),
      }),
    ]) as unknown as z.ZodType<MachineFilter>,
);

export const machineSort = z
  .array(
    z.enum([
      "id",
      "-id",
      "name",
      "-name",
      "platform",
      "-platform",
      "state",
      "-state",
      "version",
      "-version",
      "registeredAt",
      "-registeredAt",
      "firstReportedById",
      "-firstReportedById",
    ]),
  )
  .readonly();

export const registerMachineInput = z.strictObject({
  name: z.string(),
  platform: z.string().nullable().optional(),
  firstReportedBy: z.uuid().nullable().optional(),
}) satisfies z.ZodType<RegisterMachineInput>;

export type RegisterMachineInputShape = Assert<
  SameShape<z.output<typeof registerMachineInput>, RegisterMachineInput>
>;

export const updateMachineInput = z.strictObject({
  id: z.uuid(),
  platform: z.string().nullable().optional(),
}) satisfies z.ZodType<UpdateMachineInput>;

export type UpdateMachineInputShape = Assert<
  SameShape<z.output<typeof updateMachineInput>, UpdateMachineInput>
>;

export const readMachineInput = z.strictObject({
  filter: machineFilter.optional(),
  sort: machineSort.optional(),
  limit: z.int().min(0).optional(),
  offset: z.int().min(0).optional(),
}) satisfies z.ZodType<ReadMachineInput>;

export type ReadMachineInputShape = Assert<
  SameShape<z.output<typeof readMachineInput>, ReadMachineInput>
>;
