// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/execution/machine.mesh.mx; change that file and rebuild.
// Mesh's own imports carry a `$` so that no entity name can shadow them.

import {
  NotFoundError as $NotFoundError,
  parseInput,
  type ContextArgument as $ContextArgument,
  type DataLayer as $DataLayer,
} from "@meshfw/runtime";
import type {
  Machine,
  RegisterMachineInput,
  UpdateMachineInput,
  ReadMachineInput,
} from "./machine.types";
import { registerMachineInput, updateMachineInput, readMachineInput } from "./machine.validators";
import { tables } from "../schema";

export function bindMachine(layer: $DataLayer) {
  return Object.freeze({
    async register(input: RegisterMachineInput, ...[_context]: $ContextArgument): Promise<Machine> {
      const parsed = await parseInput(registerMachineInput, input);
      return layer.transaction(async (tx) => {
        const now = new Date();
        const row = await tx.insert(tables.machine, {
          name: parsed.name,
          platform: parsed.platform === undefined ? null : parsed.platform,
          state: "active",
          version: 1,
          registeredAt: now,
          firstReportedById: parsed.firstReportedBy === undefined ? null : parsed.firstReportedBy,
        });
        return row as Machine;
      });
    },

    async update(input: UpdateMachineInput, ...[_context]: $ContextArgument): Promise<Machine> {
      const parsed = await parseInput(updateMachineInput, input);
      return layer.transaction(async (tx) => {
        const key = { id: parsed.id };
        const changes: Partial<Machine> = {};
        if (parsed.platform !== undefined) changes.platform = parsed.platform;
        const row = await tx.updateByKey(tables.machine, key, changes);
        if (row === undefined) throw new $NotFoundError("Machine", key);
        return row as Machine;
      });
    },

    async read(input: ReadMachineInput, ...[_context]: $ContextArgument): Promise<Machine[]> {
      const parsed = await parseInput(readMachineInput, input);
      return layer.transaction(async (tx) => {
        return (await tx.select(tables.machine, {
          filter: parsed.filter,
          sort: parsed.sort,
          limit: parsed.limit,
          offset: parsed.offset,
        })) as Machine[];
      });
    },
  });
}
