// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/execution/run.mesh.mx; change that file and rebuild.

import { z } from "zod";

import type { StartRunInput, ReadRunInput, RunFilter } from "./run.types";

type Keys<T> = T extends Record<string, never> ? never : keyof T;

type SameShape<A, B> = [Keys<A>] extends [Keys<B>]
  ? [Keys<B>] extends [Keys<A>]
    ? [A] extends [B]
      ? [B] extends [A]
        ? true
        : false
      : false
    : false
  : false;

type Assert<T extends true> = T;

const comparison = <T extends z.ZodType>(value: T) =>
  z
    .strictObject({
      eq: value.nullable().exactOptional(),
      ne: value.nullable().exactOptional(),
      lt: value.exactOptional(),
      lte: value.exactOptional(),
      gt: value.exactOptional(),
      gte: value.exactOptional(),
      in: z.array(value).readonly().exactOptional(),
      nil: z.boolean().exactOptional(),
    })
    .refine((operators) => Object.keys(operators).length > 0, {
      message: "a comparison needs an operator",
    });

export const runFilter: z.ZodType<RunFilter> = z.lazy(
  () =>
    z.union([
      z.strictObject({ and: z.array(runFilter).readonly() }),
      z.strictObject({ or: z.array(runFilter).readonly() }),
      z.strictObject({
        id: comparison(z.uuid()).exactOptional(),
        state: comparison(z.enum(["running", "succeeded", "failed", "canceled"])).exactOptional(),
        cancelReason: comparison(z.string()).exactOptional(),
        endedAt: comparison(z.date()).exactOptional(),
        version: comparison(z.int()).exactOptional(),
        startedAt: comparison(z.date()).exactOptional(),
        taskId: comparison(z.string()).exactOptional(),
        responsibleId: comparison(z.string()).exactOptional(),
        startedById: comparison(z.string()).exactOptional(),
        parentRunId: comparison(z.string()).exactOptional(),
      }),
    ]) as unknown as z.ZodType<RunFilter>,
);

export const runSort = z
  .array(
    z.enum([
      "id",
      "-id",
      "state",
      "-state",
      "cancelReason",
      "-cancelReason",
      "endedAt",
      "-endedAt",
      "version",
      "-version",
      "startedAt",
      "-startedAt",
      "taskId",
      "-taskId",
      "responsibleId",
      "-responsibleId",
      "startedById",
      "-startedById",
      "parentRunId",
      "-parentRunId",
    ]),
  )
  .readonly();

export const startRunInput = z.strictObject({
  inputs: (
    z
      .json()
      .refine((value) => value !== null, {
        message: "null is only allowed on a nullable attribute",
      }) as z.ZodType<unknown>
  ).optional(),
  task: z.uuid(),
  responsible: z.uuid(),
  startedBy: z.uuid(),
  parentRun: z.uuid().nullable().optional(),
}) satisfies z.ZodType<StartRunInput>;

export type StartRunInputShape = Assert<SameShape<z.output<typeof startRunInput>, StartRunInput>>;

export const readRunInput = z.strictObject({
  filter: runFilter.optional(),
  sort: runSort.optional(),
  limit: z.int().min(0).optional(),
  offset: z.int().min(0).optional(),
}) satisfies z.ZodType<ReadRunInput>;

export type ReadRunInputShape = Assert<SameShape<z.output<typeof readRunInput>, ReadRunInput>>;
