// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/execution/session-reference.mesh.mx; change that file and rebuild.

import { z } from "zod";

import type {
  RecordSessionReferenceInput,
  SetAvailabilitySessionReferenceInput,
  ReadSessionReferenceInput,
  SessionReferenceFilter,
} from "./sessionReference.types";

type Keys<T> = T extends Record<string, never> ? never : keyof T;

type SameShape<A, B> = [Keys<A>] extends [Keys<B>]
  ? [Keys<B>] extends [Keys<A>]
    ? [A] extends [B]
      ? [B] extends [A]
        ? true
        : false
      : false
    : false
  : false;

type Assert<T extends true> = T;

const comparison = <T extends z.ZodType>(value: T) =>
  z.strictObject({
    eq: value.nullable().optional(),
    ne: value.nullable().optional(),
    lt: value.optional(),
    lte: value.optional(),
    gt: value.optional(),
    gte: value.optional(),
    in: z.array(value).readonly().optional(),
    nil: z.boolean().optional(),
  });

// The cast is the schema's only gap: zod writes an absent key as `?: T | undefined`, which the
// strictest `exactOptionalPropertyTypes` setting does not let the filter type accept.
export const sessionReferenceFilter: z.ZodType<SessionReferenceFilter> = z.lazy(
  () =>
    z.union([
      z.strictObject({ and: z.array(sessionReferenceFilter).readonly() }),
      z.strictObject({ or: z.array(sessionReferenceFilter).readonly() }),
      z.strictObject({
        id: comparison(z.uuid()).optional(),
        runtime: comparison(z.string()).optional(),
        runtimeSessionId: comparison(z.string()).optional(),
        availability: comparison(
          z.enum(["complete", "partial", "unavailable", "redacted"]),
        ).optional(),
        location: comparison(z.string()).optional(),
        version: comparison(z.int()).optional(),
        recordedAt: comparison(z.date()).optional(),
        machineId: comparison(z.string()).optional(),
        agentProfileId: comparison(z.string()).optional(),
        recordedById: comparison(z.string()).optional(),
      }),
    ]) as unknown as z.ZodType<SessionReferenceFilter>,
);

export const sessionReferenceSort = z
  .array(
    z.enum([
      "id",
      "-id",
      "runtime",
      "-runtime",
      "runtimeSessionId",
      "-runtimeSessionId",
      "availability",
      "-availability",
      "location",
      "-location",
      "version",
      "-version",
      "recordedAt",
      "-recordedAt",
      "machineId",
      "-machineId",
      "agentProfileId",
      "-agentProfileId",
      "recordedById",
      "-recordedById",
    ]),
  )
  .readonly();

export const recordSessionReferenceInput = z.strictObject({
  runtime: z.string(),
  runtimeSessionId: z.string(),
  availability: z.enum(["complete", "partial", "unavailable", "redacted"]),
  location: z.string().nullable().optional(),
  machine: z.uuid(),
  agentProfile: z.uuid(),
  recordedBy: z.uuid(),
}) satisfies z.ZodType<RecordSessionReferenceInput>;

export type RecordSessionReferenceInputShape = Assert<
  SameShape<z.output<typeof recordSessionReferenceInput>, RecordSessionReferenceInput>
>;

export const setAvailabilitySessionReferenceInput = z.strictObject({
  id: z.uuid(),
  availability: z.enum(["complete", "partial", "unavailable", "redacted"]).optional(),
}) satisfies z.ZodType<SetAvailabilitySessionReferenceInput>;

export type SetAvailabilitySessionReferenceInputShape = Assert<
  SameShape<
    z.output<typeof setAvailabilitySessionReferenceInput>,
    SetAvailabilitySessionReferenceInput
  >
>;

export const readSessionReferenceInput = z.strictObject({
  filter: sessionReferenceFilter.optional(),
  sort: sessionReferenceSort.optional(),
  limit: z.int().min(0).optional(),
  offset: z.int().min(0).optional(),
}) satisfies z.ZodType<ReadSessionReferenceInput>;

export type ReadSessionReferenceInputShape = Assert<
  SameShape<z.output<typeof readSessionReferenceInput>, ReadSessionReferenceInput>
>;
