// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/execution/session-reference.mesh.mx; change that file and rebuild.

import type { Comparison as $Comparison } from "@meshfw/runtime";

import type { Machine } from "./machine.types";

import type { Collaborator } from "../identity/collaborator.types";

export type SessionReference = {
  id: string;
  runtime: string;
  runtimeSessionId: string;
  availability: "complete" | "partial" | "unavailable" | "redacted";
  location: string | null;
  version: number;
  recordedAt: Date;
  machineId: string;
  agentProfileId: string;
  recordedById: string;
};

export type RecordSessionReferenceInput = {
  runtime: string;
  runtimeSessionId: string;
  availability: "complete" | "partial" | "unavailable" | "redacted";
  location?: string | null | undefined;
  machine: Machine["id"];
  agentProfile: Collaborator["id"];
  recordedBy: Collaborator["id"];
};

export type SetAvailabilitySessionReferenceInput = {
  id: string;
  availability?: "complete" | "partial" | "unavailable" | "redacted" | undefined;
};

export type ReadSessionReferenceInput = {
  filter?: SessionReferenceFilter | undefined;
  sort?: SessionReferenceSort | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

export type SessionReferenceFilter =
  | { and: readonly SessionReferenceFilter[] }
  | { or: readonly SessionReferenceFilter[] }
  | {
      id?: $Comparison<string>;
      runtime?: $Comparison<string>;
      runtimeSessionId?: $Comparison<string>;
      availability?: $Comparison<"complete" | "partial" | "unavailable" | "redacted">;
      location?: $Comparison<string>;
      version?: $Comparison<number>;
      recordedAt?: $Comparison<Date>;
      machineId?: $Comparison<string>;
      agentProfileId?: $Comparison<string>;
      recordedById?: $Comparison<string>;
    };

export type SessionReferenceSort = readonly (
  | "id"
  | "-id"
  | "runtime"
  | "-runtime"
  | "runtimeSessionId"
  | "-runtimeSessionId"
  | "availability"
  | "-availability"
  | "location"
  | "-location"
  | "version"
  | "-version"
  | "recordedAt"
  | "-recordedAt"
  | "machineId"
  | "-machineId"
  | "agentProfileId"
  | "-agentProfileId"
  | "recordedById"
  | "-recordedById"
)[];
