import { lstat, readdir, readFile } from "node:fs/promises";
import { join, relative, sep } from "node:path";
import type { GeneratedFile, ResolvedConfig } from "@mesh/compiler";
import type { Diagnostic } from "@mesh/model";
import { diagnostic, sortDiagnostics } from "./diagnostics.ts";

export const projectPath = (root: string, path: string): string => relative(root, path).split(sep).join("/");
const errorCode = (cause: unknown): string =>
  typeof cause === "object" && cause !== null && "code" in cause ? String(cause.code) : "UNKNOWN";

/** Inspect the output tree with lstat. Never descend into or read a symlink.
 * Missing descendants of a blocked path are not separately diagnosed: fixing
 * the named symlink/non-directory is required before those paths can be checked.
 * Like the writer, this assumes no concurrent filesystem mutation during a build.
 */
export async function checkGeneratedFiles(
  files: readonly GeneratedFile[], config: ResolvedConfig, compareContents = true,
): Promise<Diagnostic[]> {
  const diagnostics: Diagnostic[] = [];
  const expected = new Map(files.map((file) => [file.path, file]));
  const seen = new Set<string>();
  const blocked: string[] = [];
  const fail = (path: string, message: string) => diagnostics.push(diagnostic(path, message));
  const walk = async (absolute: string): Promise<void> => {
    const path = projectPath(config.root, absolute);
    let info;
    try { info = await lstat(absolute); }
    catch (cause) {
      if (errorCode(cause) === "ENOENT") return;
      blocked.push(path);
      fail(path, `Cannot inspect generated path (${errorCode(cause)}); fix its permissions and rebuild`);
      return;
    }
    seen.add(path);
    if (info.isSymbolicLink()) {
      blocked.push(path);
      fail(path, "Symlink in the output tree; delete or move it and rebuild using real files and directories");
    } else if (info.isDirectory()) {
      if (expected.has(path)) fail(path, "Expected a generated file, found a directory; delete or move it and rebuild");
      let names;
      try { names = await readdir(absolute); }
      catch (cause) {
        blocked.push(path);
        fail(path, `Cannot list generated directory (${errorCode(cause)}); fix its permissions and rebuild`);
        return;
      }
      for (const name of names.sort()) await walk(join(absolute, name));
    } else if (info.isFile()) {
      const file = expected.get(path);
      if (!file) fail(path, "File is not produced by the build; delete or move it out of the output directory");
      else if (compareContents) {
        try {
          if (!(await readFile(absolute)).equals(Buffer.from(file.contents, "utf8"))) {
            fail(path, "Generated bytes differ; run mesh build and commit the generated tree");
          }
        } catch (cause) {
          fail(path, `Cannot read generated file (${errorCode(cause)}); fix its permissions and rebuild`);
        }
      }
      // A regular file may obstruct a directory required by an expected path.
      blocked.push(path);
    } else {
      blocked.push(path);
      fail(path, "Unsupported filesystem entry in the output tree; delete or move it and rebuild");
    }
  };
  await walk(config.output);
  if (compareContents) for (const path of expected.keys()) {
    if (!seen.has(path) && !blocked.some((prefix) => path === prefix || path.startsWith(`${prefix}/`))) {
      fail(path, "Generated file is missing; run mesh build and commit the generated tree");
    }
  }
  return sortDiagnostics(diagnostics);
}
