// Do not edit this file by hand.
// It is generated by `mesh build` from the entity files; change them and rebuild.
// The types of `actions` and `tx`, which the functions of an entity file and an application's `transaction` callback receive.

import type { ActionContext as $ActionContext } from "@meshfw/runtime";
import type { Event, RecordEventInput, ReadEventInput } from "./audit/event.types";
import type { Attempt, StartAttemptInput, ReadAttemptInput } from "./execution/attempt.types";
import type {
  Invocation,
  RecordInvocationInput,
  CorrectInvocationInput,
  ReadInvocationInput,
} from "./execution/invocation.types";
import type {
  Machine,
  RegisterMachineInput,
  UpdateMachineInput,
  ReadMachineInput,
} from "./execution/machine.types";
import type { Run, StartRunInput, ReadRunInput } from "./execution/run.types";
import type {
  SessionReference,
  RecordSessionReferenceInput,
  SetAvailabilitySessionReferenceInput,
  RedactSessionReferenceInput,
  ReadSessionReferenceInput,
} from "./execution/sessionReference.types";
import type {
  Collaborator,
  RegisterCollaboratorInput,
  UpdateCollaboratorInput,
  ReadCollaboratorInput,
} from "./identity/collaborator.types";
import type {
  Membership,
  GrantMembershipInput,
  ChangeRoleMembershipInput,
  ReadMembershipInput,
} from "./identity/membership.types";
import type {
  Workspace,
  CreateWorkspaceInput,
  RenameWorkspaceInput,
  ReadWorkspaceInput,
} from "./identity/workspace.types";
import type {
  Assignment,
  StartAssignmentInput,
  ReadAssignmentInput,
} from "./work/assignment.types";
import type {
  Claim,
  AcquireClaimInput,
  RenewClaimInput,
  ReleaseClaimInput,
  RevokeClaimInput,
  ReadClaimInput,
} from "./work/claim.types";
import type {
  Completion,
  RecordCompletionInput,
  ReadCompletionInput,
} from "./work/completion.types";
import type {
  Dependency,
  AddDependencyInput,
  RemoveDependencyInput,
  ReadDependencyInput,
} from "./work/dependency.types";
import type {
  EvidenceReference,
  RecordEvidenceReferenceInput,
  ReadEvidenceReferenceInput,
} from "./work/evidenceReference.types";
import type {
  LateResult,
  RecordLateResultInput,
  ReadLateResultInput,
} from "./work/lateResult.types";
import type {
  Review,
  AcceptReviewInput,
  ReturnReviewInput,
  ReadReviewInput,
} from "./work/review.types";
import type {
  Submission,
  SubmitSubmissionInput,
  ReadSubmissionInput,
} from "./work/submission.types";
import type {
  Task,
  CreateTaskInput,
  UpdateTaskInput,
  SetPriorityTaskInput,
  MoveTaskInput,
  ReopenTaskInput,
  ReadTaskInput,
} from "./work/task.types";

/** Every action function of the project, bound to the running transaction: a call joins it, and carries the caller's context unless it passes its own. */
export interface Actions {
  readonly recordEvent: (input: RecordEventInput, context?: $ActionContext) => Promise<Event>;
  readonly readEvent: (input: ReadEventInput, context?: $ActionContext) => Promise<Event[]>;
  readonly startAttempt: (input: StartAttemptInput, context?: $ActionContext) => Promise<Attempt>;
  readonly readAttempt: (input: ReadAttemptInput, context?: $ActionContext) => Promise<Attempt[]>;
  readonly recordInvocation: (
    input: RecordInvocationInput,
    context?: $ActionContext,
  ) => Promise<Invocation>;
  readonly correctInvocation: (
    input: CorrectInvocationInput,
    context?: $ActionContext,
  ) => Promise<Invocation>;
  readonly readInvocation: (
    input: ReadInvocationInput,
    context?: $ActionContext,
  ) => Promise<Invocation[]>;
  readonly registerMachine: (
    input: RegisterMachineInput,
    context?: $ActionContext,
  ) => Promise<Machine>;
  readonly updateMachine: (input: UpdateMachineInput, context?: $ActionContext) => Promise<Machine>;
  readonly readMachine: (input: ReadMachineInput, context?: $ActionContext) => Promise<Machine[]>;
  readonly startRun: (input: StartRunInput, context?: $ActionContext) => Promise<Run>;
  readonly readRun: (input: ReadRunInput, context?: $ActionContext) => Promise<Run[]>;
  readonly recordSessionReference: (
    input: RecordSessionReferenceInput,
    context?: $ActionContext,
  ) => Promise<SessionReference>;
  readonly setAvailabilitySessionReference: (
    input: SetAvailabilitySessionReferenceInput,
    context?: $ActionContext,
  ) => Promise<SessionReference>;
  readonly redactSessionReference: (
    input: RedactSessionReferenceInput,
    context?: $ActionContext,
  ) => Promise<SessionReference>;
  readonly readSessionReference: (
    input: ReadSessionReferenceInput,
    context?: $ActionContext,
  ) => Promise<SessionReference[]>;
  readonly registerCollaborator: (
    input: RegisterCollaboratorInput,
    context?: $ActionContext,
  ) => Promise<Collaborator>;
  readonly updateCollaborator: (
    input: UpdateCollaboratorInput,
    context?: $ActionContext,
  ) => Promise<Collaborator>;
  readonly readCollaborator: (
    input: ReadCollaboratorInput,
    context?: $ActionContext,
  ) => Promise<Collaborator[]>;
  readonly grantMembership: (
    input: GrantMembershipInput,
    context?: $ActionContext,
  ) => Promise<Membership>;
  readonly changeRoleMembership: (
    input: ChangeRoleMembershipInput,
    context?: $ActionContext,
  ) => Promise<Membership>;
  readonly readMembership: (
    input: ReadMembershipInput,
    context?: $ActionContext,
  ) => Promise<Membership[]>;
  readonly createWorkspace: (
    input: CreateWorkspaceInput,
    context?: $ActionContext,
  ) => Promise<Workspace>;
  readonly renameWorkspace: (
    input: RenameWorkspaceInput,
    context?: $ActionContext,
  ) => Promise<Workspace>;
  readonly readWorkspace: (
    input: ReadWorkspaceInput,
    context?: $ActionContext,
  ) => Promise<Workspace[]>;
  readonly startAssignment: (
    input: StartAssignmentInput,
    context?: $ActionContext,
  ) => Promise<Assignment>;
  readonly readAssignment: (
    input: ReadAssignmentInput,
    context?: $ActionContext,
  ) => Promise<Assignment[]>;
  readonly acquireClaim: (input: AcquireClaimInput, context?: $ActionContext) => Promise<Claim>;
  readonly renewClaim: (input: RenewClaimInput, context?: $ActionContext) => Promise<Claim>;
  readonly releaseClaim: (input: ReleaseClaimInput, context?: $ActionContext) => Promise<Claim>;
  readonly revokeClaim: (input: RevokeClaimInput, context?: $ActionContext) => Promise<Claim>;
  readonly readClaim: (input: ReadClaimInput, context?: $ActionContext) => Promise<Claim[]>;
  readonly recordCompletion: (
    input: RecordCompletionInput,
    context?: $ActionContext,
  ) => Promise<Completion>;
  readonly readCompletion: (
    input: ReadCompletionInput,
    context?: $ActionContext,
  ) => Promise<Completion[]>;
  readonly addDependency: (
    input: AddDependencyInput,
    context?: $ActionContext,
  ) => Promise<Dependency>;
  readonly removeDependency: (
    input: RemoveDependencyInput,
    context?: $ActionContext,
  ) => Promise<void>;
  readonly readDependency: (
    input: ReadDependencyInput,
    context?: $ActionContext,
  ) => Promise<Dependency[]>;
  readonly recordEvidenceReference: (
    input: RecordEvidenceReferenceInput,
    context?: $ActionContext,
  ) => Promise<EvidenceReference>;
  readonly readEvidenceReference: (
    input: ReadEvidenceReferenceInput,
    context?: $ActionContext,
  ) => Promise<EvidenceReference[]>;
  readonly recordLateResult: (
    input: RecordLateResultInput,
    context?: $ActionContext,
  ) => Promise<LateResult>;
  readonly readLateResult: (
    input: ReadLateResultInput,
    context?: $ActionContext,
  ) => Promise<LateResult[]>;
  readonly acceptReview: (input: AcceptReviewInput, context?: $ActionContext) => Promise<Review>;
  readonly returnReview: (input: ReturnReviewInput, context?: $ActionContext) => Promise<Review>;
  readonly readReview: (input: ReadReviewInput, context?: $ActionContext) => Promise<Review[]>;
  readonly submitSubmission: (
    input: SubmitSubmissionInput,
    context?: $ActionContext,
  ) => Promise<Submission>;
  readonly readSubmission: (
    input: ReadSubmissionInput,
    context?: $ActionContext,
  ) => Promise<Submission[]>;
  readonly createTask: (input: CreateTaskInput, context?: $ActionContext) => Promise<Task>;
  readonly updateTask: (input: UpdateTaskInput, context?: $ActionContext) => Promise<Task>;
  readonly setPriorityTask: (
    input: SetPriorityTaskInput,
    context?: $ActionContext,
  ) => Promise<Task>;
  readonly moveTask: (input: MoveTaskInput, context?: $ActionContext) => Promise<Task>;
  readonly reopenTask: (input: ReopenTaskInput, context?: $ActionContext) => Promise<Task>;
  readonly readTask: (input: ReadTaskInput, context?: $ActionContext) => Promise<Task[]>;
}

/** One function per read action, reading inside the running transaction. A read through `tx` runs no read policy. */
export interface Reads {
  readonly readEvent: (input: ReadEventInput) => Promise<Event[]>;
  readonly readAttempt: (input: ReadAttemptInput) => Promise<Attempt[]>;
  readonly readInvocation: (input: ReadInvocationInput) => Promise<Invocation[]>;
  readonly readMachine: (input: ReadMachineInput) => Promise<Machine[]>;
  readonly readRun: (input: ReadRunInput) => Promise<Run[]>;
  readonly readSessionReference: (input: ReadSessionReferenceInput) => Promise<SessionReference[]>;
  readonly readCollaborator: (input: ReadCollaboratorInput) => Promise<Collaborator[]>;
  readonly readMembership: (input: ReadMembershipInput) => Promise<Membership[]>;
  readonly readWorkspace: (input: ReadWorkspaceInput) => Promise<Workspace[]>;
  readonly readAssignment: (input: ReadAssignmentInput) => Promise<Assignment[]>;
  readonly readClaim: (input: ReadClaimInput) => Promise<Claim[]>;
  readonly readCompletion: (input: ReadCompletionInput) => Promise<Completion[]>;
  readonly readDependency: (input: ReadDependencyInput) => Promise<Dependency[]>;
  readonly readEvidenceReference: (
    input: ReadEvidenceReferenceInput,
  ) => Promise<EvidenceReference[]>;
  readonly readLateResult: (input: ReadLateResultInput) => Promise<LateResult[]>;
  readonly readReview: (input: ReadReviewInput) => Promise<Review[]>;
  readonly readSubmission: (input: ReadSubmissionInput) => Promise<Submission[]>;
  readonly readTask: (input: ReadTaskInput) => Promise<Task[]>;
}
