// Do not edit this file by hand.
// It is generated by `mesh build` from the entity files; change them and rebuild.
// Import it as "#mesh"; the other files in this folder are an implementation detail.
// Mesh's own imports and internal names carry a `$` so that no entity or action name can collide with them.

import {
  FrameworkError as $FrameworkError,
  type BindOptions as $BindOptions,
  type ContextArgument as $ContextArgument,
  type DataLayer as $DataLayer,
} from "@meshfw/runtime";
import { bindEvent } from "./audit/event.actions";
import type {
  Event,
  RecordEventInput,
  ReadEventInput,
  EventFilter,
  EventSort,
  EventLoadable,
  EventWith,
} from "./audit/event.types";
import { bindAttempt } from "./execution/attempt.actions";
import type {
  Attempt,
  StartAttemptInput,
  ReadAttemptInput,
  AttemptFilter,
  AttemptSort,
  AttemptLoadable,
  AttemptWith,
} from "./execution/attempt.types";
import { bindInvocation } from "./execution/invocation.actions";
import type {
  Invocation,
  RecordInvocationInput,
  CorrectInvocationInput,
  ReadInvocationInput,
  InvocationFilter,
  InvocationSort,
  InvocationLoadable,
  InvocationWith,
} from "./execution/invocation.types";
import { bindMachine } from "./execution/machine.actions";
import type {
  Machine,
  RegisterMachineInput,
  UpdateMachineInput,
  ReadMachineInput,
  MachineFilter,
  MachineSort,
  MachineLoadable,
  MachineWith,
} from "./execution/machine.types";
import { bindRun } from "./execution/run.actions";
import type {
  Run,
  StartRunInput,
  ReadRunInput,
  RunFilter,
  RunSort,
  RunLoadable,
  RunWith,
} from "./execution/run.types";
import { bindSessionReference } from "./execution/sessionReference.actions";
import type {
  SessionReference,
  RecordSessionReferenceInput,
  SetAvailabilitySessionReferenceInput,
  RedactSessionReferenceInput,
  ReadSessionReferenceInput,
  SessionReferenceFilter,
  SessionReferenceSort,
  SessionReferenceLoadable,
  SessionReferenceWith,
} from "./execution/sessionReference.types";
import { bindCollaborator } from "./identity/collaborator.actions";
import type {
  Collaborator,
  RegisterCollaboratorInput,
  UpdateCollaboratorInput,
  ReadCollaboratorInput,
  CollaboratorFilter,
  CollaboratorSort,
  CollaboratorLoadable,
  CollaboratorWith,
} from "./identity/collaborator.types";
import { bindMembership } from "./identity/membership.actions";
import type {
  Membership,
  GrantMembershipInput,
  ChangeRoleMembershipInput,
  ReadMembershipInput,
  MembershipFilter,
  MembershipSort,
  MembershipLoadable,
  MembershipWith,
} from "./identity/membership.types";
import { bindWorkspace } from "./identity/workspace.actions";
import type {
  Workspace,
  CreateWorkspaceInput,
  RenameWorkspaceInput,
  ReadWorkspaceInput,
  WorkspaceFilter,
  WorkspaceSort,
} from "./identity/workspace.types";
import { bindAssignment } from "./work/assignment.actions";
import type {
  Assignment,
  StartAssignmentInput,
  ReadAssignmentInput,
  AssignmentFilter,
  AssignmentSort,
  AssignmentLoadable,
  AssignmentWith,
} from "./work/assignment.types";
import { bindClaim } from "./work/claim.actions";
import type {
  Claim,
  AcquireClaimInput,
  RenewClaimInput,
  ReleaseClaimInput,
  RevokeClaimInput,
  ReadClaimInput,
  ClaimFilter,
  ClaimSort,
  ClaimLoadable,
  ClaimWith,
} from "./work/claim.types";
import { bindCompletion } from "./work/completion.actions";
import type {
  Completion,
  RecordCompletionInput,
  ReadCompletionInput,
  CompletionFilter,
  CompletionSort,
  CompletionLoadable,
  CompletionWith,
} from "./work/completion.types";
import { bindDependency } from "./work/dependency.actions";
import type {
  Dependency,
  AddDependencyInput,
  RemoveDependencyInput,
  ReadDependencyInput,
  DependencyFilter,
  DependencySort,
  DependencyLoadable,
  DependencyWith,
} from "./work/dependency.types";
import { bindEvidenceReference } from "./work/evidenceReference.actions";
import type {
  EvidenceReference,
  RecordEvidenceReferenceInput,
  ReadEvidenceReferenceInput,
  EvidenceReferenceFilter,
  EvidenceReferenceSort,
  EvidenceReferenceLoadable,
  EvidenceReferenceWith,
} from "./work/evidenceReference.types";
import { bindLateResult } from "./work/lateResult.actions";
import type {
  LateResult,
  RecordLateResultInput,
  ReadLateResultInput,
  LateResultFilter,
  LateResultSort,
  LateResultLoadable,
  LateResultWith,
} from "./work/lateResult.types";
import { bindReview } from "./work/review.actions";
import type {
  Review,
  AcceptReviewInput,
  ReturnReviewInput,
  ReadReviewInput,
  ReviewFilter,
  ReviewSort,
  ReviewLoadable,
  ReviewWith,
} from "./work/review.types";
import { bindSubmission } from "./work/submission.actions";
import type {
  Submission,
  SubmitSubmissionInput,
  ReadSubmissionInput,
  SubmissionFilter,
  SubmissionSort,
  SubmissionLoadable,
  SubmissionWith,
} from "./work/submission.types";
import { bindTask } from "./work/task.actions";
import type {
  Task,
  CreateTaskInput,
  UpdateTaskInput,
  SetPriorityTaskInput,
  MoveTaskInput,
  ReopenTaskInput,
  ReadTaskInput,
  TaskFilter,
  TaskSort,
  TaskLoadable,
  TaskWith,
} from "./work/task.types";

export type {
  Event,
  RecordEventInput,
  ReadEventInput,
  EventFilter,
  EventSort,
  EventLoadable,
  EventWith,
  Attempt,
  StartAttemptInput,
  ReadAttemptInput,
  AttemptFilter,
  AttemptSort,
  AttemptLoadable,
  AttemptWith,
  Invocation,
  RecordInvocationInput,
  CorrectInvocationInput,
  ReadInvocationInput,
  InvocationFilter,
  InvocationSort,
  InvocationLoadable,
  InvocationWith,
  Machine,
  RegisterMachineInput,
  UpdateMachineInput,
  ReadMachineInput,
  MachineFilter,
  MachineSort,
  MachineLoadable,
  MachineWith,
  Run,
  StartRunInput,
  ReadRunInput,
  RunFilter,
  RunSort,
  RunLoadable,
  RunWith,
  SessionReference,
  RecordSessionReferenceInput,
  SetAvailabilitySessionReferenceInput,
  RedactSessionReferenceInput,
  ReadSessionReferenceInput,
  SessionReferenceFilter,
  SessionReferenceSort,
  SessionReferenceLoadable,
  SessionReferenceWith,
  Collaborator,
  RegisterCollaboratorInput,
  UpdateCollaboratorInput,
  ReadCollaboratorInput,
  CollaboratorFilter,
  CollaboratorSort,
  CollaboratorLoadable,
  CollaboratorWith,
  Membership,
  GrantMembershipInput,
  ChangeRoleMembershipInput,
  ReadMembershipInput,
  MembershipFilter,
  MembershipSort,
  MembershipLoadable,
  MembershipWith,
  Workspace,
  CreateWorkspaceInput,
  RenameWorkspaceInput,
  ReadWorkspaceInput,
  WorkspaceFilter,
  WorkspaceSort,
  Assignment,
  StartAssignmentInput,
  ReadAssignmentInput,
  AssignmentFilter,
  AssignmentSort,
  AssignmentLoadable,
  AssignmentWith,
  Claim,
  AcquireClaimInput,
  RenewClaimInput,
  ReleaseClaimInput,
  RevokeClaimInput,
  ReadClaimInput,
  ClaimFilter,
  ClaimSort,
  ClaimLoadable,
  ClaimWith,
  Completion,
  RecordCompletionInput,
  ReadCompletionInput,
  CompletionFilter,
  CompletionSort,
  CompletionLoadable,
  CompletionWith,
  Dependency,
  AddDependencyInput,
  RemoveDependencyInput,
  ReadDependencyInput,
  DependencyFilter,
  DependencySort,
  DependencyLoadable,
  DependencyWith,
  EvidenceReference,
  RecordEvidenceReferenceInput,
  ReadEvidenceReferenceInput,
  EvidenceReferenceFilter,
  EvidenceReferenceSort,
  EvidenceReferenceLoadable,
  EvidenceReferenceWith,
  LateResult,
  RecordLateResultInput,
  ReadLateResultInput,
  LateResultFilter,
  LateResultSort,
  LateResultLoadable,
  LateResultWith,
  Review,
  AcceptReviewInput,
  ReturnReviewInput,
  ReadReviewInput,
  ReviewFilter,
  ReviewSort,
  ReviewLoadable,
  ReviewWith,
  Submission,
  SubmitSubmissionInput,
  ReadSubmissionInput,
  SubmissionFilter,
  SubmissionSort,
  SubmissionLoadable,
  SubmissionWith,
  Task,
  CreateTaskInput,
  UpdateTaskInput,
  SetPriorityTaskInput,
  MoveTaskInput,
  ReopenTaskInput,
  ReadTaskInput,
  TaskFilter,
  TaskSort,
  TaskLoadable,
  TaskWith,
};
export {
  tables,
  assignmentTable,
  attemptTable,
  claimTable,
  collaboratorTable,
  completionTable,
  dependencyTable,
  eventTable,
  evidenceReferenceTable,
  invocationTable,
  lateResultTable,
  machineTable,
  membershipTable,
  reviewTable,
  runTable,
  sessionReferenceTable,
  submissionTable,
  taskTable,
  workspaceTable,
} from "./schema";
export {
  loadEventFields,
  loadAttemptFields,
  loadInvocationFields,
  loadMachineFields,
  loadRunFields,
  loadSessionReferenceFields,
  loadCollaboratorFields,
  loadMembershipFields,
  loadAssignmentFields,
  loadClaimFields,
  loadCompletionFields,
  loadDependencyFields,
  loadEvidenceReferenceFields,
  loadLateResultFields,
  loadReviewFields,
  loadSubmissionFields,
  loadTaskFields,
} from "./load";

/**
 * Every action function, bound to `layer`. Opens nothing and creates no table:
 * the caller owns the layer and closes it.
 */
export function bind(layer: $DataLayer, options: $BindOptions = {}) {
  const eventActions = bindEvent(layer, options);
  const attemptActions = bindAttempt(layer, options);
  const invocationActions = bindInvocation(layer, options);
  const machineActions = bindMachine(layer, options);
  const runActions = bindRun(layer, options);
  const sessionReferenceActions = bindSessionReference(layer, options);
  const collaboratorActions = bindCollaborator(layer, options);
  const membershipActions = bindMembership(layer, options);
  const workspaceActions = bindWorkspace(layer, options);
  const assignmentActions = bindAssignment(layer, options);
  const claimActions = bindClaim(layer, options);
  const completionActions = bindCompletion(layer, options);
  const dependencyActions = bindDependency(layer, options);
  const evidenceReferenceActions = bindEvidenceReference(layer, options);
  const lateResultActions = bindLateResult(layer, options);
  const reviewActions = bindReview(layer, options);
  const submissionActions = bindSubmission(layer, options);
  const taskActions = bindTask(layer, options);
  return Object.freeze({
    recordEvent: eventActions.record,
    readEvent: eventActions.read,
    startAttempt: attemptActions.start,
    readAttempt: attemptActions.read,
    recordInvocation: invocationActions.record,
    correctInvocation: invocationActions.correct,
    readInvocation: invocationActions.read,
    registerMachine: machineActions.register,
    updateMachine: machineActions.update,
    readMachine: machineActions.read,
    startRun: runActions.start,
    readRun: runActions.read,
    recordSessionReference: sessionReferenceActions.record,
    setAvailabilitySessionReference: sessionReferenceActions.setAvailability,
    redactSessionReference: sessionReferenceActions.redact,
    readSessionReference: sessionReferenceActions.read,
    registerCollaborator: collaboratorActions.register,
    updateCollaborator: collaboratorActions.update,
    readCollaborator: collaboratorActions.read,
    grantMembership: membershipActions.grant,
    changeRoleMembership: membershipActions.changeRole,
    readMembership: membershipActions.read,
    createWorkspace: workspaceActions.create,
    renameWorkspace: workspaceActions.rename,
    readWorkspace: workspaceActions.read,
    startAssignment: assignmentActions.start,
    readAssignment: assignmentActions.read,
    acquireClaim: claimActions.acquire,
    renewClaim: claimActions.renew,
    releaseClaim: claimActions.release,
    revokeClaim: claimActions.revoke,
    readClaim: claimActions.read,
    recordCompletion: completionActions.record,
    readCompletion: completionActions.read,
    addDependency: dependencyActions.add,
    removeDependency: dependencyActions.remove,
    readDependency: dependencyActions.read,
    recordEvidenceReference: evidenceReferenceActions.record,
    readEvidenceReference: evidenceReferenceActions.read,
    recordLateResult: lateResultActions.record,
    readLateResult: lateResultActions.read,
    acceptReview: reviewActions.accept,
    returnReview: reviewActions.return,
    readReview: reviewActions.read,
    submitSubmission: submissionActions.submit,
    readSubmission: submissionActions.read,
    createTask: taskActions.create,
    updateTask: taskActions.update,
    setPriorityTask: taskActions.setPriority,
    moveTask: taskActions.move,
    reopenTask: taskActions.reopen,
    readTask: taskActions.read,
  });
}

let $defaultBinding: ReturnType<typeof bind> | undefined;
let $defaultLayer: $DataLayer | undefined;
let $disconnecting: Promise<void> | undefined;
/** Calls through the top-level functions that have not settled; `disconnect()` waits for them. */
let $inFlight = 0;
const $idle: (() => void)[] = [];

function $isDataLayer(value: unknown): value is $DataLayer {
  return (
    typeof value === "object" &&
    value !== null &&
    typeof (value as Partial<$DataLayer>).transaction === "function" &&
    typeof (value as Partial<$DataLayer>).close === "function"
  );
}

/**
 * Bind every action function to the data layer `mesh.config.ts` configures. The
 * layer opens on the first transaction. Waits for a `disconnect()` in progress;
 * throws `FrameworkError` while connected.
 */
export async function connect(): Promise<void> {
  if ($disconnecting) await $disconnecting;
  if ($defaultLayer)
    throw new $FrameworkError("connect() was called while connected; call disconnect() first");
  const { default: config } = await import("../mesh.config");
  const data: unknown = config.data;
  if (!$isDataLayer(data))
    throw new $FrameworkError(
      `The data adapter "${config.data.name}" configured in mesh.config.ts has no run-time half: connect() needs a data layer with transaction() and close()`,
    );
  if ($defaultLayer)
    throw new $FrameworkError("connect() was called while connected; call disconnect() first");
  $defaultBinding = bind(data);
  $defaultLayer = data;
}

/**
 * Stop new calls, wait for the calls already made through the top-level functions to
 * settle, however long they take, then close the layer `connect()` bound. Does nothing
 * when not connected. If `close()` rejects, the binding is restored and the program
 * stays connected, so `disconnect()` can be called again. Never closes a layer passed
 * to `bind`.
 */
export async function disconnect(): Promise<void> {
  if ($disconnecting) return $disconnecting;
  const layer = $defaultLayer;
  const binding = $defaultBinding;
  if (!layer || !binding) return;
  $defaultBinding = undefined;
  $defaultLayer = undefined;
  $disconnecting = (async () => {
    while ($inFlight > 0) await new Promise<void>((resolve) => $idle.push(resolve));
    try {
      await layer.close();
    } catch (error) {
      $defaultBinding = binding;
      $defaultLayer = layer;
      throw error;
    }
  })();
  try {
    await $disconnecting;
  } finally {
    $disconnecting = undefined;
  }
}

/** Run one call on the default binding, counted so that `disconnect()` waits for it. */
async function $delegate<T>(
  name: string,
  call: (binding: ReturnType<typeof bind>) => Promise<T>,
): Promise<T> {
  if (!$defaultBinding)
    throw new $FrameworkError(
      `${name} was called while not connected: call connect() first, or use bind(db) with a data layer of your own`,
    );
  $inFlight++;
  try {
    return await call($defaultBinding);
  } finally {
    $inFlight--;
    if ($inFlight === 0) for (const resolve of $idle.splice(0)) resolve();
  }
}

export async function recordEvent(
  input: RecordEventInput,
  ...context: $ContextArgument
): Promise<Event> {
  return $delegate("recordEvent", (binding) => binding.recordEvent(input, ...context));
}

export async function readEvent(
  input: ReadEventInput,
  ...context: $ContextArgument
): Promise<Event[]> {
  return $delegate("readEvent", (binding) => binding.readEvent(input, ...context));
}

export async function startAttempt(
  input: StartAttemptInput,
  ...context: $ContextArgument
): Promise<Attempt> {
  return $delegate("startAttempt", (binding) => binding.startAttempt(input, ...context));
}

export async function readAttempt(
  input: ReadAttemptInput,
  ...context: $ContextArgument
): Promise<Attempt[]> {
  return $delegate("readAttempt", (binding) => binding.readAttempt(input, ...context));
}

export async function recordInvocation(
  input: RecordInvocationInput,
  ...context: $ContextArgument
): Promise<Invocation> {
  return $delegate("recordInvocation", (binding) => binding.recordInvocation(input, ...context));
}

export async function correctInvocation(
  input: CorrectInvocationInput,
  ...context: $ContextArgument
): Promise<Invocation> {
  return $delegate("correctInvocation", (binding) => binding.correctInvocation(input, ...context));
}

export async function readInvocation(
  input: ReadInvocationInput,
  ...context: $ContextArgument
): Promise<Invocation[]> {
  return $delegate("readInvocation", (binding) => binding.readInvocation(input, ...context));
}

export async function registerMachine(
  input: RegisterMachineInput,
  ...context: $ContextArgument
): Promise<Machine> {
  return $delegate("registerMachine", (binding) => binding.registerMachine(input, ...context));
}

export async function updateMachine(
  input: UpdateMachineInput,
  ...context: $ContextArgument
): Promise<Machine> {
  return $delegate("updateMachine", (binding) => binding.updateMachine(input, ...context));
}

export async function readMachine(
  input: ReadMachineInput,
  ...context: $ContextArgument
): Promise<Machine[]> {
  return $delegate("readMachine", (binding) => binding.readMachine(input, ...context));
}

export async function startRun(input: StartRunInput, ...context: $ContextArgument): Promise<Run> {
  return $delegate("startRun", (binding) => binding.startRun(input, ...context));
}

export async function readRun(input: ReadRunInput, ...context: $ContextArgument): Promise<Run[]> {
  return $delegate("readRun", (binding) => binding.readRun(input, ...context));
}

export async function recordSessionReference(
  input: RecordSessionReferenceInput,
  ...context: $ContextArgument
): Promise<SessionReference> {
  return $delegate("recordSessionReference", (binding) =>
    binding.recordSessionReference(input, ...context),
  );
}

export async function setAvailabilitySessionReference(
  input: SetAvailabilitySessionReferenceInput,
  ...context: $ContextArgument
): Promise<SessionReference> {
  return $delegate("setAvailabilitySessionReference", (binding) =>
    binding.setAvailabilitySessionReference(input, ...context),
  );
}

export async function redactSessionReference(
  input: RedactSessionReferenceInput,
  ...context: $ContextArgument
): Promise<SessionReference> {
  return $delegate("redactSessionReference", (binding) =>
    binding.redactSessionReference(input, ...context),
  );
}

export async function readSessionReference(
  input: ReadSessionReferenceInput,
  ...context: $ContextArgument
): Promise<SessionReference[]> {
  return $delegate("readSessionReference", (binding) =>
    binding.readSessionReference(input, ...context),
  );
}

export async function registerCollaborator(
  input: RegisterCollaboratorInput,
  ...context: $ContextArgument
): Promise<Collaborator> {
  return $delegate("registerCollaborator", (binding) =>
    binding.registerCollaborator(input, ...context),
  );
}

export async function updateCollaborator(
  input: UpdateCollaboratorInput,
  ...context: $ContextArgument
): Promise<Collaborator> {
  return $delegate("updateCollaborator", (binding) =>
    binding.updateCollaborator(input, ...context),
  );
}

export async function readCollaborator(
  input: ReadCollaboratorInput,
  ...context: $ContextArgument
): Promise<Collaborator[]> {
  return $delegate("readCollaborator", (binding) => binding.readCollaborator(input, ...context));
}

export async function grantMembership(
  input: GrantMembershipInput,
  ...context: $ContextArgument
): Promise<Membership> {
  return $delegate("grantMembership", (binding) => binding.grantMembership(input, ...context));
}

export async function changeRoleMembership(
  input: ChangeRoleMembershipInput,
  ...context: $ContextArgument
): Promise<Membership> {
  return $delegate("changeRoleMembership", (binding) =>
    binding.changeRoleMembership(input, ...context),
  );
}

export async function readMembership(
  input: ReadMembershipInput,
  ...context: $ContextArgument
): Promise<Membership[]> {
  return $delegate("readMembership", (binding) => binding.readMembership(input, ...context));
}

export async function createWorkspace(
  input: CreateWorkspaceInput,
  ...context: $ContextArgument
): Promise<Workspace> {
  return $delegate("createWorkspace", (binding) => binding.createWorkspace(input, ...context));
}

export async function renameWorkspace(
  input: RenameWorkspaceInput,
  ...context: $ContextArgument
): Promise<Workspace> {
  return $delegate("renameWorkspace", (binding) => binding.renameWorkspace(input, ...context));
}

export async function readWorkspace(
  input: ReadWorkspaceInput,
  ...context: $ContextArgument
): Promise<Workspace[]> {
  return $delegate("readWorkspace", (binding) => binding.readWorkspace(input, ...context));
}

export async function startAssignment(
  input: StartAssignmentInput,
  ...context: $ContextArgument
): Promise<Assignment> {
  return $delegate("startAssignment", (binding) => binding.startAssignment(input, ...context));
}

export async function readAssignment(
  input: ReadAssignmentInput,
  ...context: $ContextArgument
): Promise<Assignment[]> {
  return $delegate("readAssignment", (binding) => binding.readAssignment(input, ...context));
}

export async function acquireClaim(
  input: AcquireClaimInput,
  ...context: $ContextArgument
): Promise<Claim> {
  return $delegate("acquireClaim", (binding) => binding.acquireClaim(input, ...context));
}

export async function renewClaim(
  input: RenewClaimInput,
  ...context: $ContextArgument
): Promise<Claim> {
  return $delegate("renewClaim", (binding) => binding.renewClaim(input, ...context));
}

export async function releaseClaim(
  input: ReleaseClaimInput,
  ...context: $ContextArgument
): Promise<Claim> {
  return $delegate("releaseClaim", (binding) => binding.releaseClaim(input, ...context));
}

export async function revokeClaim(
  input: RevokeClaimInput,
  ...context: $ContextArgument
): Promise<Claim> {
  return $delegate("revokeClaim", (binding) => binding.revokeClaim(input, ...context));
}

export async function readClaim(
  input: ReadClaimInput,
  ...context: $ContextArgument
): Promise<Claim[]> {
  return $delegate("readClaim", (binding) => binding.readClaim(input, ...context));
}

export async function recordCompletion(
  input: RecordCompletionInput,
  ...context: $ContextArgument
): Promise<Completion> {
  return $delegate("recordCompletion", (binding) => binding.recordCompletion(input, ...context));
}

export async function readCompletion(
  input: ReadCompletionInput,
  ...context: $ContextArgument
): Promise<Completion[]> {
  return $delegate("readCompletion", (binding) => binding.readCompletion(input, ...context));
}

export async function addDependency(
  input: AddDependencyInput,
  ...context: $ContextArgument
): Promise<Dependency> {
  return $delegate("addDependency", (binding) => binding.addDependency(input, ...context));
}

export async function removeDependency(
  input: RemoveDependencyInput,
  ...context: $ContextArgument
): Promise<void> {
  return $delegate("removeDependency", (binding) => binding.removeDependency(input, ...context));
}

export async function readDependency(
  input: ReadDependencyInput,
  ...context: $ContextArgument
): Promise<Dependency[]> {
  return $delegate("readDependency", (binding) => binding.readDependency(input, ...context));
}

export async function recordEvidenceReference(
  input: RecordEvidenceReferenceInput,
  ...context: $ContextArgument
): Promise<EvidenceReference> {
  return $delegate("recordEvidenceReference", (binding) =>
    binding.recordEvidenceReference(input, ...context),
  );
}

export async function readEvidenceReference(
  input: ReadEvidenceReferenceInput,
  ...context: $ContextArgument
): Promise<EvidenceReference[]> {
  return $delegate("readEvidenceReference", (binding) =>
    binding.readEvidenceReference(input, ...context),
  );
}

export async function recordLateResult(
  input: RecordLateResultInput,
  ...context: $ContextArgument
): Promise<LateResult> {
  return $delegate("recordLateResult", (binding) => binding.recordLateResult(input, ...context));
}

export async function readLateResult(
  input: ReadLateResultInput,
  ...context: $ContextArgument
): Promise<LateResult[]> {
  return $delegate("readLateResult", (binding) => binding.readLateResult(input, ...context));
}

export async function acceptReview(
  input: AcceptReviewInput,
  ...context: $ContextArgument
): Promise<Review> {
  return $delegate("acceptReview", (binding) => binding.acceptReview(input, ...context));
}

export async function returnReview(
  input: ReturnReviewInput,
  ...context: $ContextArgument
): Promise<Review> {
  return $delegate("returnReview", (binding) => binding.returnReview(input, ...context));
}

export async function readReview(
  input: ReadReviewInput,
  ...context: $ContextArgument
): Promise<Review[]> {
  return $delegate("readReview", (binding) => binding.readReview(input, ...context));
}

export async function submitSubmission(
  input: SubmitSubmissionInput,
  ...context: $ContextArgument
): Promise<Submission> {
  return $delegate("submitSubmission", (binding) => binding.submitSubmission(input, ...context));
}

export async function readSubmission(
  input: ReadSubmissionInput,
  ...context: $ContextArgument
): Promise<Submission[]> {
  return $delegate("readSubmission", (binding) => binding.readSubmission(input, ...context));
}

export async function createTask(
  input: CreateTaskInput,
  ...context: $ContextArgument
): Promise<Task> {
  return $delegate("createTask", (binding) => binding.createTask(input, ...context));
}

export async function updateTask(
  input: UpdateTaskInput,
  ...context: $ContextArgument
): Promise<Task> {
  return $delegate("updateTask", (binding) => binding.updateTask(input, ...context));
}

export async function setPriorityTask(
  input: SetPriorityTaskInput,
  ...context: $ContextArgument
): Promise<Task> {
  return $delegate("setPriorityTask", (binding) => binding.setPriorityTask(input, ...context));
}

export async function moveTask(input: MoveTaskInput, ...context: $ContextArgument): Promise<Task> {
  return $delegate("moveTask", (binding) => binding.moveTask(input, ...context));
}

export async function reopenTask(
  input: ReopenTaskInput,
  ...context: $ContextArgument
): Promise<Task> {
  return $delegate("reopenTask", (binding) => binding.reopenTask(input, ...context));
}

export async function readTask(
  input: ReadTaskInput,
  ...context: $ContextArgument
): Promise<Task[]> {
  return $delegate("readTask", (binding) => binding.readTask(input, ...context));
}
