// Do not edit this file by hand.
// It is generated by `mesh build` from the entity files; change them and rebuild.

import { sqliteTable as _meshSqlite, integer, real, text } from "drizzle-orm/sqlite-core";

export const assignmentTable = _meshSqlite("assignments", {
  id: text("id").notNull().primaryKey(),
  reviewWaived: integer("reviewWaived", { mode: "boolean" }).notNull(),
  startedAt: integer("startedAt", { mode: "timestamp_ms" }).notNull(),
  endedAt: integer("endedAt", { mode: "timestamp_ms" }),
  endReason: text("endReason", { enum: ["reassigned", "unassigned"] }),
  taskId: text("taskId").notNull(),
  assigneeId: text("assigneeId").notNull(),
  delegatorId: text("delegatorId").notNull(),
});

export const attemptTable = _meshSqlite("attempts", {
  id: text("id").notNull().primaryKey(),
  step: text("step").notNull(),
  number: integer("number").notNull(),
  claimFence: integer("claimFence"),
  runtime: text("runtime"),
  outcome: text("outcome", { mode: "json" }),
  state: text("state", {
    enum: ["running", "succeeded", "failed", "stopped", "abandoned"],
  }).notNull(),
  endedAt: integer("endedAt", { mode: "timestamp_ms" }),
  version: integer("version").notNull(),
  startedAt: integer("startedAt", { mode: "timestamp_ms" }).notNull(),
  runId: text("runId").notNull(),
  taskId: text("taskId").notNull(),
  performerId: text("performerId").notNull(),
  delegatorId: text("delegatorId").notNull(),
  machineId: text("machineId"),
  sessionId: text("sessionId"),
});

export const claimTable = _meshSqlite("claims", {
  id: text("id").notNull().primaryKey(),
  fence: integer("fence").notNull(),
  acquiredAt: integer("acquiredAt", { mode: "timestamp_ms" }).notNull(),
  expiresAt: integer("expiresAt", { mode: "timestamp_ms" }).notNull(),
  endedAt: integer("endedAt", { mode: "timestamp_ms" }),
  endReason: text("endReason"),
  state: text("state", { enum: ["active", "released", "revoked", "expired"] }).notNull(),
  taskId: text("taskId").notNull(),
  holderId: text("holderId").notNull(),
});

export const collaboratorTable = _meshSqlite("collaborators", {
  id: text("id").notNull().primaryKey(),
  kind: text("kind", { enum: ["human", "agent"] }).notNull(),
  name: text("name").notNull(),
  state: text("state", { enum: ["active", "retired"] }).notNull(),
  version: integer("version").notNull(),
});

export const completionTable = _meshSqlite("completions", {
  id: text("id").notNull().primaryKey(),
  rule: text("rule", {
    enum: ["review-accepted", "performer-is-reviewer", "review-waived"],
  }).notNull(),
  completedAt: integer("completedAt", { mode: "timestamp_ms" }).notNull(),
  taskId: text("taskId").notNull(),
  submissionId: text("submissionId"),
  completedById: text("completedById").notNull(),
});

export const dependencyTable = _meshSqlite("dependencies", {
  id: text("id").notNull().primaryKey(),
  createdAt: integer("createdAt", { mode: "timestamp_ms" }).notNull(),
  dependentId: text("dependentId").notNull(),
  prerequisiteId: text("prerequisiteId").notNull(),
  createdById: text("createdById").notNull(),
});

export const eventTable = _meshSqlite("events", {
  seq: integer("seq").notNull().primaryKey(),
  type: text("type").notNull(),
  schemaVersion: integer("schemaVersion").notNull(),
  workspaceId: text("workspaceId").notNull(),
  recordType: text("recordType", {
    enum: ["workspace", "collaborator", "membership", "task", "evidence-reference"],
  }).notNull(),
  recordId: text("recordId").notNull(),
  recordVersion: integer("recordVersion").notNull(),
  actor: text("actor").notNull(),
  caller: text("caller").notNull(),
  occurredAt: integer("occurredAt", { mode: "timestamp_ms" }).notNull(),
  recordedAt: integer("recordedAt", { mode: "timestamp_ms" }).notNull(),
  cause: text("cause", { mode: "json" }).notNull(),
  checks: text("checks", { mode: "json" }),
  payload: text("payload", { mode: "json" }).notNull(),
  taskId: text("taskId"),
});

export const evidenceReferenceTable = _meshSqlite("evidence_references", {
  id: text("id").notNull().primaryKey(),
  kind: text("kind").notNull(),
  locator: text("locator").notNull(),
  contentHash: text("contentHash"),
  description: text("description"),
  recordedAt: integer("recordedAt", { mode: "timestamp_ms" }).notNull(),
  recordedById: text("recordedById").notNull(),
});

export const invocationTable = _meshSqlite("invocations", {
  id: text("id").notNull().primaryKey(),
  requestedProvider: text("requestedProvider"),
  requestedModel: text("requestedModel"),
  actualProvider: text("actualProvider"),
  actualModel: text("actualModel"),
  inputTokens: integer("inputTokens"),
  outputTokens: integer("outputTokens"),
  cacheReadTokens: integer("cacheReadTokens"),
  cacheWriteTokens: integer("cacheWriteTokens"),
  usageSource: text("usageSource", { enum: ["runtime", "provider", "estimate"] }).notNull(),
  estimatedCost: real("estimatedCost"),
  pricingBasis: text("pricingBasis"),
  startedAt: integer("startedAt", { mode: "timestamp_ms" }),
  endedAt: integer("endedAt", { mode: "timestamp_ms" }),
  reason: text("reason"),
  recordedAt: integer("recordedAt", { mode: "timestamp_ms" }).notNull(),
  attemptId: text("attemptId").notNull(),
  taskId: text("taskId").notNull(),
  sessionId: text("sessionId"),
  correctsId: text("correctsId"),
  recordedById: text("recordedById").notNull(),
});

export const lateResultTable = _meshSqlite("late_results", {
  id: text("id").notNull().primaryKey(),
  fence: integer("fence").notNull(),
  summary: text("summary"),
  evidence: text("evidence", { mode: "json" }).notNull(),
  recordedAt: integer("recordedAt", { mode: "timestamp_ms" }).notNull(),
  taskId: text("taskId").notNull(),
  submitterId: text("submitterId").notNull(),
});

export const machineTable = _meshSqlite("machines", {
  id: text("id").notNull().primaryKey(),
  name: text("name").notNull().unique(),
  platform: text("platform"),
  state: text("state", { enum: ["active", "retired"] }).notNull(),
  version: integer("version").notNull(),
  registeredAt: integer("registeredAt", { mode: "timestamp_ms" }).notNull(),
  firstReportedById: text("firstReportedById"),
});

export const membershipTable = _meshSqlite("memberships", {
  id: text("id").notNull().primaryKey(),
  role: text("role", { enum: ["owner", "member", "guest"] }).notNull(),
  state: text("state", { enum: ["active", "revoked"] }).notNull(),
  grantedAt: integer("grantedAt", { mode: "timestamp_ms" }).notNull(),
  revokedAt: integer("revokedAt", { mode: "timestamp_ms" }),
  version: integer("version").notNull(),
  collaboratorId: text("collaboratorId").notNull(),
  grantedById: text("grantedById").notNull(),
  revokedById: text("revokedById"),
});

export const reviewTable = _meshSqlite("reviews", {
  id: text("id").notNull().primaryKey(),
  decision: text("decision", { enum: ["accept", "return"] }).notNull(),
  reasons: text("reasons"),
  ruleApplied: text("ruleApplied", {
    enum: ["parent-assignee", "parent-creator", "task-creator"],
  }).notNull(),
  decidedAt: integer("decidedAt", { mode: "timestamp_ms" }).notNull(),
  submissionId: text("submissionId").notNull(),
  reviewerId: text("reviewerId").notNull(),
});

export const runTable = _meshSqlite("runs", {
  id: text("id").notNull().primaryKey(),
  inputs: text("inputs", { mode: "json" }).notNull(),
  outcome: text("outcome", { mode: "json" }),
  state: text("state", { enum: ["running", "succeeded", "failed", "canceled"] }).notNull(),
  cancelReason: text("cancelReason"),
  endedAt: integer("endedAt", { mode: "timestamp_ms" }),
  version: integer("version").notNull(),
  startedAt: integer("startedAt", { mode: "timestamp_ms" }).notNull(),
  taskId: text("taskId").notNull(),
  responsibleId: text("responsibleId").notNull(),
  startedById: text("startedById").notNull(),
  parentRunId: text("parentRunId"),
});

export const sessionReferenceTable = _meshSqlite("session_references", {
  id: text("id").notNull().primaryKey(),
  runtime: text("runtime").notNull(),
  runtimeSessionId: text("runtimeSessionId").notNull(),
  availability: text("availability", {
    enum: ["complete", "partial", "unavailable", "redacted"],
  }).notNull(),
  location: text("location"),
  version: integer("version").notNull(),
  recordedAt: integer("recordedAt", { mode: "timestamp_ms" }).notNull(),
  machineId: text("machineId").notNull(),
  agentProfileId: text("agentProfileId").notNull(),
  recordedById: text("recordedById").notNull(),
});

export const submissionTable = _meshSqlite("submissions", {
  id: text("id").notNull().primaryKey(),
  summary: text("summary"),
  evidence: text("evidence", { mode: "json" }).notNull(),
  fence: integer("fence"),
  taskVersion: integer("taskVersion").notNull(),
  state: text("state", { enum: ["pending", "accepted", "returned", "withdrawn"] }).notNull(),
  submittedAt: integer("submittedAt", { mode: "timestamp_ms" }).notNull(),
  taskId: text("taskId").notNull(),
  submitterId: text("submitterId").notNull(),
});

export const taskTable = _meshSqlite("tasks", {
  id: text("id").notNull().primaryKey(),
  title: text("title").notNull(),
  intent: text("intent"),
  priority: integer("priority"),
  state: text("state", { enum: ["open", "done", "canceled"] }).notNull(),
  version: integer("version").notNull(),
  createdAt: integer("createdAt", { mode: "timestamp_ms" }).notNull(),
  parentId: text("parentId"),
  creatorId: text("creatorId").notNull(),
});

export const workspaceTable = _meshSqlite("workspaces", {
  id: text("id").notNull().primaryKey(),
  name: text("name"),
  location: text("location", { enum: ["local", "shared"] }).notNull(),
  state: text("state", { enum: ["active", "moved"] }).notNull(),
  version: integer("version").notNull(),
});

export const tables = {
  assignment: assignmentTable,
  attempt: attemptTable,
  claim: claimTable,
  collaborator: collaboratorTable,
  completion: completionTable,
  dependency: dependencyTable,
  event: eventTable,
  evidenceReference: evidenceReferenceTable,
  invocation: invocationTable,
  lateResult: lateResultTable,
  machine: machineTable,
  membership: membershipTable,
  review: reviewTable,
  run: runTable,
  sessionReference: sessionReferenceTable,
  submission: submissionTable,
  task: taskTable,
  workspace: workspaceTable,
};
