import { existsSync, readdirSync, readFileSync } from "node:fs";
import { extname, join, relative, sep } from "node:path";
import type { DataDiagnostic } from "@mxlang/data";
import { parseEntitySource } from "../src/build.ts";

// ADR-0043: only packages declaring tag contracts may mention MX; extensions join in M6.
export const MX_IMPORT_PACKAGES = ["packages/compiler"] as const;

/**
 * The one `@mxlang` mention allowed outside those packages.
 *
 * The docs site highlights `mx` fences with MX's own tree-sitter highlighter,
 * which is the published `@mxlang/tree-sitter-mx` (ADR-0065). It is a build-time
 * grammar for the documentation, not the entity vocabulary, so `@mxlang/core` and
 * `@mxlang/data` stay forbidden everywhere outside `packages/compiler` and only
 * this one package name passes in `apps/docs`. A blanket exemption for the docs
 * app would have let the vocabulary's own packages back in.
 */
export const MX_HIGHLIGHTER_PACKAGE = "@mxlang/tree-sitter-mx";

/**
 * The offset of the first `@mxlang` mention in `source` that is not the
 * highlighter, or -1. `@mxlang/tree-sitter-mx-something` does not pass: the name
 * must end where the package name ends.
 */
function firstForbiddenMxMention(source: string): number {
  for (let at = 0; ;) {
    const found = source.indexOf("@mxlang", at);
    if (found === -1) return -1;
    const end = found + MX_HIGHLIGHTER_PACKAGE.length;
    const next = source[end];
    if (source.startsWith(MX_HIGHLIGHTER_PACKAGE, found) && (next === undefined || !/[\w.-]/.test(next))) {
      at = end;
      continue;
    }
    return found;
  }
}
const sourceExtensions = new Set([".ts", ".tsx", ".mts", ".cts", ".js", ".jsx", ".mjs", ".cjs", ".json"]);
const lockFiles = new Set(["bun.lock", "bun.lockb", "bun.lock.json", "package-lock.json", "npm-shrinkwrap.json", "yarn.lock", "pnpm-lock.yaml"]);
const within = (path: string, dir: string) => path === dir || path.startsWith(`${dir}/`);

function walk(root: string, dir: string, allFiles = false, rule: "mx" | "drizzle" = "mx"): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const file = join(dir, entry.name);
    // Only host separators delimit segments; a POSIX backslash is a filename character.
    const path = relative(root, file).split(sep).join("/");
    if (!allFiles && (path.split("/").includes("node_modules") || within(path, "apps/docs/site") || within(path, "apps/docs/docs") ||
      (rule === "mx" && MX_IMPORT_PACKAGES.some((pkg) => within(path, pkg))))) return [];
    // Never follow symlinks into dependencies or outside the checkout.
    if (entry.isDirectory()) return walk(root, file, allFiles, rule);
    return entry.isFile() && (allFiles || (sourceExtensions.has(extname(file)) && !lockFiles.has(entry.name))) ? [file] : [];
  });
}

/** Deliberately text-only: comments, strings, wrappers and dependency fields all count.
 * Specifiers assembled at run time from pieces cannot be caught by this substring rule;
 * the package.json dependency rule plus code review are the backstop.
 *
 * The one exception is `MX_HIGHLIGHTER_PACKAGE`, the docs site's grammar (ADR-0065).
 */
export function checkMxImports(root: string): string[] {
  return ["packages", "apps", "examples"].flatMap((group) => walk(root, join(root, group))).sort().flatMap((file) => {
    const source = readFileSync(file, "utf8");
    const first = firstForbiddenMxMention(source);
    if (first === -1) return [];
    const path = relative(root, file).split(sep).join("/");
    const line = source.slice(0, first).split(/\r\n|\r|\n/).length;
    return [`${path}:${line}: Mention of @mxlang is forbidden here (ADR-0043), including comments and strings; move the code into packages/compiler or remove the mention`];
  });
}

/**
 * ADR-0014: Drizzle (`drizzle-orm`, `drizzle-kit`) is imported only by data adapters
 * and by the schema they emit. One allow-list; everything else in the checkout that
 * mentions either package, comments and strings included, fails. Docs content
 * (`apps/docs/docs`, skipped by the walker), manifests and lockfiles name packages
 * without importing them, and the rule's own files name what they forbid.
 */
export const DRIZZLE_IMPORT_ALLOWLIST: readonly ((path: string, source: string) => boolean)[] = [
  (path) => /^packages\/data-[^/]+\//.test(path),
  // An emitted schema: a project's `.mesh/schema.ts` that carries the generated header.
  (path, source) => /(?:^|\/)\.mesh\/schema\.ts$/.test(path) && source.startsWith("// Do not edit this file by hand.\n// It is generated by `mesh build`"),
  (path) => path.split("/").at(-1) === "package.json" || lockFiles.has(path.split("/").at(-1) ?? ""),
  // The docs navigation names ADR-0014 by its title.
  (path) => path === "apps/docs/docmd.config.json",
  (path) => /^packages\/compiler\/test\/repository-checks(?:\.test)?\.ts$/.test(path),
];

export function checkDrizzleImports(root: string): string[] {
  return walk(root, root, false, "drizzle").sort().flatMap((file) => {
    const source = readFileSync(file, "utf8");
    const path = relative(root, file).split(sep).join("/");
    if (DRIZZLE_IMPORT_ALLOWLIST.some((allow) => allow(path, source))) return [];
    const match = /drizzle-orm|drizzle-kit/.exec(source);
    if (!match) return [];
    const line = source.slice(0, match.index).split(/\r\n|\r|\n/).length;
    return [`${path}:${line}: Drizzle is allowed only in data adapters and the emitted schema (ADR-0014); remove ${match[0]} from this file`];
  });
}

/**
 * Acceptance test 4 for generated code: nothing under a project's output folder
 * (`.mesh/`) imports the build half or Drizzle. Every code file under a `.mesh/`
 * folder in `examples/` and `apps/` is read as text, comments and strings included:
 * `@meshfw/model`, `@meshfw/compiler` and `model.json` are forbidden everywhere,
 * and Drizzle everywhere except the emitted `.mesh/schema.ts`. `model.json` itself
 * is data, not code, and is not scanned. Finding no `.mesh/` folder is an error, so
 * the rule cannot pass vacuously.
 */
export function checkGeneratedImports(root: string): string[] {
  const files = ["examples", "apps"].filter((group) => existsSync(join(root, group)))
    .flatMap((group) => walk(root, join(root, group), false, "drizzle"))
    .filter((file) => relative(root, file).split(sep).includes(".mesh") && extname(file) !== ".json").sort();
  if (files.length === 0) return ["examples: No generated .mesh/ files scanned"];
  return files.flatMap((file) => {
    const source = readFileSync(file, "utf8");
    const path = relative(root, file).split(sep).join("/");
    const schema = /(?:^|\/)\.mesh\/schema\.ts$/.test(path);
    const forbidden = schema ? /@meshfw\/model|@meshfw\/compiler|model\.json/g : /@meshfw\/model|@meshfw\/compiler|model\.json|drizzle-[a-z]+/g;
    return [...source.matchAll(forbidden)].map((match) =>
      `${path}:${source.slice(0, match.index).split(/\r\n|\r|\n/).length}: Generated code must not import ${match[0]} (roadmap M2, acceptance 4); it imports only @meshfw/runtime, zod, its sibling files, the adapter's schema.ts and (index.ts only) ../mesh.config`);
  });
}

const runtimeForbidden = ["@meshfw/model", "@meshfw/compiler", "drizzle-orm", "drizzle-kit"];

/** M2's text rules reuse M1's directory walker, scanning every runtime source file. */
export function checkRuntime(root: string, rule: "imports" | "web"): string[] {
  const dir = join(root, "packages/runtime/src");
  const files = existsSync(dir) ? walk(root, dir, true).sort() : [];
  const errors: string[] = [];
  if (files.length === 0) errors.push("packages/runtime/src: No runtime source files scanned");
  const report = (file: string, source: string, index: number, reason: string) => {
    const path = relative(root, file).split(sep).join("/");
    errors.push(`${path}:${source.slice(0, index).split(/\r\n|\r|\n/).length}: ${reason}`);
  };
  for (const file of files) {
    const source = readFileSync(file, "utf8");
    if (rule === "imports") {
      for (const name of runtimeForbidden) {
        const index = source.indexOf(name);
        if (index !== -1) report(file, source, index, `Runtime must not mention ${name}; move build-time or database-specific code out of runtime`);
      }
    } else {
      // Plain text on purpose, like M1: even comments and strings fail.
      // No parsing or token adjacency assumptions: inter-token comments cannot hide a mention.
      for (const match of source.matchAll(/bun:|node:|\bBun\b/g)) {
        report(file, source, match.index, `Runtime must use web-standard APIs; forbidden text ${match[0]} (including comments and strings)`);
      }
    }
  }
  if (rule === "imports") {
    const file = join(root, "packages/runtime/package.json");
    if (!existsSync(file)) errors.push("packages/runtime/package.json: Missing runtime manifest");
    else {
      const source = readFileSync(file, "utf8");
      // Scan the whole manifest text, including values such as npm: dependency aliases.
      for (const name of runtimeForbidden) {
        const index = source.indexOf(name);
        if (index !== -1) report(file, source, index, `Runtime manifest must not mention ${name} anywhere, including keys and values`);
      }
    }
  }
  return errors;
}

interface DocsBlock {
  /** Page the fence is on. */
  name: string;
  /** 1-based line of the opening fence. */
  line: number;
  /** The fence's lines, with a figure's `// @key:` annotations removed. */
  block: string[];
  /** False when the fence was never closed. */
  closed: boolean;
}

/** Docs fences plus ADR-0050's current reference, not historical ADR/fixture syntax. */
function docsMxBlocks(dir: string): DocsBlock[] {
  const blocks: DocsBlock[] = [];
  const pages = readdirSync(dir).filter((entry) => entry.endsWith(".md")).sort();
  const reference = "../architecture/decisions/0050-entity-file-syntax.md";
  if (existsSync(join(dir, reference))) pages.push(reference);
  for (const name of pages) {
    const lines = readFileSync(join(dir, name), "utf8").split(/\r?\n/);
    for (let i = 0; i < lines.length; i++) {
      const opening = /^ {0,3}(`{3,}|~{3,})(.*)$/.exec(lines[i]!);
      if (!opening) continue;
      const fence = opening[1]!;
      const line = i + 1;
      let block: string[] = [];
      let closed = false;
      while (++i < lines.length) {
        const closing = /^ {0,3}(`{3,}|~{3,})\s*$/.exec(lines[i]!);
        if (closing && closing[1]![0] === fence[0] && closing[1]!.length >= fence.length) { closed = true; break; }
        block.push(lines[i]!);
      }
      const language = opening[2]!.trim().split(/\s+/)[0];
      // The figure is one entity file too, once its `// @key:` annotations are removed.
      if (language === "mx-figure") block = block.filter((text) => !/^\s*\/\/\s*@/.test(text));
      else if (language !== "mx") continue;
      blocks.push({ name, line, block, closed });
    }
  }
  return blocks;
}

/**
 * Syntax v4 (ADR-0067): :name declares, &name refers to a member, and another
 * entity is imported. Fences parse as authored, through the compiler's own
 * parse (production contracts and `MESH_SYNTAX`). The bounded text guard below
 * adds what a parse of one fence cannot see: undeclared member heads,
 * unimported entity names and unbound `self.` reads.
 */
export const DOCS_SYNTAX = "syntax v4";

/** A complete v4 entity file: comments and imports may come first, then `entity :Name`. */
export function isV4EntityFile(block: string): boolean {
  for (const line of block.split("\n")) {
    const text = line.trim();
    if (text === "" || text.startsWith("//")) continue;
    if (text.startsWith("import ")) continue;
    return /^entity\s+:\w+/.test(text);
  }
  return false;
}

/**
 * An option whose value is a single name or enum value, written as a string:
 * `default="draft"`, `on:load="visible"`. A list is handled
 * by `V4_LIST_OF_QUOTED_NAMES` below.
 */
const V4_QUOTED_NAME =
  /(?:^|[\s])(auto|types|actions|load|sort|default|on|on:load|entity)=("[^"]*")/;

/**
 * An option whose value is a list written as quoted identifiers: `fields=[
 * "status", "amount"]`, `accept=["title"]`. Any option may hold such a list,
 * including one an extension adds (`audit fields=[...]`), because a list of
 * quoted identifiers is a list of names wherever it appears.
 *
 * The one exclusion is an option whose value is genuinely a list of text.
 * None of the v1 vocabulary has one — `table`, `message`, `code`, `of`,
 * `match` and `domain` are all single strings, and `values` holds enum values,
 * which are atoms, not text — so the set is empty and is kept as a named,
 * auditable place to add one. A *single* quoted value is not caught here: for
 * an option nobody has declared, `"some text"` and a name look the same, and
 * guessing would produce false findings on ordinary text.
 */
const V4_TEXT_LIST_OPTIONS = new Set<string>();
const V4_LIST_OF_QUOTED_NAMES =
  /(\b[a-z][a-z0-9-]*)=(\[\s*(?:"[\w-]+"\s*,?\s*)+\])/g;

/**
 * The first line of a block that is not written in syntax v4, or `null`.
 *
 * The parser cannot see any of this: `accept=["title"]` and `sort=[:dueOn]`
 * are perfectly good input to MX, so the block would parse and the page would
 * drift back to the old syntax without any check noticing. These are the rules
 * of the syntax the docs enforce, and this is where it enforces them.
 */
export function oldSpellingInV4(block: string): string | null {
  for (const [index, line] of block.split("\n").entries()) {
    const text = line.trim();
    if (text === "" || text.startsWith("//")) continue;
    if (/(?:^|\s)(?:accept|require)\s*=|^arguments\b/.test(text)) {
      return `line ${index + 1}: action input belongs in one \`input\` section (${text})`;
    }
    if (/\b(?:belongs-to|has-many|has-one)\s*=/.test(text) || /\bentity\s*=\s*:/.test(text)) {
      return `line ${index + 1}: a relationship is \`kind :name entity=ImportedName\` (${text})`;
    }
    if (/^(?:asc|desc)\s+:|^:\w+\s*=|\b(?:load|actions|fields)\s*=\s*\[[^\]]*:\w|\bon:load\s*=\s*:/.test(text)) {
      return `line ${index + 1}: a member reference is \`&name\`, not an atom (${text})`;
    }
    // A read's order is a `sort` section with `asc`/`desc` lines (ADR-0066).
    if (/(?:^|[\s])sort=/.test(text)) {
      return `line ${index + 1}: a read's order is a \`sort\` section with \`asc &field\` and \`desc &field\` lines, not a \`sort=\` option (${text})`;
    }
    const name = V4_QUOTED_NAME.exec(text);
    if (name) {
      return `line ${index + 1}: \`${name[1]}\` takes an atom, member reference or imported name, not a string (${text})`;
    }
    V4_LIST_OF_QUOTED_NAMES.lastIndex = 0;
    for (let list = V4_LIST_OF_QUOTED_NAMES.exec(text); list; list = V4_LIST_OF_QUOTED_NAMES.exec(text)) {
      if (V4_TEXT_LIST_OPTIONS.has(list[1]!)) continue;
      return `line ${index + 1}: \`${list[1]}\` takes atoms or member references, not strings (${text})`;
    }
    const oldName = /^[a-z][a-z0-9-]*\s+#(\w+)/.exec(text);
    if (oldName) return `line ${index + 1}: a declaration is \`kind :name options\`; \`#${oldName[1]}\` is the old spelling (${text})`;
  }
  return invalidMembersInV4(block);
}

// A bounded text guard for the documented fence shapes, not another MX parser.
// Strings/comments/regexes are blanked with rows and columns intact. The real
// parse owns grammar and member placement; this only resolves member heads and
// entity names within one fence.
const V4_TOKENS = /\/\/[^\n]*|\/\*[\s\S]*?\*\/|"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|`(?:\\.|[^`\\])*`|\/(?:\\.|[^/\n\\])+\/[a-z]*|&[A-Za-z_]\w*|[A-Za-z_$][\w$]*|\d+(?:\.\d+)?|===|!==|=>|&&|\|\||==|!=|<=|>=|\S/g;
const v4Operand = (previous: string) => previous === "" || /^(?:return|throw|typeof|void|delete|yield|await)$/.test(previous) ||
  /^(?:=>|&&|\|\||===|!==|==|!=|<=|>=|[=([{,:?!+*/%<>|&^~-])$/.test(previous);
const v4LineReference = (prefix: string) => /^[\t ]*$/.test(prefix) || /^[\t ]*(?:asc|desc)[\t ]+$/.test(prefix);
const V4_MEMBER_SECTIONS = new Set(["attributes", "relationships", "computed", "actions", "policies"]);

function invalidMembersInV4(source: string): string | null {
  const masked = source.replace(V4_TOKENS, (token) => /^["'`/]/.test(token)
    ? token.replace(/[^\r\n]/g, " ") : token);
  const members = new Set<string>();
  const imports = new Set<string>();
  const uses: { name: string; line: number; imported: boolean }[] = [];
  const parents: { indent: number; kind: string; self: boolean }[] = [];
  let previous = "";
  for (const [index, line] of masked.split("\n").entries()) {
    const text = line.trim();
    if (!text) continue;
    const at = index + 1;
    const indent = line.length - line.trimStart().length;
    while (parents.length && parents[parents.length - 1]!.indent >= indent) parents.pop();
    const parent = parents[parents.length - 1];
    const kind = /^([a-z][\w-]*)\b/.exec(text)?.[1] ?? "";
    const declaration = /^[a-z][\w-]*\s+:(\w+)/.exec(text);
    if (declaration && (V4_MEMBER_SECTIONS.has(parent?.kind ?? "") ||
      (kind === "check" && parents.some((entry) => entry.kind === "validate")))) members.add(declaration[1]!);
    const namedImport = /^import\s*\{([^}]+)\}/.exec(text);
    if (namedImport) for (const entry of namedImport[1]!.split(",")) {
      const local = /^\s*\w+(?:\s+as\s+(\w+))?\s*$/.exec(entry);
      if (local) imports.add(local[1] ?? entry.trim());
    }
    for (const match of text.matchAll(/\bentity\s*=\s*([A-Za-z_]\w*)/g)) {
      uses.push({ name: match[1]!, line: at, imported: true });
    }

    // One-line parameter lists and indented method/arrow bodies are the docs'
    // shapes. Delimiter depth bounds inline bodies too, so a nested arrow's self
    // cannot license a read after that arrow has ended. This only tracks scope;
    // the real parser still validates the syntax and delimiter kinds.
    const functions = [...line.matchAll(/\(([^()]*)\)\s*(?:=>|\{)|\b[A-Za-z_$]\w*\s*=>/g)].map((match) => {
      const parameters = match[1] ?? "";
      const self = /^\s*\{[\s\S]*\}\s*$/.test(parameters) &&
        /(?:^|,)\s*self\s*(?:,|$|=)/.test(parameters.trim().slice(1, -1));
      const block = match[0].endsWith("{");
      let depth = block ? 1 : 0;
      let end = match.index! + match[0].length;
      for (; end < line.length; end++) {
        const char = line[end]!;
        if ("([{".includes(char)) depth++;
        else if (")]}".includes(char)) {
          if (depth === 0 || (--depth === 0 && block)) break;
        } else if (depth === 0 && ",;".includes(char)) break;
      }
      return { start: match.index!, end, self };
    });
    for (const read of line.matchAll(/\bself\s*(?:\?\.|\.)/g)) {
      const fn = functions.filter((entry) => entry.start < read.index! && read.index! < entry.end).at(-1);
      if (!(fn ? fn.self : parent?.self)) return `line ${at}: self. requires self destructured in this function's parameters; prefer &name`;
    }
    for (const token of line.matchAll(V4_TOKENS)) {
      if (/^&\w/.test(token[0]) && (v4LineReference(line.slice(0, token.index)) || v4Operand(previous))) {
        uses.push({ name: token[0].slice(1), line: at, imported: false });
      }
      previous = token[0];
    }
    const fn = functions.filter((entry) => entry.end === line.length).at(-1);
    parents.push({ indent, kind, self: fn ? fn.self : parent?.self ?? false });
  }
  // Resolve after collecting the fence: forward member declarations are legal.
  for (const use of uses) {
    if (use.imported ? !imports.has(use.name) : !members.has(use.name)) {
      return use.imported
        ? `line ${use.line}: entity=${use.name} must name an import in this fence`
        : `line ${use.line}: &${use.name} is not a declared member of this entity`;
    }
  }
  return null;
}

/** A parser crash is a finding, not an exception. */
export function parseV4(source: string, file: string): DataDiagnostic[] {
  try {
    return parseEntitySource(source, file).diagnostics;
  } catch (cause) {
    return [{ severity: "error", message: `MX could not parse the block at all: ${(cause as Error).message.split("\n")[0]}`, line: 1, column: 0, offset: 0 }];
  }
}

/**
 * The stricter companion: every MX fence on the Docs pages must be a complete v4
 * entity file, so a page cannot drift back to another syntax, and every one of them
 * must parse. A block whose root is not `entity :Name` fails here.
 */
export function checkDocsSyntaxV4(dir: string) {
  let checked = 0;
  const blocks = docsMxBlocks(dir);
  const errors: string[] = [];
  for (const { name, line, block, closed } of blocks) {
    const where = `${name}:${line}`;
    if (!closed) { errors.push(`${where}: unclosed MX fence`); continue; }
    if (!isV4EntityFile(block.join("\n"))) {
      errors.push(`${where}: MX fence is not a complete ${DOCS_SYNTAX} entity file: its root must be \`entity :Name\``);
      continue;
    }
    checked++;
    const quoted = oldSpellingInV4(block.join("\n"));
    if (quoted) errors.push(`${where}: MX fence is not written in ${DOCS_SYNTAX}: ${quoted}`);
    for (const diagnostic of parseV4(`${block.join("\n")}\n`, where)) {
      errors.push(`${where}: MX block ${diagnostic.line}:${diagnostic.column + 1}: ${diagnostic.message}`);
    }
  }
  if (checked === 0) errors.push(`Docs ${DOCS_SYNTAX} check found no entity file on any Docs page`);
  console.log(`Docs ${DOCS_SYNTAX} entity files: ${checked} checked, ${errors.length} findings`);
  return { checked, errors };
}

export function checkDocsSamples(dir: string) {
  let parsed = 0;
  let skipped = 0;
  const blocks = docsMxBlocks(dir);
  const errors: string[] = [];
  for (const { name, line, block, closed } of blocks) {
    const where = `${name}:${line}`;
    if (!closed) errors.push(`${where}: unclosed MX fence`);
    // Every complete v4 fence is parsed as authored, with the production contracts.
    if (isV4EntityFile(block.join("\n"))) {
      parsed++;
      const old = oldSpellingInV4(block.join("\n"));
      if (old) errors.push(`${where}: MX fence is not written in ${DOCS_SYNTAX}: ${old}`);
      for (const diagnostic of parseV4(`${block.join("\n")}\n`, where)) {
        errors.push(`${where}: MX block ${diagnostic.line}:${diagnostic.column + 1}: ${diagnostic.message}`);
      }
      continue;
    }
    const root = block.find((text) => text.trim() !== "")?.trimStart() ?? "";
    // An entity file may open with its imports, so an `import` line heads a complete block too.
    if (!/^(entity\b|resource\b|import\s)/.test(root)) { skipped++; continue; }
    if (/^resource\b/.test(root)) errors.push(`${where}: MX fence is not written in ${DOCS_SYNTAX}: use entity :Name, not resource`);
    const diagnostics = parseEntitySource(`${block.join("\n")}\n`, join(dir, name)).diagnostics;
    parsed++;
    for (const diagnostic of diagnostics) {
      errors.push(`${where}: MX block ${diagnostic.line}:${diagnostic.column + 1}: ${diagnostic.message}`);
    }
  }
  if (parsed === 0) errors.push("Docs sample check parsed no complete entity blocks");
  console.log(`Docs MX samples: ${parsed} entity files checked, ${errors.length} findings`);
  return { parsed, skipped, errors };
}
