// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/identity/collaborator.mesh.mx; change that file and rebuild.

import { z } from "zod";

import type {
  RegisterCollaboratorInput,
  UpdateCollaboratorInput,
  ReadCollaboratorInput,
  CollaboratorFilter,
} from "./collaborator.types";

type Keys<T> = T extends Record<string, never> ? never : keyof T;

type SameShape<A, B> = [Keys<A>] extends [Keys<B>]
  ? [Keys<B>] extends [Keys<A>]
    ? [A] extends [B]
      ? [B] extends [A]
        ? true
        : false
      : false
    : false
  : false;

type Assert<T extends true> = T;

const comparison = <T extends z.ZodType>(value: T) =>
  z.strictObject({
    eq: value.nullable().optional(),
    ne: value.nullable().optional(),
    lt: value.optional(),
    lte: value.optional(),
    gt: value.optional(),
    gte: value.optional(),
    in: z.array(value).readonly().optional(),
    nil: z.boolean().optional(),
  });

// The cast is the schema's only gap: zod writes an absent key as `?: T | undefined`, which the
// strictest `exactOptionalPropertyTypes` setting does not let the filter type accept.
export const collaboratorFilter: z.ZodType<CollaboratorFilter> = z.lazy(
  () =>
    z.union([
      z.strictObject({ and: z.array(collaboratorFilter).readonly() }),
      z.strictObject({ or: z.array(collaboratorFilter).readonly() }),
      z.strictObject({
        id: comparison(z.uuid()).optional(),
        kind: comparison(z.enum(["human", "agent"])).optional(),
        name: comparison(z.string()).optional(),
        state: comparison(z.enum(["active", "retired"])).optional(),
        retiredAt: comparison(z.date()).optional(),
        version: comparison(z.int()).optional(),
        createdAt: comparison(z.date()).optional(),
      }),
    ]) as unknown as z.ZodType<CollaboratorFilter>,
);

export const collaboratorSort = z
  .array(
    z.enum([
      "id",
      "-id",
      "kind",
      "-kind",
      "name",
      "-name",
      "state",
      "-state",
      "retiredAt",
      "-retiredAt",
      "version",
      "-version",
      "createdAt",
      "-createdAt",
    ]),
  )
  .readonly();

export const registerCollaboratorInput = z.strictObject({
  kind: z.enum(["human", "agent"]),
  name: z.string(),
}) satisfies z.ZodType<RegisterCollaboratorInput>;

export type RegisterCollaboratorInputShape = Assert<
  SameShape<z.output<typeof registerCollaboratorInput>, RegisterCollaboratorInput>
>;

export const updateCollaboratorInput = z.strictObject({
  id: z.uuid(),
  name: z.string().optional(),
}) satisfies z.ZodType<UpdateCollaboratorInput>;

export type UpdateCollaboratorInputShape = Assert<
  SameShape<z.output<typeof updateCollaboratorInput>, UpdateCollaboratorInput>
>;

export const readCollaboratorInput = z.strictObject({
  filter: collaboratorFilter.optional(),
  sort: collaboratorSort.optional(),
  limit: z.int().min(0).optional(),
  offset: z.int().min(0).optional(),
}) satisfies z.ZodType<ReadCollaboratorInput>;

export type ReadCollaboratorInputShape = Assert<
  SameShape<z.output<typeof readCollaboratorInput>, ReadCollaboratorInput>
>;
