// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/identity/membership.mesh.mx; change that file and rebuild.

import { z } from "zod";

import type {
  GrantMembershipInput,
  ChangeRoleMembershipInput,
  ReadMembershipInput,
  MembershipFilter,
} from "./membership.types";

type Keys<T> = T extends Record<string, never> ? never : keyof T;

type SameShape<A, B> = [Keys<A>] extends [Keys<B>]
  ? [Keys<B>] extends [Keys<A>]
    ? [A] extends [B]
      ? [B] extends [A]
        ? true
        : false
      : false
    : false
  : false;

type Assert<T extends true> = T;

const comparison = <T extends z.ZodType>(value: T) =>
  z.strictObject({
    eq: value.nullable().optional(),
    ne: value.nullable().optional(),
    lt: value.optional(),
    lte: value.optional(),
    gt: value.optional(),
    gte: value.optional(),
    in: z.array(value).readonly().optional(),
    nil: z.boolean().optional(),
  });

// The cast is the schema's only gap: zod writes an absent key as `?: T | undefined`, which the
// strictest `exactOptionalPropertyTypes` setting does not let the filter type accept.
export const membershipFilter: z.ZodType<MembershipFilter> = z.lazy(
  () =>
    z.union([
      z.strictObject({ and: z.array(membershipFilter).readonly() }),
      z.strictObject({ or: z.array(membershipFilter).readonly() }),
      z.strictObject({
        id: comparison(z.uuid()).optional(),
        role: comparison(z.enum(["owner", "member", "guest"])).optional(),
        state: comparison(z.enum(["active", "revoked"])).optional(),
        grantedAt: comparison(z.date()).optional(),
        revokedAt: comparison(z.date()).optional(),
        version: comparison(z.int()).optional(),
        collaboratorId: comparison(z.string()).optional(),
        grantedById: comparison(z.string()).optional(),
        revokedById: comparison(z.string()).optional(),
      }),
    ]) as unknown as z.ZodType<MembershipFilter>,
);

export const membershipSort = z
  .array(
    z.enum([
      "id",
      "-id",
      "role",
      "-role",
      "state",
      "-state",
      "grantedAt",
      "-grantedAt",
      "revokedAt",
      "-revokedAt",
      "version",
      "-version",
      "collaboratorId",
      "-collaboratorId",
      "grantedById",
      "-grantedById",
      "revokedById",
      "-revokedById",
    ]),
  )
  .readonly();

export const grantMembershipInput = z.strictObject({
  role: z.enum(["owner", "member", "guest"]),
  grantedAt: z.date(),
  collaborator: z.uuid(),
  grantedBy: z.uuid().nullable().optional(),
}) satisfies z.ZodType<GrantMembershipInput>;

export type GrantMembershipInputShape = Assert<
  SameShape<z.output<typeof grantMembershipInput>, GrantMembershipInput>
>;

export const changeRoleMembershipInput = z.strictObject({
  id: z.uuid(),
  role: z.enum(["owner", "member", "guest"]).optional(),
}) satisfies z.ZodType<ChangeRoleMembershipInput>;

export type ChangeRoleMembershipInputShape = Assert<
  SameShape<z.output<typeof changeRoleMembershipInput>, ChangeRoleMembershipInput>
>;

export const readMembershipInput = z.strictObject({
  filter: membershipFilter.optional(),
  sort: membershipSort.optional(),
  limit: z.int().min(0).optional(),
  offset: z.int().min(0).optional(),
}) satisfies z.ZodType<ReadMembershipInput>;

export type ReadMembershipInputShape = Assert<
  SameShape<z.output<typeof readMembershipInput>, ReadMembershipInput>
>;
