// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/identity/membership.mesh.mx; change that file and rebuild.

import { z } from "zod";

import type {
  GrantMembershipInput,
  ChangeRoleMembershipInput,
  ReadMembershipInput,
  MembershipFilter,
} from "./membership.types";

type Keys<T> = T extends Record<string, never> ? never : keyof T;

type SameShape<A, B> = [Keys<A>] extends [Keys<B>]
  ? [Keys<B>] extends [Keys<A>]
    ? [A] extends [B]
      ? [B] extends [A]
        ? true
        : false
      : false
    : false
  : false;

type Assert<T extends true> = T;

const comparison = <T extends z.ZodType>(value: T) =>
  z
    .strictObject({
      eq: value.nullable().exactOptional(),
      ne: value.nullable().exactOptional(),
      lt: value.exactOptional(),
      lte: value.exactOptional(),
      gt: value.exactOptional(),
      gte: value.exactOptional(),
      in: z.array(value).readonly().exactOptional(),
      nil: z.boolean().exactOptional(),
    })
    .refine((operators) => Object.keys(operators).length > 0, {
      message: "a comparison needs an operator",
    });

export const membershipFilter: z.ZodType<MembershipFilter> = z.lazy(
  () =>
    z.union([
      z.strictObject({ and: z.array(membershipFilter).readonly() }),
      z.strictObject({ or: z.array(membershipFilter).readonly() }),
      z.strictObject({
        id: comparison(z.uuid()).exactOptional(),
        role: comparison(z.enum(["owner", "member", "guest"])).exactOptional(),
        state: comparison(z.enum(["active", "revoked"])).exactOptional(),
        grantedAt: comparison(z.date()).exactOptional(),
        revokedAt: comparison(z.date()).exactOptional(),
        version: comparison(z.int()).exactOptional(),
        collaboratorId: comparison(z.uuid()).exactOptional(),
        grantedById: comparison(z.uuid()).exactOptional(),
        revokedById: comparison(z.uuid()).exactOptional(),
      }),
    ]) as unknown as z.ZodType<MembershipFilter>,
);

export const membershipSort = z
  .array(
    z.enum([
      "id",
      "-id",
      "role",
      "-role",
      "state",
      "-state",
      "grantedAt",
      "-grantedAt",
      "revokedAt",
      "-revokedAt",
      "version",
      "-version",
      "collaboratorId",
      "-collaboratorId",
      "grantedById",
      "-grantedById",
      "revokedById",
      "-revokedById",
    ]),
  )
  .readonly();

export const grantMembershipInput = z.strictObject({
  role: z.enum(["owner", "member", "guest"]),
  grantedAt: z.date(),
  collaborator: z.uuid(),
  grantedBy: z.uuid(),
}) satisfies z.ZodType<GrantMembershipInput>;

export type GrantMembershipInputShape = Assert<
  SameShape<z.output<typeof grantMembershipInput>, GrantMembershipInput>
>;

export const changeRoleMembershipInput = z.strictObject({
  id: z.uuid(),
  role: z.enum(["owner", "member", "guest"]).optional(),
  expectedVersion: z.int().nullable().optional(),
}) satisfies z.ZodType<ChangeRoleMembershipInput>;

export type ChangeRoleMembershipInputShape = Assert<
  SameShape<z.output<typeof changeRoleMembershipInput>, ChangeRoleMembershipInput>
>;

export const readMembershipInput = z.strictObject({
  filter: membershipFilter.optional(),
  sort: membershipSort.optional(),
  limit: z.int().min(0).optional(),
  offset: z.int().min(0).optional(),
}) satisfies z.ZodType<ReadMembershipInput>;

export type ReadMembershipInputShape = Assert<
  SameShape<z.output<typeof readMembershipInput>, ReadMembershipInput>
>;
