// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/identity/membership.mesh.mx; change that file and rebuild.
// Mesh's own imports carry a `$` so that no entity name can shadow them.

import {
  NotFoundError as $NotFoundError,
  parseInput,
  type ContextArgument as $ContextArgument,
  type DataLayer as $DataLayer,
} from "@meshfw/runtime";
import type {
  Membership,
  GrantMembershipInput,
  ChangeRoleMembershipInput,
  ReadMembershipInput,
} from "./membership.types";
import {
  grantMembershipInput,
  changeRoleMembershipInput,
  readMembershipInput,
} from "./membership.validators";
import { tables } from "../schema";

export function bindMembership(layer: $DataLayer) {
  return Object.freeze({
    async grant(input: GrantMembershipInput, ...[_context]: $ContextArgument): Promise<Membership> {
      const parsed = await parseInput(grantMembershipInput, input);
      return layer.transaction(async (tx) => {
        const row = await tx.insert(tables.membership, {
          role: parsed.role,
          state: "active",
          grantedAt: parsed.grantedAt,
          revokedAt: null,
          version: 1,
          collaboratorId: parsed.collaborator,
          grantedById: parsed.grantedBy,
          revokedById: null,
        });
        return row as Membership;
      });
    },

    async changeRole(
      input: ChangeRoleMembershipInput,
      ...[_context]: $ContextArgument
    ): Promise<Membership> {
      const parsed = await parseInput(changeRoleMembershipInput, input);
      return layer.transaction(async (tx) => {
        const key = { id: parsed.id };
        const changes: Partial<Membership> = {};
        if (parsed.role !== undefined) changes.role = parsed.role;
        const row = await tx.updateByKey(tables.membership, key, changes);
        if (row === undefined) throw new $NotFoundError("Membership", key);
        return row as Membership;
      });
    },

    async read(input: ReadMembershipInput, ...[_context]: $ContextArgument): Promise<Membership[]> {
      const parsed = await parseInput(readMembershipInput, input);
      return layer.transaction(async (tx) => {
        return (await tx.select(tables.membership, {
          filter: parsed.filter,
          sort: parsed.sort,
          limit: parsed.limit,
          offset: parsed.offset,
        })) as Membership[];
      });
    },
  });
}
