// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/identity/membership.mesh.mx; change that file and rebuild.

import { expr as $, type Scope as $Scope } from "@meshfw/runtime";
import type { Membership } from "./membership.types";

/** What every expression of Membership reads. */
export type MembershipScope = $Scope<{
  self: Membership & { collaborator: any; grantedBy: any; revokedBy: any };
  input: any;
  actor: any;
  context: any;
  before: Membership | null;
  tx: any;
}>;
/** What the expressions that only run on a stored record (an update or a destroy) read: `before` is the stored record. */
export type MembershipStoredScope = MembershipScope & { before: Membership };

export const expressions = {
  // check :membershipActive that, translated (src/domain/identity/membership.mesh.mx:28:16)
  "changeRole.check.membershipActive.that": ($s: MembershipStoredScope) =>
    $.eq($s.self.state, "active"),
  // check :roleChanges that, translated (src/domain/identity/membership.mesh.mx:33:16)
  "changeRole.check.roleChanges.that": ($s: MembershipStoredScope) =>
    $.ne($s.self.role, $s.before?.role),
  // check :versionMatches that, translated (src/domain/identity/membership.mesh.mx:38:16)
  "changeRole.check.versionMatches.that": ($s: MembershipStoredScope) =>
    $.or($.isNull($s.input?.expectedVersion), $.eq($s.input?.expectedVersion, $s.self.version)),
  // check :versionMatches details, plain (unsupported-construct) (src/domain/identity/membership.mesh.mx:41:19)
  "changeRole.check.versionMatches.details": ($s: MembershipStoredScope) => {
    return (({ input, before }) => ({
      expectedVersion: input.expectedVersion,
      actualVersion: before.version,
    }))($s);
  },
  // set &version, translated (src/domain/identity/membership.mesh.mx:45:20)
  "changeRole.step.0.set.version": ($s: MembershipStoredScope) => $.add($s.self.version, 1),
} as const;
