// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/identity/workspace.mesh.mx; change that file and rebuild.

import { expr as $, type Scope as $Scope } from "@meshfw/runtime";
import type { Workspace } from "./workspace.types";

/** What every expression of Workspace reads. */
export type WorkspaceScope = $Scope<{
  self: Workspace;
  input: any;
  actor: any;
  context: any;
  before: Workspace | null;
  tx: any;
}>;
/** What the expressions that only run on a stored record (an update or a destroy) read: `before` is the stored record. */
export type WorkspaceStoredScope = WorkspaceScope & { before: Workspace };

export const expressions = {
  // check :workspaceActive that, translated (src/domain/identity/workspace.mesh.mx:19:16)
  "rename.check.workspaceActive.that": ($s: WorkspaceStoredScope) => $.eq($s.self.state, "active"),
  // check :versionMatches that, translated (src/domain/identity/workspace.mesh.mx:24:16)
  "rename.check.versionMatches.that": ($s: WorkspaceStoredScope) =>
    $.or($.isNull($s.input?.expectedVersion), $.eq($s.input?.expectedVersion, $s.self.version)),
  // check :versionMatches details, plain (unsupported-construct) (src/domain/identity/workspace.mesh.mx:27:19)
  "rename.check.versionMatches.details": ($s: WorkspaceStoredScope) => {
    return (({ before }) => ({ currentVersion: before.version }))($s);
  },
  // set &version, translated (src/domain/identity/workspace.mesh.mx:31:20)
  "rename.step.0.set.version": ($s: WorkspaceStoredScope) => $.add($s.self.version, 1),
} as const;
