// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/identity/workspace.mesh.mx; change that file and rebuild.
// Mesh's own imports carry a `$` so that no entity name can shadow them.

import {
  NotFoundError as $NotFoundError,
  parseInput,
  type ContextArgument as $ContextArgument,
  type DataLayer as $DataLayer,
} from "@meshfw/runtime";
import type {
  Workspace,
  CreateWorkspaceInput,
  RenameWorkspaceInput,
  ReadWorkspaceInput,
} from "./workspace.types";
import {
  createWorkspaceInput,
  renameWorkspaceInput,
  readWorkspaceInput,
} from "./workspace.validators";
import { tables } from "../schema";

export function bindWorkspace(layer: $DataLayer) {
  return Object.freeze({
    async create(input: CreateWorkspaceInput, ...[_context]: $ContextArgument): Promise<Workspace> {
      const parsed = await parseInput(createWorkspaceInput, input);
      return layer.transaction(async (tx) => {
        const row = await tx.insert(tables.workspace, {
          name: parsed.name === undefined ? null : parsed.name,
          location: parsed.location === undefined ? "local" : parsed.location,
          state: "active",
          version: 1,
        });
        return row as Workspace;
      });
    },

    async rename(input: RenameWorkspaceInput, ...[_context]: $ContextArgument): Promise<Workspace> {
      const parsed = await parseInput(renameWorkspaceInput, input);
      return layer.transaction(async (tx) => {
        const key = { id: parsed.id };
        const changes: Partial<Workspace> = {};
        if (parsed.name !== undefined) changes.name = parsed.name;
        const row = await tx.updateByKey(tables.workspace, key, changes);
        if (row === undefined) throw new $NotFoundError("Workspace", key);
        return row as Workspace;
      });
    },

    async read(input: ReadWorkspaceInput, ...[_context]: $ContextArgument): Promise<Workspace[]> {
      const parsed = await parseInput(readWorkspaceInput, input);
      return layer.transaction(async (tx) => {
        return (await tx.select(tables.workspace, {
          filter: parsed.filter,
          sort: parsed.sort,
          limit: parsed.limit,
          offset: parsed.offset,
        })) as Workspace[];
      });
    },
  });
}
