// Do not edit this file by hand.
// It is generated by `mesh build` from src/domain/identity/workspace.mesh.mx; change that file and rebuild.

import { z } from "zod";

import type {
  CreateWorkspaceInput,
  RenameWorkspaceInput,
  ReadWorkspaceInput,
  WorkspaceFilter,
} from "./workspace.types";

type Keys<T> = T extends Record<string, never> ? never : keyof T;

type SameShape<A, B> = [Keys<A>] extends [Keys<B>]
  ? [Keys<B>] extends [Keys<A>]
    ? [A] extends [B]
      ? [B] extends [A]
        ? true
        : false
      : false
    : false
  : false;

type Assert<T extends true> = T;

const comparison = <T extends z.ZodType>(value: T) =>
  z.strictObject({
    eq: value.nullable().optional(),
    ne: value.nullable().optional(),
    lt: value.optional(),
    lte: value.optional(),
    gt: value.optional(),
    gte: value.optional(),
    in: z.array(value).readonly().optional(),
    nil: z.boolean().optional(),
  });

// The cast is the schema's only gap: zod writes an absent key as `?: T | undefined`, which the
// strictest `exactOptionalPropertyTypes` setting does not let the filter type accept.
export const workspaceFilter: z.ZodType<WorkspaceFilter> = z.lazy(
  () =>
    z.union([
      z.strictObject({ and: z.array(workspaceFilter).readonly() }),
      z.strictObject({ or: z.array(workspaceFilter).readonly() }),
      z.strictObject({
        id: comparison(z.uuid()).optional(),
        name: comparison(z.string()).optional(),
        location: comparison(z.enum(["local", "shared"])).optional(),
        state: comparison(z.enum(["active"])).optional(),
        version: comparison(z.int()).optional(),
      }),
    ]) as unknown as z.ZodType<WorkspaceFilter>,
);

export const workspaceSort = z
  .array(
    z.enum([
      "id",
      "-id",
      "name",
      "-name",
      "location",
      "-location",
      "state",
      "-state",
      "version",
      "-version",
    ]),
  )
  .readonly();

export const createWorkspaceInput = z.strictObject({
  name: z.string().nullable().optional(),
  location: z.enum(["local", "shared"]).optional(),
}) satisfies z.ZodType<CreateWorkspaceInput>;

export type CreateWorkspaceInputShape = Assert<
  SameShape<z.output<typeof createWorkspaceInput>, CreateWorkspaceInput>
>;

export const renameWorkspaceInput = z.strictObject({
  id: z.uuid(),
  name: z.string().nullable().optional(),
}) satisfies z.ZodType<RenameWorkspaceInput>;

export type RenameWorkspaceInputShape = Assert<
  SameShape<z.output<typeof renameWorkspaceInput>, RenameWorkspaceInput>
>;

export const readWorkspaceInput = z.strictObject({
  filter: workspaceFilter.optional(),
  sort: workspaceSort.optional(),
  limit: z.int().min(0).optional(),
  offset: z.int().min(0).optional(),
}) satisfies z.ZodType<ReadWorkspaceInput>;

export type ReadWorkspaceInputShape = Assert<
  SameShape<z.output<typeof readWorkspaceInput>, ReadWorkspaceInput>
>;
